### ISSUE TITLE
RxScala

### ISSUE THREAD

**Issue by headinthebox** [ReactiveX/RxJava#1340]
I thought we agreed to keep `create` to avoid confusion (i.e. for those that watch the Coursera course) and all. So let's remove the annotation.

```
@deprecated("Use `apply[T](Subscriber[T] => Unit)` instead", "0.17.0")
```

**Comment by samuelgruetter** [comment]
It's now two years, later, and things might have changed since then, so maybe we should revisit this decision? That is, I suggest to deprecate and then remove the method

```
def create[T](f: Observer[T] => Subscription): Observable[T]
```

Is this cousera course still being taught?
I'm suggesting this because it seems that nowadays, people are not confused by the _absence_ of this method, but by its _presence_, see [this issue](https://github.com/ReactiveX/RxScala/issues/195).

**Comment by akarnokd** [comment]
Wrong project? RxJava no longer has such a create() factory method but one that takes `OnSubscribe<T>`:

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L93

although the `SyncOnSubscribe` and `AsyncOnSubscribe` overloads may pose some problems.

**Comment by samuelgruetter** [comment]
Oh, sorry, of course I meant RxScala. I just wrote it here because it belongs to this thread, and this thread was started when RxScala was in the same repo as RxJava.
