### ISSUE TITLE
Non-deterministic Hang - ExceptionsTest?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1536]
Three builds have hung around the same place, near here:

- rx.exceptions.ExceptionsTest > testStackOverflowIsThrown STANDARD_OUT
- rx.exceptions.ExceptionsTest STANDARD_OUT

The logs can be seen at:

- https://netflixoss.ci.cloudbees.com/job/RxJava-pull-requests/1456/console
- https://netflixoss.ci.cloudbees.com/job/RxJava-pull-requests/1432/console
- https://netflixoss.ci.cloudbees.com/job/RxJava-pull-requests/1461/console

I have tried to replicate in the `ExceptionsTest` code but have not succeeded.

**Comment by akarnokd** [comment]
What happens is that a StackOverflowError is thrown but the check for it close (the stack is still next to full) so the attempt to report it may again cause another StackOverflowError. So instead of causing an actual StackOverflow, we could just throw one similar to how ThreadDeath is tested. Btw. ```assertFalse(isComputerOn())```?

**Comment by akarnokd** [comment]
I haven't seen this failure a long time so closing.
