### ISSUE TITLE
Need Scheduler Shutdown

### ISSUE THREAD

**Issue by blesa** [ReactiveX/RxJava#1730]
Use of Schedulers.io() or Schedulers.computation() creates several executors (thread pools) which are never shutted down. Threads stay in memory until the whole JVM finishes. This causes memory leak warnings on Tomcat aplication server (while reloading web app). Maybe it also violates section 4.3 of Rx Design Guidelines (not sure about that).
There should be a method to gracefully terminate all schedulers and their executors (thread pools). I'd propose something like Schedulers.reset() (or .shutdown or .shutdownNow).
All default schedulers are now created in Schedulers class constructor and referenced from its final member variables. I think it should be changed and sequence like this should be possible:
Schedulers.io(); // singleton referencing schedulers is created, threads are running
Schedulers.reset(); // all executors are shutted down, threads are gone
...
Schedulers.io(); // a fresh new set of executors is initialized

**Comment by akarnokd** [comment]
There is a 3 months old proposal to solve the issue. Is it still relevant? @benjchristensen have you considered the latest update to the PR to be adequate?

**Comment by andrewclegg** [comment]
This also causes a conflict with tools like https://github.com/carrotsearch/randomizedtesting which do automatic thread leak detection at test time. Because I have no way of closing down the `RxComputationThreadPool-*` threads at the end of a test suite, randomizedtesting throws an exception.

**Comment by simonbasle** [comment]
hi everyone,

reviving this discussion since the issue came up with one of our users. Said user deploys our SDK in a JBoss instance and does hot redeploys (vs restarting the container). This leads to OOM because the RxJava threads (in this case from `Schedulers.computation()`) are never cleared, and they retain a reference to the whole application code via their `contextClassLoader`.

so :up: for this feature :)

continuing discussion, should we also expose a `public void shutdown()` method on the schedulers themselves / the `Scheduler` interface? or rather attempt to make it package protected so that only `Schedulers.reset()` can call its Schedulers shutdown method?

**Comment by davidmoten** [comment]
I have container based deployments too and am keen to see this PR succeed also.

**Comment by simonbasle** [comment]
ping @akarnokd @benjchristensen, has this been reviewed since last PR? could this be revived as is or does it need work?

**Comment by akarnokd** [comment]
The related PR is quite old and needs reapplication. I don't really have time for this now and decisions regarding RxJava have few and far between lately.

**Comment by headinthebox** [comment]
Why don't we let `Schedulers` be `Subscription`s?

**Comment by simonbasle** [comment]
@headinthebox that's an interesting idea, reusing an interface that is already close in semantics to `Closeable` in java and `IDisposable` in ReactiveExtensions, but still specific to RxJava.

if I go that way, how do you think the backward compatibility should be maintained? do a default implementation in the `Scheduler` abstract class?

**Comment by akarnokd** [comment]
> Why don't we let Schedulers be Subscriptions?

Because it is only half of the solution. It doesn't really matter what the method will be called that shuts down the `NewThreadWorker`s.

There are a few things to consider:

- Shutting down schedulers is a terminal state and since `Schedulers` references them from final fields, there is no way to resurrect them.
- If one needs resurrection, the entire shutdown mechanism should be implemented on `Schedulers` and somehow not expose the actual shutdown method on the `Scheduler` class. Plus, one has to switch to `volatile` references to the standard schedulers so they can be replaced at will, but @benjchristensen  expressed concerns regarding the added `volatile` reads of those scheduler instances putting overhead on Observable sequence creation.
- `computation()` scheduler is trivial to shutdown due to the known fixed set of workers, `trampoline()`, `test()` doesn't really matter, `newThread()` shuts down itself 'automatically' after (proper) use. The remaining trouble is with `io()` because one needs to track each worker created. This requires some concurrent datastructure and the `createWorker()`'s overhead will increase significantly.

See #1769 for my original proposal.

**Comment by MatthewDailey** [comment]
@akarnokd @benjchristensen @headinthebox I'd like to bump this again. The inability to adequately unit test concurrent code in an isolated way is a bug, not a potential enhancement. 

I can work around this by factoring my all my tests to their own suites but I think the easier and better solution is to improve RxJava. If I reapply your PR, will you be able to take a look and iterate with me if necessary?

**Comment by akarnokd** [comment]
@MatthewDailey I think it's faster if I'm doing it, but it could take weeks until it gets approved and more weeks until it gets released.

**Comment by MatthewDailey** [comment]
Ok, I'll get to refactoring then then. Thanks!

**Comment by akarnokd** [comment]
See my PR #3022 about the proposed implementation.

**Comment by MatthewDailey** [comment]
Thanks! I'll look forward to it getting released. I refactored our project to use the threadpool scheduler which seems to be sufficient for isolating our tests.

**Comment by akarnokd** [comment]
This comes up from time to time. The lastest PR is #3149 .

**Comment by Petikoch** [comment]
With 1.1.0 there is `Schedulers.shutdown()`. 
Issue solved? -> Close?

**Comment by akarnokd** [comment]
Yes. Closing via #3149.
