### ISSUE TITLE
Backpressure: Join

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1781]
Backpressure for `join` needs to be reviewed or implemented.

**Comment by akarnokd** [comment]
I think this can't be reasonably implemented. Since elements of both sources trigger a separate duration Observable, backpressure delay could change what overlapping events are. In addition, once a source emits, the value is combined with each open value from the other stream and thus controlling how many elements to emit is difficult. It may mean that at a given time, only a total of ```RxRingBuffer.SIZE``` elements can be active in the form ```left * right <= RxRingBuffer.SIZE```.

**Comment by headinthebox** [comment]
Yup, backpressure messes up anything that involves time.

**Comment by akarnokd** [comment]
I believe this operator can't really support backpressure without dropping, buffering or simply erroring out; the timing of the signals from the other observables and the cross-combination would skew.
