### ISSUE TITLE
observeOn() slowing things down considerably

### ISSUE THREAD

**Issue by daschl** [ReactiveX/RxJava#2157]
Hi folks,

I'm again hunting lost performance and this time it seems that `observeOn` is a major contributor. I think the workload itself is not so important, but I'm fetching 5 docs in a batch from the server, wait and then the next one.  Something like:

```java
while(true) {

    Observable
        .range(1, 5)
        .flatMap(new Func1<Integer, Observable<GetResponse>>() {
            @Override
            public Observable<GetResponse> call(Integer i) {
                return core.<GetResponse>send(new GetRequest("" + i, "default"));
            }
        })
        .doOnNext(new Action1<GetResponse>() {
            @Override
            public void call(GetResponse getResponse) {
                getResponse.content().release();
            }
        })
        .toBlocking()
        .last();
}
```

Now when I run it like this, I get 30k ops/s against my Couchbase Server cluster, which seems fair relatively. Now when I change the code to:

```java
.flatMap(new Func1<Integer, Observable<GetResponse>>() {
    @Override
    public Observable<GetResponse> call(Integer i) {
        return core.<GetResponse>send(new GetRequest("" + i, "default")).observeOn(env.scheduler());
    }
})
```

I'm not getting over 22k ops/s, which means I'm loosing 8k ops/s just by moving it onto a different scheduler. The thing is, I need to move it somewhere else to prevent users from stalling my IO threads. I expect "some" loss, but not that much.

I did JFR runs for both sessions over 5 minute periods. I'm not 100% sure what is causing the issues here, but one interesting thing is that with `observeOn` I get contention reported, without it there is no contention:

![screen shot 2014-12-22 at 13 43 26](https://cloud.githubusercontent.com/assets/29086/5525064/9138fec8-89e0-11e4-9c23-0bb8e5f813f5.png)

Also, it looks like the Interrupt Exceptions are back with observeOn (no shown when omitted):

![screen shot 2014-12-22 at 13 46 16](https://cloud.githubusercontent.com/assets/29086/5525097/ff9e1f4c-89e0-11e4-9e2c-abeafef9f015.png)

So my questions are basically:

1) can we improve the observeOn performance to be mostly on-par (loosing a few 100 ops/s I'm okay with)
2) if not, is there an alternative way to go that is faster?
3) @akarnokd didn't you fix the interrupts?

This is on 1.0.3

**Comment by benjchristensen** [comment]
I know I need to come back and spend some time on this. During Holidays I didn't spend much time on anything, and I'm rather busy in other "day job" items right now. Can this wait? Do you have a proposed change?

It seems the `InterruptedException` issue is the low hanging fruit I'd like solved.

**Comment by daschl** [comment]
Well, the only thing at this point is that I'm thinking about avoiding observeOn where possible, but its not a solution. If you grab the low hanging fruit, I'll be more than happy to verify :)

**Comment by akarnokd** [comment]
In #1207 I was wondering if observeOn can be improved by not using any queue since the schedulers already have their queues.

In your base case, you have 3 messages per value going through the observeOn: onNext, onCompleted and unsubscribe. I think the onCompleted could be omitted if you know exactly how many onNexts there will be: just use a take(5) after the observeOn so upstream is cleaned up. If you don't have control over onNext, you can always concat/merge with never(), although they are quite heavy, or create your simple operator which simply swallows onCompleted.

**Comment by benjchristensen** [comment]
Wouldn't it be more expensive to go through the queue used by the Executor since it would need to schedule a new task each time? The idea was that a single schedule step could drain many items from the queue, instead of each item needing to go through the scheduling overhead. 

It would be interesting to have concrete data comparing the two.

**Comment by akarnokd** [comment]
I did some performance enhancements in #2603. Could you check if you get your performance back?

**Comment by akarnokd** [comment]
Several performance enhancements have been merged relating observeOn, so closing. If you have further problems, please don't hesitate to reopen this issue or post a new one.

**Comment by daschl** [comment]
Sounds great, I'll do that if needed. Cheers and thanks again
