### ISSUE TITLE
SerializedObserver swallows post-termination exceptions

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2539]
The purpose of the class is to ensure event delivery contract, but when serializing multiple event sources in operators, non-fatal errors get swallowed after a terminal event. Because these exceptions might be still worth receiving somehow, I suggest routing them to the plugin's error handler.

Thoughts?

**Comment by benjchristensen** [comment]
There's no good answer for this as any operator can ignore events after a terminal operator as they are outside the contract. 

The `SerializedObserver` class is only for serializing, not for any other contract enforcement, but any operator can choose to enforce it. For example, `merge` is strict about terminal events as it uses it to do cleanup whereas `map` is lenient because it is a simple operator.
