### ISSUE TITLE
Add operator switchIf with condition

### ISSUE THREAD

**Issue by kboyarshinov** [ReactiveX/RxJava#2786]
It is like `switchIfEmpty` operator. But with an option to specify condition of switch.

Returns an Observable that emits items emitted by the source Observable, checks the specified predicate for each item, and then switches to alternate Observable if the condition is satisfied.
`Observable<T> switchIf(Func1<? super T,java.lang.Boolean> predicate, Observable<? extends T> alternate)`

**Comment by benjchristensen** [comment]
Does it keep emitting the source `T` events while the predicate is false? Once it hits true the first time it would now be subscribed to the alternate, so it doesn't seem like an `if` but more a `switchOn` since it will switch and now only be on the alternate. 

What types of use cases are you needing this for? Why is `flatMap` insufficient?

**Comment by kboyarshinov** [comment]
> Does it keep emitting the source T events while the predicate is false?

Yes
> What types of use cases are you needing this for? Why is flatMap insufficient?

Use case: check emitted data, if it is not valid switch on data explicitly valid. `flatMap` is ok. `lift` is also good fit. But it would be nice to have internal operator.

**Comment by akarnokd** [comment]
If a value of T triggered the switch, should that value be emitted before the switch or not?

**Comment by kboyarshinov** [comment]
@akarnokd No. If invalid data triggered the switch, it should not be emitted before the switch.

**Comment by akarnokd** [comment]
Not sure about this operator. Let's put this on hold for now.
