### ISSUE TITLE
OperatorPublish connect(connection) should not return null

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2803]
This is outstanding work from #2774.  I can have a go at it next week if no-one in a rush.

**Comment by akarnokd** [comment]
If you don't mind some Reactive-Streams style code, you can look at my [OperatorPublish](https://github.com/akarnokd/RxJavaFlow/blob/master/src/main/java/rx/internal/operators/OperatorPublish.java) which definitely doesn't return null on connection, but due to the half-finished project, I can't run all tests relying on it.

**Comment by davidmoten** [comment]
Looks to me that ```OperatorPublish``` needs a good chunk of rework (#2810) and that the ReactiveStreams code could be basis for a rewrite. I'd be happy to have a go at this but haven't much time on my hands this week and anyway it might make more sense for @akarnokd to do it as he's so familiar with the subject already (and would probably do it in the blink of an eye).

**Comment by akarnokd** [comment]
I'll add this to my todo list for this week.

**Comment by akarnokd** [comment]
The operator has been rewritten so it never returns null. Closing.
