### ISSUE TITLE
Question: contribute operator  flatMap maxConcurrent using backpressure

### ISSUE THREAD

**Issue by mhawrylczak** [ReactiveX/RxJava#2842]
Hi, 
Recently I made an operator  [flatMap max concurrent using backpressure - gist](https://gist.github.com/mhawrylczak/aadf246e329d07861097), and I wonder if it may bring some value to RxJava (of course after rewriting with JDK6, faster sychronization method, and missing tests). 
If yes, let me know and I create suitable pull request.

**Comment by akarnokd** [comment]
Hello. First of all, we already have a flatMap with max concurrency in [1.0.8](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L4581) but allow me to review the code:

  - The operator ignores downstream unsubscription. If the downstream used ```take()``` for example, neither the main source nor the Subscribers to the inner observables are unsubscribed
  - One should not call onXXX methods while inside a ```synchronized``` block or holding a ```j.u.c.Lock```.
  - The operator requests a limited amount of inner observables but ignores any downstream requests: for example, merging two Range(0, 1000) sources with max concurrency of 1 and requesting only a single value will still deliver both ranges completely.
  - Using doOnXXX methods to handle events is costly because they each add one additional layer and more subscribers are instantiated for a single upstream value than necessary.
  - ```LongAdder``` isn't meant to  replace AtomicLong when monotonic values are required.

**Comment by mhawrylczak** [comment]
Thank you for review. I knew about the flatMap max concurrency  operator, but wanted  to try do the same using backpressure - mainly for education purposes.
