### ISSUE TITLE
Using zip() with buffer() causes MissingBackpressureException

### ISSUE THREAD

**Issue by marshallpierce** [ReactiveX/RxJava#2924]
Not sure if this is related to a similar issue I had: https://github.com/ReactiveX/RxJava/issues/2850.

Repro is in https://bitbucket.org/marshallpierce/rxjava-merge-backpressure at org.mpierce.rxjava.zip.ExperimentMain. (I re-used the same repo as for that other bug in case they're related.)

What I'm doing is very simple: zipping a buffered observable with another observable.

**Comment by akarnokd** [comment]
The problem is that the two sources to zip run on different rate. The first millisecond buffer tries to produce 1000 items before the other produces a single. Since zip uses an internal buffer sized according to the settings you changed, the millisecond buffer will overflow it and cause the exception.

**Comment by marshallpierce** [comment]
I realized that just after I posted... I should add that this is an attempt to reproduce a case I'm seeing in our app where we have two buffer() streams, each using the *same* timeout, that hit this situation. I oversimplified to the point where it's no longer the same case...

**Comment by marshallpierce** [comment]
I'm unable to reproduce this. I think this may have been caused by severe thread deprioritization (app where I spotted the issue is an Android app, and I've only seen it when backgrounding the app is involved).
