### ISSUE TITLE
Overriding Computation Scheduler + using a flatMap causes hanging

### ISSUE THREAD

**Issue by hannesstruss** [ReactiveX/RxJava#2944]
When overriding the default computation scheduler in `RxJavaPlugins` with `Schedulers.immediate()`, the following situation hangs. Neither `Hallo` nor `Done` are printed. Overriding any of the other schedulers doesn't cause the hanging. It also doesn't hang when removing the `flatMap`. 

When subscribing on `Schedulers.io()`, `Done` is printed, but when additionally overriding `getIOScheduler()` in the `RxJavaSchedulersHook` to be `Schedulers.io()`, it hangs again.

I'm not sure if it's good practice to reference `Schedulers` from the `RxJavaSchedulersHook` subclass.

Tested with `1.0.10` and current `1.x` `(0855972)`

Testcase:

```java
public class SomeTest {
  @Test
  public void testThis() {
    RxJavaPlugins.getInstance().registerSchedulersHook(new RxJavaSchedulersHook() {
      @Override
      public Scheduler getComputationScheduler() {
        return Schedulers.immediate();
      }
    });

    Observable.just("test")
        .flatMap(new Func1<String, Observable<Boolean>>() {
          @Override
          public Observable<Boolean> call(String s) {
            return Observable.just(true);
          }
        })
        .subscribe(new Action1<Object>() {
          @Override
          public void call(Object o) {
            System.out.println("Hallo");
          }
        });
    
    System.out.println("Done");
  }
}
```

**Comment by akarnokd** [comment]
> I'm not sure if it's good practice to reference Schedulers from the RxJavaSchedulersHook subclass.
Yes, it is prone to circular class initialization problems.

In this case, the management loop for handling the internal buffers runs periodically on the computation scheduler but ```immediate()``` sleeps when a task is scheduled with delay. Due to the periodicity, the periodic task bogs down the scheduler and the main thread because the management class was initialized on this thread.

In my experience, there is no realistic use for an immediate scheduler because you can use either ```toBlocking``` to make things synchronous again or use the ```Schedulers.test()``` where you can advance 'time' at your leisure.

**Comment by hannesstruss** [comment]
True, thanks for the clarification! Closing this, and might think about proposing a docs update later.
