### ISSUE TITLE
ObserveOn: Unsubscribe of RecursiveScheduler

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3002]
Need to explore the unsubscribe of `recursiveScheduler`: https://github.com/ReactiveX/RxJava/blob/34dce48b4d591a2c574839b4527cbc30cb69e5a2/src/main/java/rx/internal/operators/OperatorObserveOn.java#L122

It seems to wrap with `child.add(scheduledUnsubscribe)` and then defeat that with `child.add(recursiveScheduler)`.

**Comment by akarnokd** [comment]
Yes, looks odd. I can't really remember why the unsubscription of the worker had to be scheduled. Maybe it had something to do with pitfall no. 2: unsubscribing the downstream: something around subscribe and ```SafeSubscriber``` doing this and cutting off the last few events from the wrapped ```Subscriber```.

**Comment by davidmoten** [comment]
Might be another problem here that the call to `child.setProducer` is made before adding all the subscriptions. I might test with #2997.

**Comment by benjchristensen** [comment]
> why the unsubscription of the worker had to be scheduled

Was it was because we could end up not emitting an `onError` that was scheduled but then dropped because the `worker` got unsubscribed?

**Comment by davidmoten** [comment]
I think @akarnokd is right, that `SafeSubscriber` reports `onCompleted` to its wrapped subscriber then unsubscribes which if `child.add(recursiveScheduler)` is present can cut short the schedule in `OperatorObserveOn` so that it doesn't emit its stuff. 

Re `onError` getting dropped this is still a possiblity but still consistent with the Observable contract (?). All the scheduled polls of the queue do check for error first so that once a scheduled task is run the error can shortcut the queue. Perhaps we can do something to aid this scenario without stuffing up the `onComplete` case.

**Comment by davidmoten** [comment]
I've probably got my last comment backwards. I was thinking that SafeSubscriber was upstream of observeOn but should be downstream so wouldn't have the effect I stated.

**Comment by akarnokd** [comment]
```SafeSubscriber``` came into play earlier when the operators used ```subscribe()``` to attach to each other instead of ```unsafeSubscribe()```.

**Comment by akarnokd** [comment]
Closing via #3682.
