### ISSUE TITLE
Variants of first, single etc. which return Single

### ISSUE THREAD

**Issue by tilal6991** [ReactiveX/RxJava#3038]
Now that we have the concept of a "Single", I think it would make sense that any operator which returns an observable which is guaranteed to return exactly one item or fail would be a Single. Examples would be operators like single, first, toList, takeFirst, takeLast etc.

I understand that to maintain source and binary compatibility, the existing definitions of these would need to be unchanged so would it be possible to create some sort of conversion mechanism to turn an observable into a Single?

If this would be acceptable I would be happy to try my hand in writing such a conversion mechanism depending on how complex it would have to be. I have been using Rx for a while now but as of yet have not actually written something which interacts with low level Rx stuff (e.g. a custom operator)

Thanks!

**Comment by benjchristensen** [comment]
Yes we will want something to convert, such as `Single.from(Observable o)` or `Observable.toSingle()`.

The `toSingle()` method should behave similarly to `single()` except return a `Single`. 

Awkward, but all we can do during 1.x.

It would be great if you want to contribute this and start the design discussion. Note that public APIs contributions can often go through a lot of back and forth as we discuss them since we are stuck with them forever once we let them in.
