### ISSUE TITLE
Deadlock in toBlocking().single()

### ISSUE THREAD

**Issue by Wendly** [ReactiveX/RxJava#3054]
It is sample code.
If there is no deadlock, it prints 0 to 999. But it doesn't. Some number is missing.

```java
for (int x = 0; x < 1000; x++) {
    Observable.merge(Observable.just(x).subscribeOn(Schedulers.io()),
            Observable.just(x).subscribeOn(Schedulers.io()))
            .toList()
            .map(i -> {
        return Observable.from(i).subscribeOn(Schedulers.io()).toList().toBlocking().single();
    }).subscribeOn(Schedulers.io()).subscribe(System.out::println);
}
```

I am tracing this issue for a while. I found the root cause finally. When completeInner is happen in merge, the inner subscriber will be unsubscribed and the worker of the inner subscriber is unsubscribed and released. The last inner subscriber will call the onCompleted of toList. Then, toList will be executed in the released worker.

If you call toBlocking() after toList. The released worker will be blcoked. Waiting for the next work is done. But sometimes the released worker will be get again and the next work is pedding. This is a deadlock.

I have a workaround right now. Add a observeOn(Schedulers.io()) after merge().toList(). But I have no idea how to fix it. So I create this issue.

**Comment by akarnokd** [comment]
This is a same-pool deadlock situation. The worker of one of the async `just` gets put back into pool but the same thread will emit the `onCompleted()` and trigger the execution of the `map()` which starts a blocking call and receives the same IO worker it is currently executing on and schedules the `from()` behind itself, blocks and thus deadlocks due to itself.

If you use `computation()` or `newThread()` in the inner `subscribeOn`, there is no deadlock. Generally though, blocking and non-blocking streaming doesn't mix well and you should avoid using `toBlocking()` inside a sequence (as an exit point it is fine). Use either `flatMap` or `concatMap` to keep the stream non-blocking.

Generally, I'm not sure if such case can be fixed: merge would need to not unsubscribe its very last inner, but there could be pending scalar emissions and the emission might be eventually triggered by a request from another thread. Tracking the number of `ScheduledAction`s doesn't work either because even if a wip counter is maintained, a never-run action won't decrement its value and may never reach the 0 = release thread state.
