### ISSUE TITLE
Prevent Duplicate onStart Without Wrapping

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3075]
Worth exploring if it is possible to prevent duplicate `onStart` without wrapping `Subscriber`. It may not be worth the effort for the small benefit, but it seems wrong we need to wrap just to avoid that.

The duplication comes via `lift` here: https://github.com/ReactiveX/RxJava/blob/bd8fb30737bd7937265cedfc1b69974c8621f62e/src/main/java/rx/Observable.java#L144

Examples of wrapping were discussed originally here: https://github.com/ReactiveX/RxJava/pull/3065#discussion_r34587075

**Comment by akarnokd** [comment]
One possible solution is that only `subscribe()` calls `onStart` automatically, but neither `unsafeSubscribe` nor `lift` does it and operators that 'repurpose' their incoming `Subscriber` have to decide whether it is safe to call `onStart` or not. I think RxJava 2.0 with the Reactive-Streams API can really resolve this issue for good.

**Comment by akarnokd** [comment]
A possible technical solution is to make sources (`range`, `from`, `Subject`) call `onStart` manually instead of the `Observable.subscribe` doing it but then all operators' parent `Subscriber` has to be updated to call `onStart` on its child subscriber. The problem is, that's a protocol change and existing custom operators outside RxJava won't know to do it and require updates as well.

I don't think this can be solved with 1.x architecture without drastically affecting everything.
