### ISSUE TITLE
Accepting Collection<Observable<T>> as argument in Observable.concat or Observable.amb ...

### ISSUE THREAD

**Issue by jeremieSimon** [ReactiveX/RxJava#3087]
This is not really an issue but a comment. 
I don't understand why your Observable.concat, Observable.amb or Observable.combineLatest don't take a Collection of Observable<T> as argument. Maybe something like concatAll would be great. 

That would be practical. I know you can do the trick without, but I don't see any obvious reasons why not providing the option in the first place.

**Comment by akarnokd** [comment]
- There is an `amb(Iterable)` overload which is more broad and should suffice.
  - I don't see any reason for `combineLatest` to have at least `Collection`, but that would be an incompatible API change by now.
  - There was a `concat(Iterable)` proposed a long time ago but was rejected because of API surface concerns (too many overloads).

**Comment by akarnokd** [comment]
I've looked at `combineLatest` and the reason it limits the the number of concurrent sources due to the limits of RxRingBuffer: the buffer size is predetermined and the downstream request have to be divided among sources. That means each source has to be requested 1 element at least.

I'd also let you know that 2.x doesn't have this limitation and the other operators have extra overloads you were looking for.

I don't know if or when this feature-request for 1.x gets accepted.

**Comment by akarnokd** [comment]
Both `amb` and `combineLatest` now have an overload with `Iterable`. If you wish, you can post a PR for `concat()`.
