### ISSUE TITLE
Backpressure issue with subscribeOn followed by observeOn

### ISSUE THREAD

**Issue by neerajrj** [ReactiveX/RxJava#3115]
Hello,

When using subscribeOn followed by observeOn only 128 (or default rxBuffer size) items get delivered because the subscribeOn operator does not transmit the subsequent request for 128  items.
If the lines 26 or 27 are commented out the code works fine.

https://gist.github.com/neerajrj/a98d75d1e9adf6608822

Am I doing something wrong or is there a bug?

Thanks

**Comment by davidmoten** [comment]
I think the problem is that  in `.subscribeOn()` subscription to your custom Observable and requests are all scheduled on the same worker thread. This means that the first request will be registered but further requests have to wait for the `for(int i=0; i<10000; i++) {` loop to finish so they don't arrive. 

Have a look at `OnSubscribeRange` for how to safely do something like this or better still build your Observable source using `AbstractOnSubscribe` which will handle backpressure for you.

**Comment by akarnokd** [comment]
I can't run the code right now but what stands out to me is that you sleep very little at the end and the program quits before it has a chance to deliver more values.

**Comment by neerajrj** [comment]
Thanks @davidmoten switching to using AbstractOnSubscribe seems to work. I noticed that AbstractOnSubscribe was marked as experimental, is it production ready now?

**Comment by davidmoten** [comment]
It's been in the codebase a while now with decent testing and I certainly use it for many things without problem. So my personal call on that would be yes. I suppose the `@Experimental` annotation is more to indicate that the API may change (or disappear) rather than indicating that the implementation is of concern.
