### ISSUE TITLE
OnSubscribeCombineLatest MultiSourceProducer request method

### ISSUE THREAD

**Issue by wrightm** [ReactiveX/RxJava#3146]
Why is the AtomicBolean started get and compareAndSet methods both called in the if statement on line 114 of the OnSubscribeCombineLatest class?

if (!started.get() && started.compareAndSet(false, true)) 

Is compareAndSet alone not good enough?

**Comment by akarnokd** [comment]
It is much faster that way because after the first call, all subsequent calls would fail the CAS and it costs 15-45 cycles whereas `get()` is likely to  cost 3-10 cycles only. Since `request` is called quite frequently, the optimization helps greatly in reducing the overhead. See the `AtomicPerf` benchmark that measures this effect. 

However, if said check is likely to get executed once, the extra get actually makes it slightly slower (something to do with how CPUs behave when they read-then-write the same memory location). Therefore, we don't call `get()` in, for example, Subscription implementations.

**Comment by wrightm** [comment]
Thank you for your clear explanation. 

So when we expect get() to return true proportionally more often than false and request to be executed a reasonable number of times we can use this "pattern" to potentially improve performance. 

I will run the benchmark to see the effects.
