### ISSUE TITLE
Lock-free approach in RxJava 2.0 (and 1.x retrospect)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#3153]
I've been fiddling with the reactive-streams API and built a few operators such as `flatMap` fully lock free and compared it against the last two releases of RxJava:

![image](https://cloud.githubusercontent.com/assets/1269832/9262943/48189b26-4219-11e5-9219-8e3c1c606359.png)

The algorithms are practically identical, but the rs version uses atomics for everything. This involves the queue-drain approach and copy-on-write arrays for tracking the inner subscribers. This is true for the range operator used in the perf.

Generally, atomics may impose more overhead because `synchronized` blocks can be elided by the JIT and this is apparent in the warmup when the througput doubles or triples.

How could the rsi implementation be faster?

  - No SafeSubscriber wrapper (and no plugin backdoors) -> less allocation per loop.
  - RxJava's merge tracks the subscribers in a `HashMap` and in an synchronized copy-on-write array, this double tracking might be unnecessary -> likely the cause;
  - The rsi `flatMap` is implemented directly whereas RxJava's flatMap is merge(map()) except the scalar-optimizations on both. Could be the reason why RxJava runs half the throughput the moment the mapped Observable is a 2 element range.
  - It is more expensive to startup an RxJava subscriber: call to `onStart`, then call to `setProducer()` and call to `request()` which go through a synchronized block of logic that resembles the `ProducerArbiter` -> strangely, times=1 indicates that even with this overhead, a backpressure-ignoring single call to just is faster by 10%.

Here is another comparison with `concatMap`:

![image](https://cloud.githubusercontent.com/assets/1269832/9263513/06c197c2-421e-11e5-8018-56b7601ccfeb.png)

RxJava with unsafeSubscribe() is slightly faster (~5%) than the lock-free rsi implementation for times=1000. times = 1 favors the direct implementation instead of a concat(map()).

**Comment by davidmoten** [comment]
very interesting, thanks.

**Comment by benjchristensen** [comment]
Thanks for posting this. Questions and comments:

> No SafeSubscriber wrapper (and no plugin backdoors) -> less allocation per loop.

This makes sense. The SafeSubscriber stuff is definitely something I'm interested in seeing how we can improve or eliminate in 2.x while maintaining the functionality it provides (which will still be needed).

> RxJava's merge tracks the subscribers in a HashMap and in an synchronized copy-on-write array, this double tracking might be unnecessary -> likely the cause;

This sounds like something we could apply to the current RxJava `merge` and see how it improves things.

> whereas RxJava's flatMap is merge(map()) except the scalar-optimizations on both

I have a harder time seeing how this one benefits performance. The JVM is incredibly good at these types of optimization. See this very old test (no longer in our codebase): https://github.com/ReactiveX/RxJava/blob/5ada2fcc1d7613ff93619e5dbef4ab8f5beb9142/rxjava-core/src/perf/java/rx/archive/performance/TestChainPerformance.java  It tested very deep function composition versus iterating a list of functions. Composition was actually faster than iterating:

```
Iterative => Sum: 202017114 Time: 164.578715ms
Composed => Sum: 202017114 Time: 140.41171400000002ms
-------------------------------
Iterative => Sum: 202017114 Time: 166.25904699999998ms
Composed => Sum: 202017114 Time: 146.133141ms
-------------------------------
Iterative => Sum: 202017114 Time: 157.40955499999998ms
Composed => Sum: 202017114 Time: 136.02565299999998ms
```

Of course this is not the same as fusing map+merge, but that 1 function composition seems negligible due to how the JVM works. I'd like to see JMH evidence with composition and fusion, where everything else is the same.

> It is more expensive to startup an RxJava subscriber

Is this due to the design because we bolted it into RxJava rather than designed from the start like ReactiveStreams? Or is it just our implementation?

-----------

I really look forward to starting on 2.x. Within about a month I think I'll be ready to spend time on it as I want it for new work I'm doing at Netflix where I want to use the Reactive Streams APIs without bridging back and forth between them.

**Comment by akarnokd** [comment]
> This sounds like something we could apply to the current RxJava merge and see how it improves things.

I think I can do better than that with a custom spsc structure that can use a two-array approach in bounded and a sequence of arrays in unbounded mode.

> JVM

I think the current JVM isn't smart enough to eliminate allocation involved in the subscription chain: upstream - map - merge - downstream. This affects short lived streams that get resubscribed often.

**Comment by akarnokd** [comment]
> I really look forward to starting on 2.x.

Plain porting shouldn't be that hard, although there are tricky cases. Going lock-free is challenging because performance requires custom (new) algorithms.

I suggest starting an empty branch and start porting the operators without any tests. Once done, tests can be added one by one. This way, compilation errors of the old tests don't demotivate us.

Plus, there is also the matter of who (else) is going to do it and who (else) has the skill to review the different style of operators?

**Comment by benjchristensen** [comment]
The approach I've been intending to take for 2.x is to start a completely clean branch, make it depend on a shaded version of RxJava 1.x so we can bridge to most operators until we finish the migration, and focus on getting the public APIs right first, and key functionality of map/flatMap/observeOn/Schedulers/subscribe working.

Let's pick up that conversation on the 2.x issues though ... this one is very focused on merge/flatMap.

**Comment by akarnokd** [comment]
I went with lock-free for most of the operators but still using synchronized in places where complex state management happens and CAS would be memory wasting.
