### ISSUE TITLE
Different behaviour of replay between 1.0.13 and 1.0.14

### ISSUE THREAD

**Issue by rayshih** [ReactiveX/RxJava#3219]
I am not sure my implementation is good. But I notice that given the following code (in scala):

``` scala
val password = BehaviorSubject[String]("")
val passwordIsValid = (false +: password.map(s => s.length >= 8)).
  doOnSubscribe(println("on subscribe")).
  doOnNext(v => println(s"do on next => $v")).
  replay(1)

passwordIsValid.connect

password.onNext("1")
password.onNext("12")
password.onNext("12345678")

passwordIsValid.subscribe(v => println(s"another password => $v"))
```

the output by RxJava 1.0.13 is:

```
on subscribe
do on next => false
do on next => false
do on next => false
do on next => false
do on next => true
another password => true
```

which is what I want.

however the output by RxJava 1.0.14 is different.

```
on subscribe
do on next => false
another password => false
do on next => true
another password => true
```

which doesn't make sense to me.

**Comment by akarnokd** [comment]
Could you post the example in plain Java?

**Comment by rayshih** [comment]
The following is the equivalent java code

``` java
BehaviorSubject<String> password = BehaviorSubject.create("");

ConnectableObservable<Boolean> passwordIsValid = password.map(new Func1<String, Boolean>() {
    @Override
    public Boolean call(String s) {
        return s.length() >= 8;
    }
}).startWith(false).
doOnSubscribe(new Action0() {
    @Override
    public void call() {
        Log.d("RxBug", "on subscribe");
    }
}).
doOnNext(new Action1<Boolean>() {
    @Override
    public void call(Boolean v) {
        Log.d("RxBug", "do on next => " + v);
    }
}).replay(1);

passwordIsValid.connect();

password.onNext("1");
password.onNext("12");
password.onNext("12345678");
passwordIsValid.subscribe(new Action1<Boolean>() {
    @Override
    public void call(Boolean v) {
        Log.d("RxBug", "another password => " + v);
    }
});
```

**Comment by akarnokd** [comment]
Thanks. Without `startWith`, this variant gives a reasonable output:

```java
        BehaviorSubject<String> password = BehaviorSubject.create("");
        
        ConnectableObservable<String> valid = password
                .map(s -> s + ": " + (s.length() >= 8))
                .doOnSubscribe(() -> System.out.println("onSubscribe"))
                .doOnNext(v -> System.out.println("onNext -> " + v))
                .replay(1)
                ;
        
        valid.connect();
        
        password.onNext("1");
        password.onNext("12");
        password.onNext("12345678");
        
        valid.forEach(System.out::println);
```

```
onSubscribe
onNext -> : false
onNext -> 1: false
onNext -> 12: false
onNext -> 12345678: true
12345678: true
```

I'll check what's different with `startWith`.

**Comment by rayshih** [comment]
yup, I have checked that before. It behaves correctly without `startWith`

**Comment by akarnokd** [comment]
`replay()` in 1.0.14 supports downstream backpressure and expects upstream backpressure. This required request coordination among child subscribers. 

If there are no child subscribers to begin with (at `connect()` for example), replay doesn't request anything. Without request, the concat in startWith won't subscribe to just(false). Since false isn't observed, `concat` won't continue with the `BehaviorSubject` that has 0 subscribers at the time, dropping your `1` and `12` values but holding onto `12345678`. When you do subscribe to the `ConnectableObservable`, `just(false)` and the latest value of the `BehaviorSubject` is received.

Without `startWith`, it works as `BehaviorSubject` disregards backpressure and pushes its values down to `replay()` that dutifully buffers them as long as it can.

In contrast, publish() slowly consumes its source if there are no child subscribers to it. Otherwise, the behavior you are expecting wasn't codified in our unit tests (therefore the updated replay() operator shipped). I have to think about if this is actually achievable or not. Until then, you can get back the old behavior:

```java
   // ...

   valid.subscribe();
   valid.connect();

   password.onNext("1");
   // ...
```

This will consume the upstream whether there are other subscribers or not.

**Comment by rayshih** [comment]
Thanks.
