### ISSUE TITLE
2.x: Observable.generate confusing with Subscriber

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#3337]
It is confusing that the `Observable.generate` methods pass in a `Subscriber` that has an `onSubscribe` method on them. When using `generate` I should never have to or be able to call `onSubscribe` and involve myself in the flow control.

**Comment by akarnokd** [comment]
I tried to avoid adding to many new interfaces. We can change it to something like `GenerateOutput`, `ChildObserver`, `ClientObserver` or `OutputObserver`.

**Comment by JakeWharton** [comment]
We should probably avoid using the `Observer` term since this interface can be re-used for both `Observable` and `Flowable`'s `generate` methods and `Observer` is only associated with non-backpressure types.

It could be called `Emitter` and both `FlowableEmitter` and `ObservableEmitter` could extend from it.

**Comment by akarnokd** [comment]
Closing via #4410.
