### ISSUE TITLE
propagating request when using flatMap

### ISSUE THREAD

**Issue by larousso** [ReactiveX/RxJava#3367]
Hi, 

I ve this piece of code : 

```
Observable
	.from(IntStream.range(1, 20).boxed().collect(Collectors.toList()))
	.map(i -> {
                System.out.println("Step :"+i);
                return i;
            })
	.flatMap(elt ->
                            Observable
                                    .just(elt).observeOn(Schedulers.io())
                                    .map(String::valueOf)

            )
	.subscribe(new Subscriber<String>() {

                @Override
                public void onStart() {
                    request(1);
                }

                @Override
                public void onCompleted() {}

                @Override
                public void onError(Throwable throwable) {}

                @Override
                public void onNext(String s) {
                    System.out.println("Next : " + s);
                }
            });
```

I expect this on the logs : 

Step : 1
Next : 1

But Instead I've this : 

Step :1
Step :2
Next : 1
Step :3
Step :4
Step :5
Step :6
Step :7
...

Why does the request is not propagating to the source when I use flatMap ?

Thanks for your help!

**Comment by davidmoten** [comment]
You've only requested one so that is all you get arriving to the subscriber. The other log lines are because `flatMap` requests 128 (or 16 on Android) regardless of how many were requested of it and then buffers. When you request more `flatMap` will empty its buffer.

If you put a `request(1)` just after  `System.out.println("Next : " + s);` then your stream will report all to the subscriber.

**Comment by larousso** [comment]
Ok thanks. 
I didn't know that flatMap was buffering. It was the missing information :)

**Comment by akarnokd** [comment]
@davidmoten :+1:
