### ISSUE TITLE
Single threaded scheduler for disk IO?

### ISSUE THREAD

**Issue by pyricau** [ReactiveX/RxJava#3373]
When building client UI apps (say android), it's generally a good idea to use a single thread for all disk related IO. For instance, say you save a checkbox state to the disk every time it's clicked. If using Schedulers.io(), the second click might be saved before the first click.

Basically, task ordering is important when you have an app with a main thread that processes events from a queue in order.

This can easily be achieved with `Schedulers.from(Executors.newSingleThreadExecutor())`.

I've seen a lot of introductions to Rx + Android recommend using `Schedulers.io()` for all IO, including disk, and I'm worried this leads to many hard to grasp bugs.

Should there be a `Schedulers.disk()` or `Schedulers.serialIo()` ? Maybe that should belong in RxAndroid. Or maybe nowhere. Thoughts?

**Comment by artem-zinnatullin** [comment]
>When building client UI apps (say android), it's generally a good idea to use a single thread for all disk related IO. For instance, say you save a checkbox state to the disk every time it's clicked. If using Schedulers.io(), the second click might be saved before the first click.

This can be applied to the network io too: say you want to send a state to the backend every time checkbox is clicked, second click might be send before the first click.

>Should there be a Schedulers.disk() or Schedulers.serialIo() ? Maybe that should belong in RxAndroid. Or maybe nowhere. Thoughts?

I don't think that single-thread scheduler inside the `RxJava` or `RxAndroid` is a good thing because a lot of libraries and user code will be able to use it, and this scheduler will become bottleneck of the app very fast.

I'd leave it up to the user code, it's not a big deal to create such scheduler and provide static getter for it, so with static import it can be used pretty nicely:

```java
saveToTheDisk(data)
  .subscribeOn(serialIo()) // Static import hides class
  .observeOn(mainThread())
  .subscribe(result -> {}, error -> {});
```

>I've seen a lot of introductions to Rx + Android recommend using Schedulers.io() for all IO, including disk, and I'm worried this leads to many hard to grasp bugs.

I think, the best you can do — write a blog post about this problem and suggest solutions!

**Comment by stanmots** [comment]
> Should there be a Schedulers.disk() or Schedulers.serialIo()

I was also thinking about this. And then I found that such scheduler is already implemented:
[Schedulers.single()](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/schedulers/Schedulers.java#L286)
