### ISSUE TITLE
okhttp callback function onFailure donot catch OnErrorNotImplementedException

### ISSUE THREAD

**Issue by hamberluo** [ReactiveX/RxJava#3432]
okhttp 2.4.0

```
        @Override
        public void onFailure(Request request, IOException e) {
            StringBuilder builder = new StringBuilder();
            builder.append("url: ").append(request.urlString());
            builder.append("\n");
            builder.append("error: ").append(e.getMessage());
            Logger.e(builder.toString());

            if (mSubscriber.isUnsubscribed()) {
                return;
            }

            try {
                mSubscriber.onError(null);
            } catch (OnErrorNotImplementedException ex) {
                // donot reach here but crash
            }
        }
```

**Comment by artem-zinnatullin** [comment]
The problem is that you're passing `null` as an error. As a result you get `CompositeException` with pretty long stacktrace caused by `NullPointerException`  inside of `OnErrorNotImplementedException` constructor (what a lol)!

1. Don't pass `null` as an error and your code will start working.
2. Swallowing exceptions is not a very great idea, consider adding `onError` implementation to the subscribers.

**Comment by hamberluo** [comment]
when i add `onError` implementation and passing `nonnull`, the problem still exists.

**Comment by akarnokd** [comment]
@hamberluo What is exactly your problem?
