### ISSUE TITLE
Specific and general back pressure questions.

### ISSUE THREAD

**Issue by epatey** [ReactiveX/RxJava#3481]
### Specific
The documentation for `OperatorObserveOn` states that it uses an unbounded buffer:
> [Delivers events on the specified {@code Scheduler} asynchronously **via an unbounded buffer**.](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorObserveOn.java#L37)

Yet in practice it seems to apply reactive pull back pressure - failing very quickly with a `MissingBackpressureException` with the following code.

```java
Observable
    .interval(1, TimeUnit.MILLISECONDS)
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe();
```

Adding back pressure support avoids the issue.

```java
Observable
    .interval(1, TimeUnit.MILLISECONDS)
    .onBackpressureLatest()
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe();
```

Can somebody confirm that this is a documentation error?

### General
I'm also struggling to come up with a coherent set of principles to avoid `MissingBackpressureException`'s short of sprinkling `.onBackpressureBuffer()`'s all around my code.

My first approach was to make sure that any potentially bursty observables I expose are protected by `.onBackpressureBuffer()`. However, this only works some of the time since it depends on the downstream operator composition. Some operators appear to break the chain.

Ideally, I'd like to avoid inducing back pressure altogether. I promise not to `.zip(noisyObservable, Observable.never())`. Is there a way to do that? If not, what sort of principles have others used to avoid `MissingBackpressureException`'s?

**Comment by akarnokd** [comment]
> Can somebody confirm that this is a documentation error?

Yes, this is a documentation error. ˙observeOn` has a bounded queue and will signal `MissingBackpressureException`.

> Ideally, I'd like to avoid inducing back pressure altogether.

Thinking about backpressure is mandatory with 1.x. You have to decide on a case-by-case basis what to do with hot, timed or event-controlled sources. Sometimes it is okay to buffer, sometimes you can drop values.

2.x gives you more options to deal with the situation. You can go full non-backpressure with the `NbpObservable`s or you can adjust the buffers of operators to any size to accomodate bursts yet stay backpressured as long as possible.

**Comment by epatey** [comment]
@akarnokd thanks so much for the quick response.

So as a followup, can you confirm that, depending on the observable composition, a single `.onBackpressureXXX()` immediately downstream of the noisy producer _may_ not be sufficient? In other words, _could_ downstream operators break the back pressure chain? For example:

```java
noisyObservable()
    .onBackPressureXXX()
    .someOperator()
    .anotherOperator()
    .observeOn(x)
    .subscribe();
```
Is it possible that some or another operator break the back pressure chain such that `.observeOn` will still throw an mbpe?

**Comment by akarnokd** [comment]
As a general rule of thumb, you should put those just before the sensitive operators such as `observeOn` and `zip`. Can you say what operators you think would cause you trouble?

**Comment by epatey** [comment]
I understand your rule of thumb, and it make sense. My thinking was kind of the opposite. I'd like consumers of my observables to not have to worry about back pressure. If I expose an observable that is noisy, it's my job to make sure that it supports back pressure - as an implementation detail. Make it the producer's problem rather than the consumer's. 

Imagine that I have one noisy observable that is consumed 50 different places. It seemed cleaner to ensure back pressure support in my observable rather than in the 50 call sites. That was a principle that I was trying to apply.

> Can you say what operators you think would cause you trouble?

It's likely the case that some of our own custom `Operator`'s are at fault in terms of not properly implementing back pressure (and therefore breaking the chain?).

I've read that _time_ oriented operators such as `.debounce()` are know to not support back pressure. Does "not supporting back pressure" means that it will break the chain such that `request(n)` will not make it to the upstream observable? If so, is there a definitive list of operators what will break the chain?

**Comment by akarnokd** [comment]
> If I expose an observable that is noisy, it's my job to make sure that it supports back pressure - as an implementation detail. Make it the producer's problem rather than the consumer's.

The problem with this view that you are making assumptions about your consumers upfront. What if your consumer actually is able to consume whatever you throw at it? If you are building an application, you can make such assumptions but if you are building a generic API, such decisions takes away the freedom from the consumer. 

The analogous problem is with when to have default `Scheduler`s. As far as I can tell, Retrofit moved away from forcing a scheduler on the returned `Observable`s to be plain synchronous and have the caller apply any async-inducing operators at will.

> It's likely the case that some of our own custom Operator's are at fault in terms of not properly implementing back pressure (and therefore breaking the chain?).

Writing operators ranges from fairly easy to outright brain melting. I have a [blog series about operator pitfalls](http://akarnokd.blogspot.hu/2015/05/pitfalls-of-operator-implementations.html) you may want to read.

> I've read that time oriented operators such as .debounce() are know to not support back pressure.

Yes, debounce emits as fast as its timer allows, which may be still too fast.

> Does "not supporting back pressure" means that it will break the chain such that request(n)

It means such operators request independently from the upstream and practically ignore requests from downstream and emit values without considering what the downstream requested.

> If so, is there a definitive list of operators what will break the chain?

There is no such list for 1.x but you can dynamically discover it in 2.x because I added `BackpressureSupport` annotations to operators; the problematic cases are the ones with the `ERROR` value of [BackpressureKind](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/annotations/BackpressureKind.java).

**Comment by epatey** [comment]
Thanks again @akarnokd. I really appreciate your insights.

:+1: to the `BackpressureSupport` annotation. Great idea!
