### ISSUE TITLE
Polling with a "cold" source observable?

### ISSUE THREAD

**Issue by cxzhang2** [ReactiveX/RxJava#3482]
Scenario: 
I'm polling an endpoint that returns the status of my batch request.  If the batch is finished, I want to stop polling and do additional work.

Approach:
I'm using @benjchristensen's approach to polling referenced in #448. I am filtering the source observable to only respond to a STATUS = FINISHED emission.

Problem:
The source observable continues to to poll after the batch is complete.

Example output:
"polling"
"polling"
"polling"
"batch is done" <--I  want to stop polling here
"polling"
"polling"

Code:

```java
Observable
        .create((Subscriber<? super Observable<BatchStatus>> subscriber) ->
                Schedulers.newThread().createWorker().schedulePeriodically(() -> {
                    subscriber.onNext(mWebService.checkBatchStatus(id));
                    Log.d(TAG, "polling");
                }, 1000, 10000, TimeUnit.MILLISECONDS))
        .flatMap(r -> r)
        .filter(r -> r.getStatus() == BatchStatus.Status.FINISHED)
        .observeOn(AndroidSchedulers.mainThread())
        .take(1)
        .subscribe(r -> Log.d(TAG, "batch is done");
```
I don't think the subscription is still active, to test this I stored the subscription and called unsubscribe() explicitly from onNext().  How do I stop the observer from emitting more polling requests?  Any help would be appreciated.

Thanks!

Edit:
Found the fix, I had to maintain a reference to the subscription returned by schedulePeriodically() and unsubscribe that subscription in onNext().

My question still stands as to why I have to do this explicitly even though the Observable that is using the scheduler is no longer subscribed to.

**Comment by DmitryGlotov** [comment]
Hi, try organize your subscription in this way

```java      
  Observable.interval(1000, 10000, TimeUnit.MILLISECONDS, Schedulers.newThread())
                .flatMap(v -> Observable.just(Math.random() > 0.5 ? "in progress" : "finished") /*mWebService.checkBatchStatus(id)*/)
                .filter(r -> r.equals("finished"))
                .take(1)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(r -> Log.d("TAG", "batch is done"));
```

I hope it will be helpful

**Comment by cxzhang2** [comment]
@DmitryGlotov 

Thank you for your response.  I believe there is a slight difference in our approaches in that schedulePeriodically() waits for the previous action to complete while interval() does not.

Regardless of the differences I am still curious as to why it is necessary to explicitly unsubscribe to the subscription generated by schedulePeriodically()

**Comment by DmitryGlotov** [comment]
@cxzhang2 

Hi, i think your implementation doesn't wait until request is finished. Check this simplified example:

```java
Observable.create(subscriber -> {
            Schedulers.newThread().createWorker().schedulePeriodically(() -> {
                subscriber.onNext(Observable.just("finish").subscribeOn(Schedulers.io()).delay(4000, TimeUnit.MILLISECONDS));
                Log.d("tag_example", "polling");
            }, 1000, 1000, TimeUnit.MILLISECONDS);
        })
                .flatMap(d -> (Observable<String>) d)
                .take(1)
                .subscribe(r -> Log.d("tag_example", "batch is done"));
```

Output

```
polling
polling
polling
polling
batch is done
polling
polling
polling
```

Maybe this link be useful for you:
http://stackoverflow.com/questions/30885461/rxjava-retrofit-long-polling

**Comment by cxzhang2** [comment]
@DmitryGlotov 

I was referring to how schedulePeriodically() waits until one action is done before scheduling the next, provided the action itself is synchronous.  I am fairly certain this is true.

The problem I have is that the Subscription returned by schedulePeriodically() is not unsubscribed even after onComplete() has been called by the Observable.  I am not experience enough in Rx to know whether or not this is a bug or intended feature.

**Comment by akarnokd** [comment]
> My question still stands as to why I have to do this explicitly even though the Observable that is using the scheduler is no longer subscribed to.

You have to manage your resources as `Observable` doesn't know about them. @DmitryGlotov 's `interval` example is the preferred way over using `schedulePeriodically` directly.

> Thank you for your response. I believe there is a slight difference in our approaches in that schedulePeriodically() waits for the previous action to complete while interval() does not.

`interval` uses `schedulePeriodically` internally so they should behave the same way. The only exception is that `interval` tracks the `Worker` created via `createWorker` and adds it to the child `Subscriber` so an unsubscription will cancel it. Your code didn't do it.

`schedulePeriodically` runs in sequence so it won't trigger until its previous run has finished. This also means that if the call takes longer than the period, the next invocation may come immediately.

> The problem I have is that the Subscription returned by schedulePeriodically() is not unsubscribed even after onComplete() has been called by the Observable.

Based on your example, since you just drop the returned `Subscription` nothing in the chain knows about it and thus can't call it for you. If you don't want to use `interval` instead, you should capture the `Worker` and register it with the `Subscriber`:

```
Worker w = Schedulers.newThread().createWorker();

subscriber.add(w);

w.schedulePeriodically(() -> s.onNext(1), 1, 10, TimeUnit.SECONDS);
```

The contract with the `Scheduler.Worker` is that when unsubscribed, all tasks scheduled by any means will be cancelled, therefore, you don't have to keep a reference to them individually. In addition, if a worker is created, it must be eventually unsubscribed because it may leak OS threads otherwise (especially with `Schedulers.io()`).

**Comment by cxzhang2** [comment]
@akarnokd 
Perfectly clear, thank you!
