### ISSUE TITLE
AttachSubscriptionOperator

### ISSUE THREAD

**Issue by Diolor** [ReactiveX/RxJava#3538]
Here is an example of an operator that attaches a `Subscription` to the operator's subscriber:

```
public class AttachSubscriptionOperator<T> implements Observable.Operator<T, T> {

	private final Subscription subscription;

	public AttachSubscriptionOperator(Subscription subscription) {
		this.subscription = subscription;
	}

	@Override
	public Subscriber<? super T> call(Subscriber<? super T> child) {
		child.add(subscription);
		return child;
	}

}
```

Does it make sense to create a PR with an `Observable#attach()` method? I personally find it useful but is it really or indicates bad code design (because the subscriptions are getting attached to subscribers, thus creating confusion)?

**Comment by akarnokd** [comment]
Why would you want to attach a Subscription to every Subscriber that comes along?

**Comment by Diolor** [comment]
I used it with a ConnectableObservable so there was just one Subscriber in that case.

**Comment by davidmoten** [comment]
The operator you describe already exists and is called `.doOnUnsubscribe`.

A quick note for you that the Operator as you've coded it has a bug in that the `onStart` method of `child` would be called twice.  For this reason the implementation of `doOnUnsubscribe` returns `Subscribers.wrap(child)` instead of `child`.

**Comment by Diolor** [comment]
thanks for all the info @davidmoten :+1:
