### ISSUE TITLE
OperatorTake/SafeSubscriber fail to propagate an exception

### ISSUE THREAD

**Issue by Alexander--** [ReactiveX/RxJava#3571]
Here is a rough version of my code:

```java
Object state = ...
Action1<Object> action = ...

Observable.timer(delayMs, TimeUnit.MILLISECONDS, SchedulerUtils.mainThread())
    .doOnUnsubscribe(() -> <unrelated code>)
    .first()
    .takeUntil(anotherObserbable)
    .filter(time -> <unrelated code>)
    .subscribe(ok -> action.call(state))
```

When `action.call` throws, the following seems to happen:

* SafeSubscriber notifies my RxJavaErrorHandler about the exception - a ClassCastException, to be precise. This is actually useless, because the handler is global and does not have a clue about that particular exception, and whether onError will be able to handle it or not. All of this is ok.
* The exception is further handled by SafeSubscriber by producing an OnErrorNotImplemented exception and throwing it. My RxJavaErrorHandler is not notified about that exception, which may or may not be ok.
* OperatorTake decides to silently swallow the exception, because it is. well, *completed*. Or, maybe, someone else does, I can't make heads or tails of RxJava logging at that point. Regardless, the exception never reaches Scheduler or any of my global exception handling routines.

I believe, that there is a single thing, that should be done there: make SafeSubscriber directly call current `Thread.UncaughtExceptionHandler` with OnErrorNotImplemented before attempting to throw it. "Unsafe" operators may be incapable of handling exceptions at that point, and the situation, when observable without onError throws, is a hopeless condition anyway.

**Comment by akarnokd** [comment]
Hi.

The problem with `onError` is that it can only safely travel downstream, but if it missed that opportunity (i.e., by happening after a terminal event or due to an unimplemented error handler) it can't go anywhere else but to the plugin error handler. 

You may think the uncaught exception handler is a viable option but its behavior is platform dependent: on desktop, it either gets swallowed or printed to the console; on Android, it will crash the entire application.

Propagating fatal exceptions also has its limits. At best, they can only go as far as the next asynchronous boundary at which point there is nowhere to go. 

The second problem I believe the misguide caused by the case where there is no async boundary (because you have a completely synchronous sequence) and your `subscribe` method will throw in the current thread, strenghtening the classical try-catch world view unfortunately.

This means you can't reliably get away from handling exceptions either via the `onErrorXXX` method or simply using the `subscribe(Action1<T>, Action1<Throwable>)` overload which will call the second action with the exception thrown from the first one properly.

**Comment by Alexander--** [comment]
Sorry, but this is not a question. This is a bug report. If you plan to argue in favor of silently swallowing exceptions, say so and close it. I can patch the library just fine.

> You may think the uncaught exception handler is a viable option but its behavior is platform dependent

As long as error handler is controlled by myself, it is fine. Unfortunately, OnErrorNotImplementedException does not reach any handlers.

> you can't reliably get away from handling exceptions either via the onErrorXXX method or simply using the subscribe

Bullshit. `onError` isn't supposed to throw, this is stated numerous times in RxJava documentation. This is exactly why another way to propagate the fatal exception has to be used. `Thread.UncaughtExceptionHandler` is the most sensible of such methods, used by every single error reporting framework out there. But I would be fine with applying a workaround if form RxJavaErrorHandler. Unfortunately that does not get called either.

**Comment by akarnokd** [comment]
Could you post a runnable JUnit test method that demonstrates the problem?

As for the workaround, you can use the two parameter subscribe:

```java
Observable.just(1)
        .subscribe(v -> { throw new RuntimeException(); },
                e -> Thread.currentThread()
                .getUncaughtExceptionHandler()
                .uncaughtException(Thread.currentThread(), e)
        );
```
