### ISSUE TITLE
A schedule operator that accepts Quartz-style input format

### ISSUE THREAD

**Issue by preslavrachev** [ReactiveX/RxJava#3604]
Not really a feature request here, but more of a nice-to-have. Similar to the `timer` and `interval`, it would be great if RxJava supported an operator for scheduling event emitting using Quartz/cron-style expressions. Quartz is the de-facto standard in the Java world, when it comes to defining complex scheduled routines. 

See this page for some examples showing the flexibility of the Quartz/cron expression style: http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger

**Comment by artem-zinnatullin** [comment]
Standard RxJava's `Scheduler`s are not intended to be used for scheduling jobs for, let's say hours or days/months because they use threads for that and it won't be effective. Of course, you can always write own `Scheduler` which will do that more efficiently, but until such scheduler is not part of RxJava's core there is no much sense to add support for Quartz-style format to the RxJava itself. Also, scheduling rx chains for a long time will keep such chains in memory for a very long time which is not great.

BTW, there is, at least, one implementation of `Scheduler` with Quartz under the hood https://github.com/svarcheg/rx-cron-scheduler.

Another approach, which seems much better to me, is to listen for Quartz's notifications and convert them to `Observable` emission and then react to them!

Just my two cents. I vote for closing this issue, nothing personal :)

**Comment by akarnokd** [comment]
This feature could live in an external library that can wrap a `Scheduler` instance and schedule tasks based on the pattern of your choosing.
