### ISSUE TITLE
GroupedObservable -> toBlocking() - hang forever

### ISSUE THREAD

**Issue by palaima** [ReactiveX/RxJava#3611]
Found an issue where `groupObservable.toBlocking()` hangs.

`rxjava:1.1.0`

```
Observable
            .just(1, 1, 2, 3, 4, 4, 5)
            .groupBy(new Func1<Integer, Boolean>() {
                @Override
                public Boolean call(Integer integer) {
                    return integer % 2 == 0;
                }
            }).subscribe(new Action1<GroupedObservable<Boolean, Integer>>() {
            @Override
            public void call(GroupedObservable<Boolean, Integer> grouped) {
                List<Integer> first = grouped.toList().toBlocking().first();
                Timber.d(first.size() + " (Even: " + grouped.getKey() + ")");
            }
        });
```

**Comment by akarnokd** [comment]
Hi. This is expected as the `toBlocking` gives access to blocking functions that may block the sequence. In this case, the problem is that `toList` expects a complete stream and won't emit until it receives an `onCompleted` event, Since you applied `toBlocking().first()`, that will block the current thread until it receives a single element which `toList` can't ever produce; the whole chain up to the producing `just` is blocked. The usual solution is to use `flatMap` and do some non-blocking processing with `GroupedObservable`:

```java
Observable.just(1, 1, 2, 3, 4, 4, 5)
.groupBy(v -> v % 2 == 0)
.flatMap(g -> g.toList().doOnNext(first ->
    Timber.d(first.size() + " (Even: " + g.getKey() + ")")).ignoreElements())
.subscribe(v -> { }, Throwable::printStackTrace);
```

**Comment by palaima** [comment]
Thanks for clarification!
