### ISSUE TITLE
Bottleneck on retryWhen

### ISSUE THREAD

**Issue by daschl** [ReactiveX/RxJava#3633]
In some recent performance analysis of couchbase Java SDK code I did some profiling and found that `retryWhen` causes some significant slowdown of async operations.

It looks like the main suspect is `OperatorZip#tick` which can be observed in this JFR screenshot:

<img width="1016" alt="screen shot 2016-01-22 at 14 18 38" src="https://cloud.githubusercontent.com/assets/29086/12511644/3ba5da7e-c113-11e5-9ed9-551550157092.png">

The code we execute looks like this:

```java
bucket
	.async()
	.upsert(StringDocument.create(id(integer), content()))
	.retryWhen(any().delay(Delay.fixed(100, TimeUnit.MICROSECONDS)).max(Integer.MAX_VALUE).build());
```

Note the builder syntax expands to something like:

```java
    @Override
    public Observable<?> call(Tuple2<Integer, Throwable> attemptError) {
        long errorNumber = attemptError.value1();
        Throwable error = attemptError.value2();

        if (errorNumber > maxAttempts) {
            return Observable.error(new CannotRetryException(messageForMaxAttempts(errorNumber - 1), error));
        } else if (stoppingErrorFilter != null && stoppingErrorFilter.call(error) == Boolean.TRUE) {
            return Observable.error(error);
        } else {
            long delay = retryDelay.calculate(errorNumber);
            TimeUnit unit = retryDelay.unit();
            if (this.optionalScheduler != null) {
                return Observable.timer(delay, unit, optionalScheduler);
            } else {
                return Observable.timer(delay, unit);
            }
        }
    }
```

Note that on a "lets go as fast as we can" where we do this over and over again with `repeat()` this reduces ops/s on the server by 10k ops/s (so its quite significant overall).

Any idea how to optimize/avoid the zip case, or is there something we can do in the retry builder that helps go down a fast path?

**Comment by akarnokd** [comment]
RetryWhen runs only if there is an exception which by itself is costly but shouldn't affect non-failing sources at all. The RetryWhen is quite convoluted in 1.x (unlike [Rsc's](https://github.com/reactor/reactive-streams-commons/blob/master/src/main/java/reactivestreams/commons/publisher/PublisherRetryWhen.java) clean implementation). In theory, `retryWhen` can be implemented with as little overhead as a plain increment per element so pass-through is very cheap. However, 1.x Repeat is implemented on top of the underlying `OnSubscribeRedo` operator which adds quite a large overhead, even for a simple thing as an infinite repeat.

Otherwise, RxRingBuffer uses `synchronized` and the two ends of it may clash with each other.

Could you post a (perf) test with your intended operator usages?

**Comment by daschl** [comment]
@akarnokd you mean a JMH benchmark that simulates the usage pattern we have?

**Comment by akarnokd** [comment]
A simple unit test would suffice.

**Comment by akarnokd** [comment]
Posted a benchmark PR: #3634. It doesn't seem to be that bad overhead-vise.

**Comment by akarnokd** [comment]
Here is another benchmark run with Rsc which is closer to the theoretically minimum overhead:

![image](https://cloud.githubusercontent.com/assets/1269832/12520580/b0fbb5aa-c145-11e5-97a3-e532a79e4e8e.png)

**Comment by akarnokd** [comment]
In PR #3635, I've benchmarked zip. It can go as low as 100kOps/s on my weak laptop.

**Comment by akarnokd** [comment]
The comparative benchmark with Rx 2.x:

![image](https://cloud.githubusercontent.com/assets/1269832/12524816/41253cf4-c160-11e5-9b85-bbe89b9d845a.png)

**Comment by daschl** [comment]
Thanks for the analysis, it looks like I need to dig into it deeper for proper benchmarking!

**Comment by akarnokd** [comment]
Great, let me know if you have more input.
