### ISSUE TITLE
Subject's get* methods deletion

### ISSUE THREAD

**Issue by Nexen23** [ReactiveX/RxJava#3646]
Why were, e.g. `Subject::getValue()` deleted? Are they have some Cons?
1.0.16 : [Sujbect.java in 1.0.16](https://github.com/ReactiveX/RxJava/blob/v1.0.16/src/main/java/rx/subjects/PublishSubject.java)
1.x : [Subject.java in 1.x](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/subjects/PublishSubject.java)
As I can see, they should be still in `Experimental mode` according to [Docs](http://reactivex.io/RxJava/javadoc/rx/subjects/PublishSubject.html)

For my current goal, I horrendously want to use this method.

**Comment by akarnokd** [comment]
Those methods have been moved into each `Subject` implementing classes and none of them are available commonly.

**Comment by Nexen23** [comment]
What does `non of them are available commonly` mean?

**Comment by akarnokd** [comment]
It means that `Subject.getValues()` and `PublishSubject.getValues()` doesn't exist but `ReplaySubject.getValues()` does.

**Comment by Nexen23** [comment]
Okey, but what about `getValue()` method? As I can see, it exists everywhere.

**Comment by artem-zinnatullin** [comment]
Well, no, for example `PublishSubject` doesn't have `getValue()` by design.

You always can store reference to the `Subject` precisely or check if generic `Subject` has such methods via `instanceOf` or reflection and use them when needed!

@neerajrj please mark issue as resolved if you found the solution. Anyway, those methods were weird part of common Subjects API and chances that they'll be restored are very low, I guess.
