### ISSUE TITLE
doOnEach marble diagram incorrect

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#3721]
Should show the completion event forwarded to the supplied `Action1` or `Observer`.

**Comment by DavidMGross** [comment]
If so, the javadocs also need to be rewritten to indicate that the
completion event is sent to the action or observer.

I notice also that the description of the parameter in the javadoc of
doOnEach(Observer) describes the observer as an Action rather than an
Observer.

On Thu, Feb 18, 2016 at 11:30 AM, Jake Wharton <notifications@github.com>
wrote:

> Should show the completion event forwarded to the supplied Action1 or
> Observer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/3721>.
>



-- 
David M. Gross
PLP Consulting

**Comment by DavidMGross** [comment]
Reopening because the javadocs still need correction.

Also: there's a new doOnEach.o.png marble diagram that's specific to the doOnEach(observer) operator and should replace the diagram in the javadocs for that operator.

**Comment by akarnokd** [comment]
See #4024 for my proposed text changes

**Comment by akarnokd** [comment]
Great! Closing via #4024.
