### ISSUE TITLE
observable.toBlocking().toFuture().get(timeout, timeUnit) does not timeout

### ISSUE THREAD

**Issue by prismec** [ReactiveX/RxJava#3735]
The use case is pretty simple. Am I getting something wrong or is this a bug ? 

```
def observable = Observable.from(new CompletableFuture()) // never completes
observable.toBlocking().toFuture().get(1, TimeUnit.SECONDS) // never completes either
```

This should throw a TimeoutException after a second but actually blocks forever.

**Comment by akarnokd** [comment]
Observing a Future blocks the current thread so when you call `get()` it blocks further up and never gets to the timeout part. This is why there is an overload of `from(Future, long, TimeUnit)` to timeout directly with a future. Now since RxJava is Java 8. It doesn't know about `CompletableFuture` so can't utilize its non-blocking continuation style API that would otherwise allow the `get()` to timeout.

You can apply `.subscribeOn(Schedulers.io())` to make that first blocking wait happen on a different thread so your main thead is free to wait for the get with timeout.

**Comment by prismec** [comment]
Thanks! 

It could be worth a consideration to support Java 8 Futures in RxJava.

**Comment by akarnokd** [comment]
Oh sorry, I wrote the wrong version number. As it seems, both RxJava 1 and 2 are set out to remain Java **6** compatible and thus we can't really support those newer APIs in the core library. Your best bet is to find some other library and conversions or write the necessary source operator yourself.
