### ISSUE TITLE
Is there any implementation of ReactiveProperty/ReactiveCollection for RxJava?

### ISSUE THREAD

**Issue by s0nerik** [ReactiveX/RxJava#3742]
I've been using Rx in C# for some time and got used to ReactiveProperty and ReactiveCollection types. They basically allow to subscribe to property or collection changes. It's pretty useful as I don't need to manually publish anything to some subject or use another methods of notifying others. It would have been great if we had those things for RxJava also. I've googled for some ready-to-use implementation but didn't find anything. If there's no ready-to-use implementation our there and it's achievable in Java, I'd like to put this as a feature-request.

**Comment by artem-zinnatullin** [comment]
`ReactiveProperty` looks equivalent to `BehaviorSubject` which holds last value and works as property with reactive nature even though it's a subject which you don't want to use.

Can you provide links to documentation for `ReactiveProperty` and `ReactiveCollection`, hadn't found them on msdn, do you use some 3rd-party library for that? [This one](https://github.com/runceel/ReactiveProperty) maybe?

 >it's achievable in Java

It's achievable but since Java does not have built-in support for properties it will look non-native.

Collection part really depends on what you want to receive as changes: new version of collection, added/updated/removed items, both of them, etc?

**Comment by s0nerik** [comment]
I've used [this](https://github.com/neuecc/UniRx#reactiveproperty-reactivecollection) implementation. And it acts like PublishSubject, actually. The thing I like the most about it is that I don't need to publish anything by myself, thus avoiding some boilerplate. Well, while writing this I already came up with the implementation for Java, and it's quite easy. Maybe I'll link the PR here some time later.

**Comment by artem-zinnatullin** [comment]
Don't see much boilerplate in case of using `BehaviorSubject` as reactive property:

```java
private final BehaviorSubject<Boolean> somethingEnabled = BehaviorSubject.create(false);

// Notice that you can expose it as Observable (readonly)
public Observable<Boolean> somethingEnabled() { 
  return somethingEnabled;
}

public void somethingEnabled(boolean enabled) {
  somethingEnabled.onNext(enabled); // that's it, it'll now hold new value and send it to observers.
}
```

>Maybe I'll link the PR here some time later.

Before making PR here I'd suggest to wait for feedback from core team of RxJava, probably they'll reject this feature request…

**Comment by s0nerik** [comment]
The thing here is that with BehaviorSubject I will need to subscribe to it (using .take(1)) every time I'd like to get it's current value which seems to be a little bit too much for such a primitive task.

**Comment by artem-zinnatullin** [comment]
No,  it has 'getValue()`!

**Comment by s0nerik** [comment]
Thanks for the info. I'm closing this issue.

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by ZakTaccardi** [comment]
Relays/Subjects work great for a non-collection variable, but what if I want to observe a key's value in a map?

**Comment by JakeWharton** [comment]
Emit the key and value as a pair, filter at the consumer site on the key
you care about. Or expose the value as itself an observable when you look
it up by key.

**Comment by ZakTaccardi** [comment]
my bad: implementing it is not too difficult, I am just surprised that an official "RxCollections"  library for RxJava does not exist. would be sweet!

> Emit the key and value as a pair, filter at the consumer site on the key
> you care about

While this is a quickest solution and would work with a `ReplayRelay`, this would have some performance issues as the buffer grows.

> expose the value as itself an observable when you look it up by key.

This is the better solution, provided we use a hot observable containing the value in the map (don't use `Observable.just(value)` because that will emit once and complete. I've implemented something like this and its working well so far.

edit: here's my RxMap as a [gist](https://gist.github.com/ZakTaccardi/8d5a42c029ae2580e711de05625f1d4a). Could certainly be improved by not using two maps
