### ISSUE TITLE
replay().connect() does not complete on current thread

### ISSUE THREAD

**Issue by hannesstruss** [ReactiveX/RxJava#3748]
This test case:

```java
  @Test
  public void test() {
    final AtomicBoolean onNext = new AtomicBoolean(false);
    final AtomicBoolean onCompleted = new AtomicBoolean(false);

    Observable<String> o = Observable.just("Hallo")
        .doOnNext(new Action1<String>() {
          @Override
          public void call(String s) {
            onNext.set(true);
          }
        })
        .doOnCompleted(new Action0() {
          @Override
          public void call() {
            onCompleted.set(true);
          }
        });

    ConnectableObservable<String> connectable = o.replay();
    connectable.connect();

    assertTrue(onNext.get());
    assertTrue(onCompleted.get());
  }
```

started failing for me on the latest snapshot. `git bisect` says c925e860c01c30edc15c59c592c1d5e9b9777a90 is the first bad commit. `.publish()` is not affected.

**Comment by akarnokd** [comment]
Previously, `just()` didn't support backpressure and emitted its value immediately after subscription. Now it waits for a proper downstream request which doesn't happen because `replay()` requests upstream only when there is a downstream request. Just add `connectable.subscribe()` to trigger `just()`.

**Comment by hannesstruss** [comment]
@akarnokd Thanks for the explanation!
