### ISSUE TITLE
OnSubscribeRange with AsyncOnSubscribe does not work without backpressure

### ISSUE THREAD

**Issue by Witko** [ReactiveX/RxJava#3793]
Hi,
im trying to implement observable with backpressure. i've investigated a bit and came with this solution: 
```
	@Test
	public void testObservable() throws Exception {

		Observable<Integer> observable = Observable.create(new AsyncOnSubscribe<Void, Integer>() {

			@Override
			protected Void generateState() {
				return null;
			}

			@Override
			protected Void next(Void state,
								long requested,
								Observer<Observable<? extends Integer>> observer) {
				observer.onNext(Observable.create(
						new OnSubscribeRange(0, Integer.MAX_VALUE -1)));
				return null;
			}
		});
		observable
//				.observeOn(Schedulers.computation())
//				.subscribeOn(Schedulers.io())
				.subscribe(d -> System.out.println(">>>>>>"));

		sleep(10000);
	}
```

I've found out that AsyncOnSubscribe provides basics for back pressure support and im using the OnSubscribeRange to n times call some method(via chained map operator)

The problem is that it seems its very unreliable in initialization. It works if i do the backpressure in subscriber(request(n)) but once i try to go without backpressure it does not work. Data is emitted but does not reach the subscriber. I believe its being accumulated in rx.observables.AsyncOnSubscribe.AsyncOuterManager#subscribeBufferToObservable endlessly. As if the subscribe was not noticed.

Am i doing something wrong? I understand that the AsyncOnSubscribe is experimental, so if there is any recommended way how to implement backpressure support correctly please point me to the right direction.

Currently we are using rxjava 1.1.2
NOTE: I understand that the OnSubscribeRange supports only max int values so i implemented OnSubscribeLongRange but the same behaviour applies for both.

Thank you in advance,
Viliam

**Comment by akarnokd** [comment]
`AsyncOnSubscribe` allows you to generate exactly the requested amount of values from a client that manually calls request(n) multiple times. Therefore, you shouldn't ignore the `requested` in `next` and in a general case, you should have used `observer.onNext(Observable.range(0, requested))` instead of the `create()` method and the internal operator for range.

However, any asynchronous and request-manipulating operator between the subscriber and this async generator will mess with that `requested` amount so you have most likely non-predictable amounts. In addition, the class can't validate that your `Observable` did actually emit the exact requested or it even supports backpressure. Therefore, there is an internal buffering going on that is flooded with your very large range.

I'm not sure what data source you wanted to create in the first place. It looks like a direct `Observable.range(0, n).map(...)` would have sufficed. If you have some state or resource dependence or some very special emission pattern, look at the `SyncOnSubscribe` that gives you proper backpressure, cancellation and won't buffer anything.

**Comment by Witko** [comment]
The thing i'm solving is - lets assume i have a buffer which is filled by loaders from db. I  want to attach an observable to this buffer and serve the data. I also need backpressure, cos the subscriber will most likely be slower.

For backpressure calls the ```requested``` field is rather small so its quite ok.
The reason why this example looks as it does is that the ``` OnSubscribeRange ``` supports only int range. Which does not comply with the ``` requested ``` field as it is long. So i only put there the max int for demonstration.

Yes in theory you are right that the ``` Observable.range(0, n).map(...) ``` could do the trick BUT i need "infinite" observable. For this i could assume long range to be sufficient but not Int. Still this would feel kinda "hacky".

The default behaviour without backpressure is that ``` Long.MAX_VALUE ``` is requested. So if i have a subscriber without backpressure support thats what i get in the ``` next ``` method.

**Comment by davidmoten** [comment]
Without commenting on the viability of your approach a range that supports `long` values can be created like this:

```java
Observable<Long> rangeLong = Observable.create(new SyncOnSubscribe<Long, Long>() {
			
			@Override
			protected Long generateState() {
				return 0L;
			}

			@Override
			protected Long next(Long n, Observer<? super Long> o) {
				o.onNext(n);
				return n+1;
			}
		});
```

You can then compose it with `take` to limit its output.

**Comment by Witko** [comment]
Hi,
thank you for your suggestions. I've ended  up with:
```
	observable = Observable.create(new SyncOnSubscribe<Object, Data>() {

			@Override
			protected Void generateState() {
				return null;
			}

			@Override
			protected Object next(Object state, Observer<? super Data> observer) {
				observer.onNext(nextData());
				return null;
			}
		});
```

This seems to work just fine.
Thanks again!

**Comment by stealthcode** [comment]
A more concise way to write this would be to use the static initializer on
SynOnSubscribe.createStateless(...)

**Comment by Witko** [comment]
Thanks! even nicer
