### ISSUE TITLE
2.x: Remove global state, make RxJava instantiable and immutable?

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#4000]
At the moment, RxJava v1.x is a library with mostly `static` API like `Observable.just()` and so on. 

**But** it also has global shared `static` state, mostly for hooks. 

Why global state is bad:
- A lot of libraries use RxJava nowadays, when you want to change some behavior of RxJava for your code or some library in particular you also affect all other code that uses RxJava in your program.
- Any change of global state in multithreaded runtime is dangerous.
- Because of thread-safety required for this global state  RxJava has to apply atomic/synchronized operations to access it in many parts of Rx chains lifecycle which degrades performance a little bit.
- Some parts of hooks done through system properties, some via explicit API, not very consistent.
- Order of class initialization sometimes breaks hooks API and generally plays bad with static hooks.
- RxJava makes multithreading easy and immutability of the data that goes through Rx chains is a must have, but library itself is not immutable, that's awkward because RxJava brings a lot of functional aspects and immutability is fundamental to the concept.

What I think of is to **make RxJava instantiable** and remove all shared state between RxJava instances. Just like any other normal library such as Retrofit, Moshi, OkHttp (mostly) and others.

``` java
RxJava rxJava = RxJava.builder()
  .ioScheduler(…)
  .computationScheduler(…)
  .flowExecutionHook(…)
  // and other configurations
  .build();
```

At the moment, we have to pass bunch of schedulers everywhere through DI just for unit testing, we can't apply execution hooks partially to our code (for functional tests and metrics), libraries tend to use standard schedulers and it's very hard to change them without changing them for all other code and so on and so on.

Usage example:

``` java
rxJava
  .flow()
  .from(…)
  .map(…)
  .filter(…)
  .flatMap(…)
  // …
```

Libraries will simply need to accept `RxJava` instance and you will be able either share one RxJava instance between all of them or control precisely how particular library will use RxJava.

Testing will be easier because you can pass RxJava instance configured for testing as you need.

``` java
RxJava testRxJava = RxJava.builder()
  .ioScheduler(immediateScheduler)
  .computationScheduler(immediateScheduler)
  .build();
```

---

Does that make sense for others and do you fill need in that too or I'm alone here?

**Comment by artem-zinnatullin** [comment]
Forgot to add that in this case, interfaces for basic types like `Observable` (Flowable) and others will make sense, you'll be able to implement let's say ReactorRxJava or AgeraRxJava and provide custom implementation for libraries that know only about RxJava.

// Another point for interfaces is to be able to return mock of `Subscription` from `subscribe()` to verify unsubscription, but it's out of the scope of this discussion.

**Comment by abersnaze** [comment]
Would flatMap provide the RxJava instance for the creation of sub Observables?

``` java
out = in.flatMap((value, rx) -> rx.just(value.length()))
```

or would you have to close over the instance?

``` java
out = in.flatMap((value) -> in.getRx().just(value.length()))
```

**Comment by artem-zinnatullin** [comment]
I think will be better to provide API like `Observable.rx()` (`Flowable.rx())` to be able to operate on the source `RxJava` instance of unknown `Observable`.

-> `out = in.flatMap(value -> in.rx().observable().just(value.length()))`

**Comment by abersnaze** [comment]
what is `it` (in plain old java)?

**Comment by abersnaze** [comment]
is this a proposal for 1.x or 2.x?

**Comment by artem-zinnatullin** [comment]
Sorry, meant `in` of course! Fixed.

Proposal is for 2.x (see title).

**Comment by artem-zinnatullin** [comment]
Additional bonus: testing RxJava itself in this repo will be much easier without global shared state between tests. I believe @akarnokd will really appreciate it.

**Comment by akarnokd** [comment]
I'm still evaluating this proposal and its consequences. Here are my preliminary thoughts:
- The `RxJava` type you are proposing looks like any context object that has to be passed around with the current design.
- Such context-objects lead to complaints about why `observeOn` doesn't preserve it and how ThreadLocals have to be used.
- One possible outcome of having individual RxJava objects is that every library may set its own computation scheduler, sized to the available CPUs, and now you have 2..N times CPUs threads for computation.

**Comment by artem-zinnatullin** [comment]
1. Yes, it's like any context object, **but it's ok for configurable objects**. I would not open this issue if RxJava would be set of utility functions. Also, as said above I (maybe it's my bad) already have to pass schedulers all over the code for testing.
2. Not sure I understand the problem.
3. This proposal naturally requires libraries which depend on RxJava to accept instance of RxJava instead of creating one themselves (see how libraries use Gson, OkHttp, Moshi and so on). As a user you will have full control over schedulers so it's up to you to share them between RxJava instances or not.

**Comment by akarnokd** [comment]
My 2) point relates to @abersnaze 's https://github.com/ReactiveX/RxJava/issues/4000#issuecomment-224748904 comment: you either have to capture the `rx` or tag it along with many operators.

The next problem I see is that libraries have to provide API to accept the `rx` factory, but there is no guarantee they'll do it and run on their own internal factory and no chance of overriding that. Otherwise, if the libraries are willing to accept extra parameters, they could also accept user-provided schedulers, thus we can keep the current style of jumpstarting sequences.

The final problem is the conversion of 3700+ unit tests; some use standard sources, some use custom `OnSubscribe` code. It took me 2.5 weeks to convert from 1.x to 2.x; plus quite a lot of new tests were added in the past 9 months to 1.x that have to be ported as well.

Personally, I think switching to the Reactive-Streams style as well as the `Flowable`/`Obserable` swapping is enough change for 2.x. The extra indirection requires learning an even more different style and may burden all uses of the library to manage this `rx`-context object.

Since this issue is triggered by the lack of scheduler customization in 3rd party libraries, the alternative solution could be to simply don't have operators with default schedulers on `Flowable` etc. but always mandate one explicitly.

Finally, I encourage you to create a prototype fork from the current 2.x master and see how and what it takes switch to the suggested style.

**Comment by ZacSweers** [comment]
I don't think this is a necessary change judging by the argument's current form, and I don't really agree with the blanket statements used to justify "global state is bad".

> A lot of libraries use RxJava nowadays, when you want to change some behavior of RxJava for your code or some library in particular you also affect all other code that uses RxJava in your program.

To me, a library that defers to this rather than their own scheduler is simply saying that they defer to what the consumer wants. They're aware of this. If they need a specific scheduler, they should use their own or accept it as a parameter. You could just as easily flip this around to say that library developers then lose the ability to easily defer to the execution environment and now have to add these annoying parameters everywhere to force the user to pass in their instance. This opens up other cans of worms too: per-library? per-class? per-usage? What's the convention? Why can't there be a default?

> Any change of global state in multithreaded runtime is dangerous.

This statement is far too general and not really valid justification IMO. You should really be specific as to what states you're referring to and why they're dangerous. It seems to me your main issue is with the plugins/hooks API, which I argue farther down is equally as prone to bad developers doing stupid things as non-static APIs are.

> Because of thread-safety required for this global state RxJava has to apply atomic/synchronized operations to access it in many parts of Rx chains lifecycle which degrades performance a little bit.

Can you quantify this? If it's negligible (which I believe it is), then I don't really think it matters. Even if it did, schedulers are already cached and plugins are only set once, so the perf impact largely only affects the first user. The only time this would happen frequently is in tests, where perf is much less of an issue.

> Some parts of hooks done through system properties, some via explicit API, not very consistent.

I think we all agree the current 1.x hook system is not ideal. There is already a new hooks API in 2.x, so I think this is a false comparison.

> RxJava makes multithreading easy and immutability of the data that goes through Rx chains is a must have, but library itself is not immutable, that's awkward because RxJava brings a lot of functional aspects and immutability is fundamental to the concept.

Again, it's just the hooks and plugins. I would argue these are a small-but-necessary evil to that give RxJava much of its flexibility. 

> What I think of is to make RxJava instantiable and remove all shared state between RxJava instances. Just like any other normal library such as Retrofit, Moshi, OkHttp (mostly) and others.

These are not valid comparisons. Different libraries with different usage and purposes. You instantiate Retrofit objects because it's one object per service, not one global object that's passed around. Moshi has a lot of stateful internals that make an instance unique, whereas RxJava only has a handful of these. They are also not used as ubiquitously as RxJava is. A more valid example would be something like `Timber`. Can you imagine if you had to inject that everywhere you wanted to use it? Simple classes, utility methods, etc all suddenly require DI or an extra parameter.

I don't agree with those that would argue that anything and everything should be injected with DI and mockable, which this seems to be partially motivated by. Like everything else, the answer is "it depends". In RxJava's case, I think the flexibility to use it via static APIs is part of what makes it so appealing and powerful. The plugins and hooks are invisible to most users currently, and forcing this to a system where everything is an instance that must be passed around seems like major overkill.

This seems like an issue that largely revolves around the sticky 1.x plugins API, but you didn't talk at all about the improved rewrite of it that already exists in 2.x. I'd like to know what's wrong with that, rather than generalized "plugins are stateful, therefor rx is stateful, therefore everything is dangerous" vibe that the current argument seems to revolve around.

---

As brief counter-examples:

**If the goal is better testing support:** I wrote a nice test rule that lets you set schedulers on the fly for testing, and is quite clean. Simply add your rule, and call appropriate setters on it as needed in your tests. State is always cleared before and after to ensure clean and isolated states. Not all doom and gloom.

**If the goal is to make state immutable and not dangerous:** It seems to me the crux of this argument is around preventing programmers from writing dangerous code. Someone could still accidentally set Schedulers.io() to use a main thread scheduler. There's only so much you can do to protect against people doing bad things. To restructure an entire framework just to make something that largely invisible to most users, has sensible default configurations, and obvious when misconfigured seems like a massive overreaction.

---

To be clear, I'm not coming out 100% against this. I _do_ think there needs to be much better reasons to do this than what have been presented so far.

**Comment by dlew** [comment]
My main concern for a change like this is just the ease of use. This proposal adds a lot of boilerplate to RxJava coding.

It'd be especially weird coding when you're doing nested actions like `flatMap`, since you'd need to repeatedly use the `RxJava` instance inside of it. e.g.

``` java
rxJava.flow().from(someStream)
    .flatMap(item -> rxJava.flow().from(item.getItems()))
```

**Comment by artem-zinnatullin** [comment]
@hzsweers

> You could just as easily flip this around to say that library developers then lose the ability to easily defer to the execution environment and now have to add these annoying parameters everywhere to force the user to pass in their instance.

True, until you use schedulers. To test that code you either need to pass/accept schedulers or override them with hooks.

> This opens up other cans of worms too: per-library? per-class? per-usage? What's the convention? Why can't there be a default?

Up to you. You can setup one `RxJava` for `Retrofit` and another for `SQLBrite` or have one per app, the choice is what this proposal is about.

> Thread safety.

Ok, your app is running, you need to apply hook. How do you guarantee expected behavior for both already running Rx chains and new ones?

Hooks look pretty similar to `OkHttp` Interceptors API. In v3 you can't now add/remove them without creating new `OkHttpClient`, one of the reasons was thread safety for consumer code.

> If the goal is to make state immutable and not dangerous.

Yes, that's one of the goals.

---

@dlew you can just name `RxJava` instance `rx`:

Today:

``` java
flatMap(item -> Observable.from(item.getItems()))
```

Tomorrow:

``` java
flatMap(item -> rx.flow().from(item.getItems()))
```

> This proposal adds a lot of boilerplate to RxJava coding.

Yeah, I agree that it's quite easy to use current static API and that's not the reason of why this proposal was created, it's more about immutability of library itself and safety in multithreaded environment + ability to configure it precisely for some use-cases without affecting others.

**Comment by artem-zinnatullin** [comment]
Ok, let's close it for now, anyway I'm happy to receive your feedback guys and we can now refer to this discussion in future, thanks everybody 👍.
