### ISSUE TITLE
1.x: proposal for allocation reduction in the base types

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4098]
The current architecture of 1.x uses `lift` and `Operator` to implement most operators instead of `create` and `OnSubscribe`. This requires an extra object allocation when operators are assembled and could be amplified if those operators are part of the inner input to `flatMap` for example.

Due to public API compatibility, we can't change the base types to facilitate direct extensions (unlike 2.x) but the operators can be trivially rewritten to all extend their respective `OnSubscribe` interfaces.

The second inefficiency is around `Single`: the design wanted to reuse `Observable` operators at the cost of serveral entry- and exit type conversion which all involve allocating wrapper objects.

My main proposition is as follows:
- change all `Observable` operators to be `OnSubscribe` - trivial changes
- replace all `Single` operators with factored out versions, implementing `Single.OnSubscribe` - introduces aroun 50 new classes

My secondary proposition is that since `Single` is `@Beta` and `Completable` is `@Experimental`, I believe their architecture could be changed before they are promoted to final so that their operators extend the base type instead of implementing some `OnSubscribe`, saving an additional allocation.

From API use perspective, they would remain the same. However, the change is definitely binary-incompatible. I'm up for feedback if such change is acceptable on such non-release types.

**Comment by artem-zinnatullin** [comment]
❤️  that you're trying to do best to achieve performance and resources consumption. But it saves not so many memory allocations (most of created objects have very short lifetime btw), increases binary size and methods count of the library and most important: it'll require a **lot of time** for you and all code reviewers to implement that proposal. I'd prefer to see it in 2.x if you don't mind.

Since you're **very** actively working on 2.x, its release seems much closer that it was. Maybe it's time to stop doing such architectural changes in 1.x and focus effort on 2.x?

1.x can be switched to maintenance mode: bug fixes, new non-breaking APIs from the community and significant performance improvements. Actively supporting several versions of the project is very hard and time consuming, it gives community feeling that it's ok to stay on old versions and there are not many reasons to migrate to new ones and maintainers usually hate supporting old versions when new ones already released.

**Comment by davidmoten** [comment]
I like the change because I'm a consumer of large archived streams in particular and I appreciate the performance gained by reducing allocations. I have noticed with RxJava and other projects that reducing  allocations (even short-lived ones) does equate to significant performance improvements (percents here and there) in JMH runs of decent duration and these improvements are of direct benefit to me. 

The sample PR for this change in #4097 does indicate that the change is trivial and could be performed quickly. Luckily there's been a massive cleanup on the PRs (thanks @akarnokd) so finding a window to do this without causing too much rebase pain shouldn't be too difficult I suspect.

**Comment by akarnokd** [comment]
Don't worry about how much time this takes to accomplish; I don't expect too much interference before 1.1.7 so this can be done under a week (including reviews).

**Comment by stevegury** [comment]
I'm only talking about server side code here, and I understand that this could be different on Android, but I agree with @artem-zinnatullin here.

In my experience, in the type of applications we're running at Netflix, RxJava only consumes between 5% and 10% of all resources (CPU & Memory) of a server. Even improving RxJava by 10% will only improve our applications resources consumption by 0.5%-1%, at the risk of introducing bugs.

Furthermore, short-lived object allocations tend to be optimized away by [Hotspot escape-analysis](https://en.wikipedia.org/wiki/Escape_analysis). I have no experience with Android JVMs and I don't know how efficient is escape analysis on Android.

For all those reasons, I would prioritize the work on the 2.x branch above those change in 1.x.
That being said, I'm not opposed to those optimizations, if in some case they are easy, go for it.
