### ISSUE TITLE
1.x: OnSubscribeConcatMap regression IllegalStateException: More items arrived than were requested

### ISSUE THREAD

**Issue by nikitin-da** [ReactiveX/RxJava#4162]
Hi!
Starting from 1.1.2 and above test failed =(

``` java
@Test
public void producerArbiterWithFewOnSubscribe() throws InterruptedException {
    TestSubscriber<Object> testSubscriber = TestSubscriber.create();

    Observable.just(new Object())
            .startWith(Observable.create(subscriber -> {
                if (!subscriber.isUnsubscribed()) {
                    subscriber.onNext(new Object());
                    subscriber.onCompleted();
                }
            }))
            .subscribeOn(Schedulers.io())
            .subscribeOn(Schedulers.io())   // twice
            .subscribe(testSubscriber);

    testSubscriber.awaitTerminalEvent();
    testSubscriber.assertNoErrors();
}
```

**Comment by artem-zinnatullin** [comment]
Yup, I confirm. Would be great to include fix to 1.1.7!

**Comment by JakeWharton** [comment]
Well, does it fail if you honor backpressure in your custom observable (or
just switch to `startWith(just(new Object()))`)?

**Comment by artem-zinnatullin** [comment]
Yup, passes if Observable in `startWith()` honors backpressure:

``` java
@Test
public void producerArbiterWithFewOnSubscribe() throws InterruptedException {
    TestSubscriber<Object> testSubscriber = TestSubscriber.create();

    Observable.just("a")
            .startWith(Observable.create(subscriber -> {
                subscriber.setProducer(new SingleProducer<>(subscriber, "b"));
            }))
            .subscribeOn(Schedulers.io())
            .subscribeOn(Schedulers.io())   // duplicate
            .subscribe(testSubscriber);

    testSubscriber.awaitTerminalEvent();
    testSubscriber.assertNoErrors();
    testSubscriber.assertValues("b", "a");
}
```

**Comment by JakeWharton** [comment]
Yep. Nothing to fix here.

**Comment by akarnokd** [comment]
When you use `create`, you have to deal with backpressure yourself. In your case use `just` or `fromCallable` instead.

**Comment by nikitin-da** [comment]
Ok. Thanks

**Comment by artem-zinnatullin** [comment]
Hm, well you're right, but changelog for 1.1.2 didn't mention that `Observable` passed to `concat`, `startWith` and `concatMap` now required to honor backpressure.

Maybe worth to add that to changelog? Otherwise it is still a regression in my opinion because it breaks existing code (which isn't perfect, but worked with RxJava < 1.1.2).

**Comment by zsxwing** [comment]
This sounds like a regression? People can write a hot Observable like this. Right?

**Comment by akarnokd** [comment]
You can write such observable, but then you have to apply `.onBackpressureX` to work with most standard operators. The problem is that people write such trivial `create` methods (taken from an example/presentation from 2-3 years ago) instead of using `just` or `fromCallable`.

I assumed the requirement for backpressure support is almost universal but the javadoc still doesn't mention it at many operators. I'll do a pass and update the javadoc.

**Comment by akarnokd** [comment]
See #4172 for the updated doc.
