### ISSUE TITLE
replay does not cache if subscribed to using toBlocking().toFuture().get()

### ISSUE THREAD

**Issue by ppiech** [ReactiveX/RxJava#4547]
Given the following snippet:

```
    BehaviorSubject<Observable<Integer>> s = BehaviorSubject.create(Observable.just(1));

    Observable<Integer> o = s.flatMap(sp -> sp).replay(1).autoConnect();

    //o.subscribe();

    System.out.println("1st = " + o.first().toBlocking().toFuture().get(0, TimeUnit.SECONDS));

    s.onNext(Observable.just(2));

    System.out.println("2st = " + o.first().toBlocking().toFuture().get(0, TimeUnit.SECONDS));
```

I expect output: 

```
1st = 1
2nd = 2 
```

instead I get 

```
1st = 1 
2nd = 1
```

If I uncomment o.subscribe(), then the replay value gets updated correctly on 2nd.  Also it works correctly if not using the flatMap().

**Comment by akarnokd** [comment]
`replay` only moves as far as there were requests. Since both `o.first()` request 1 (due to `take(1)` inside), `replay` doesn't request more from the `flatMap`. Without `flatMap`, there is no backpressure and the `s.onNext(Observable.just(2))` is forced through into the `replay`. When you have a consumer like `o.subscribe`, that requests `Long.MAX_VALUE` which then allows `replay` to move forward and take in the 2nd Observable.

**Comment by ppiech** [comment]
The explanation make sense, but it doesn't leave me with any good workaround.  Is there an alternative to replay() which ignores backpressure?

**Comment by akarnokd** [comment]
``` java
o.subscribe();
```

that will unbound it.

**Comment by ppiech** [comment]
I think this means that if I'm dealing with an open observable, it's not safe to use `o.first().toBlocking().toFuture()`
instead I should use 
`o.toBlocking().next().toIterator().next()`
The downside is that the latter may deadlock if I haven't implemented my observable correctly, where as the former would throw an exception.

Or I should add 
`o.subscribe().unsubscribe()` prior to calling `toBlocking()`.
but it really looks like a voodoo hack.

Thank you for the explanation!
