### ISSUE TITLE
2.x: Handling null values

### ISSUE THREAD

**Issue by paveldudka** [ReactiveX/RxJava#4644]
With the upcoming RxJava2 release one of the important changes is that `null` is no longer accepted as a stream element.

Honestly, I have mixed feelings about this change and part of me understands that it will enforce clean APIs, but I can see a number of use cases when this might be a problem.

For instance, in my app I have an in-memory cache:

```
@Nullable CacheItem findCacheItem(long id);
```

CacheItem might not be present in cache, so method might return null value.

The way it is used with Rx\* - is as following:

```
Observable<CacheItem> getStream(final long id) {
    return Observable.fromCallable(new Callable<CacheItem>() {
        @Override public CacheItem call() throws Exception {
            return findCacheItem(id);
        }
    });
}
```

So with this approach, I might get null in my stream which is totally valid situation, so it is handled properly on receiving side - let's say UI changes its state if item is not present in cache:

```
Observable.just(user)
          .map(user -> user.getName())
          .map(name -> convertNameToId(name))
          .flatMap(id -> getStream(id))
          .map(cacheItem -> getUserInfoFromCacheItem(cacheItem))
          .subscribe(
              userInfo -> {
                  if(userInfo != null) showUserInfo();
                  else showPrompt();
              }
          );
```

With RxJava2 I am no longer allowed to post `null` down the stream, so I either need to wrap my CacheItem into some other class and make my stream produce that wrapper instead or make quite big architectural changes.

Wrapping every single stream element into nullable counterpart doesn't look right to me.

Am I missing something fundamental here? 

It seems like the situation like mine is quite popular, so Im curious what is the recommended strategy to tackle this problem given new "no null" policy in RxJava2?

**Comment by artem-zinnatullin** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls

**Comment by vietj** [comment]
I believe this is a valid case and the link pointed by @artem-zinnatullin does not address the situation.

In a language supporting union types (like Ceylon) that would be valid and the case above would be typed as `Observable<CacheItem | Missing>`.

As @paveldudka said the only way to handle this without loosing type safety with the current situation would be to use a wrapper type:

for instance

```
Observable<Optional<CacheItem>> getStream(final long id) { ... }
```

In this specific case maybe a more convenient way would be to use a pair as this is a cache lookup, so I would likely use something like:

```
Observable<Map.Entry<Long, CacheItem> getStream(final long id) { ... }
```

But this is sometimes not feasible.

**Comment by akarnokd** [comment]
Alternative is to use a null-sentinel value of `CacheItem` and do a comparison against it instead of null:

``` java
static final CacheItem NOT_FOUND = new CacheItem(...);

Observable.just(1)
.map(v -> {
   CacheItem ci = getFromCache(v);
   return ci != null ? ci : NOT_FOUND;
})
.filter(ci -> ci != NOT_FOUND)
...
```

**Comment by vietj** [comment]
@akarnokd if you create a reactive stream with objects you do not control this can be a problem (for example you create a Flowable of objects of a library that keeps control over the instance creation), using then `concatMap` does the same (but is more expensive)

**Comment by paveldudka** [comment]
I believe the most "natural" way for dealing with null values in RxJava2 would be to return stream of `Optional` elements instead or "raw" ones.

**Comment by danielesegato** [comment]
This is really bad.

Nulls values are really needed in Java. You are forcing to clutter the API of our apps with `Observable<Optional<Stuff>>` when we could just use `Observable<Stuff>`.

I also don't like at all the `NOT_FOUND` suggestion from @akarnokd and I'm specially concerned of this when you need to wrap others APIs (where you have no control on).

I can understand the decision about nulls in 2.x but I do not think it is a good idea in Java, at all.

Edit: to give you another example: Android Data binding throw `ObservableField<T>` can be easily wrapped in an Rx `Observable<T>` to receive every user modification. That field CAN be null and that's actually a perfectly valid value for it! Wrapping it in an `Observable<Optional<T>>` is an unnecessary complication.
I expect you'll get a lot of hate for this decision from developers.

**Comment by dimsuz** [comment]
> That field CAN be null and that's actually a perfectly valid value for it!

Than you can adapt it to more sane RxJava 2.x world by doing 

``` java
observableFields.map(v -> if (v == null) { return NOT_FOUND } else { return v } )
```

**Comment by danielesegato** [comment]
@dimsuz  what is `observableFields` in your example? On Rx 2.0 null can't be there and can't be mapped. also NOT_FOUND = ?
If it's a string or an enum mapped to a Spinner (selector) where the user didn't picked anything / removed the pick?

Even worst what if it's an object of a class provided by a library? There are many cases like this. Just ignoring the fact that null is a perfectly valid value in Java is hiding your head in the sand.

Anything you do to make it work without null (in any situation) is a workaround that add unnecessary complexity.

**Comment by dimsuz** [comment]
Right, my example was kinda wrong.

I see `null` concept as a bit mixed thing, which can mean an error and an absence of value (which is itself can be seen as value). So it implicitly encodes these meanings, it's semantics is unclear because of this.

It's far better to have some explicit `NOT_FOUND` value.

If this library decided to go this more explicit way you can easily follow it. Even if some library does not follow this and has `null` objects signalling an absence of value, then you can write a simple adapter around it.

You can extend enum with a special value, or wrap it in Optional or something like this.

In absence of sum types in Java this is a tradeoff you get for better type checking && safer runtime...

But I agree, this is the kind of question which can easily result in flame wars, I guess we can go on and on about pros & cons.

I would say that developers of this library should decide.

**Comment by JakeWharton** [comment]
It's not RxJava's choice, it's in the reactive streams spec.

**Comment by danielesegato** [comment]
@dimsuz I agree that you can work around it, creating dedicated "NULL_VALUE" constants, wrapping in Optional classes or whatever.

I need to wrap I library that can return NULL values?

1.x: No problem, I just use emit it's values and handle them in an Observable, peace of cake.
2.x: Ah, nope I need to create a wrapper class (Optionable<> or whatever)

Let's now say you need to map those values to something else, using another library that interoperate with it:

1.x: No problem: .map() etc and you are good to go, that other library already handle nulls cause it has been writted to work with it
2.x: Since Optionable is now in the way i need to extract the value, then re-wrap the new value if that can be null.

Code is bound to get messier.

And backward compatibility? That will be an HELL. Libraries that are still 1.x will not be usable by 2.x because they'll start crashing on nulls. Overall I'm very concerned with this decision.

**Comment by JakeWharton** [comment]
It was decided nearly two years ago in the reactive streams spec.

**Comment by ZakTaccardi** [comment]
@JakeWharton do you agree with the ReactiveStreams spec? (maybe there's a certain reason nulls are not allowed that I'm not aware of)

Maybe we can petition those maintaining the reactive streams spec to allow nulls?

**Comment by danielesegato** [comment]
@JakeWharton [this](https://github.com/reactive-streams/reactive-streams-jvm) one?

Do you know if I can find a discussion about this of 2 years ago? I'd like to understand the reasoning behind and what led to the decision. Thank you.

I've find [this](https://github.com/reactive-streams/reactive-streams-jvm/issues/204) discussion and [this](https://github.com/reactive-streams/reactive-streams-jvm/pull/209) one. I'm gonna need sometime to read them all :) can't now.

**Comment by smaldini** [comment]
the reason is that you can't buffer/queue nulls when doing message passing, and the spec is all about message passing.

**Comment by vietj** [comment]
@smaldini out of curiosity, how do you handle `Mono<Void>` in RSC without null ?

**Comment by akarnokd** [comment]
Rsc doesn't have a 0-1 type. Reactor's `Mono<Void>` is a `Publisher` and follows the same rules - it never emits `onNext`.

**Comment by vietj** [comment]
@akarnokd thanks for clarification

**Comment by smaldini** [comment]
`Publisher<Void>` is a valid Publisher that will never emit `onNext` indeed. That's one of the main semantic differences we have vs Maybe/Single/Completable in Reactor to still implement `Publisher` at every stage. In that case it pretty much leverages the deferred nature of `Publisher#subscribe` to implement a form of backpressure : don't do anything until subscribed.

**Comment by ScottPierce** [comment]
In the process of upgrading some libraries from 1.x to 2.x, this has shown itself to be very painful.

i.e. my company uses a library where we can subscribe to all changes to persisted values, and it's perfectly valid for a value not to be persisted yet, and thus be null.

Wrapping values in `Optional` seems annoying while programming in Kotlin, and creating a `NOT_FOUND` value for the various types also seems annoying. For instance, it's not obvious what value you'd use for a `Date` object.

I understand that the decision for the spec is outside the scope of this project, but I do find the change where it's now enforced in 2.0 to be frustrating, and felt the need to add  my voice to the mix.

**Comment by ZakTaccardi** [comment]
Yep. Use `Optainal`

**Comment by ScottPierce** [comment]
I ultimately chose the `Optional` approach, as it seems like it'll be more consistent than the alternatives. It's too early to tell how my team feels about it. I'll give it a few weeks.

**Comment by ivnsch** [comment]
How to handle this in Android Kotlin...? There are no optionals, since Android doesn't support Java 8, for lists it's also [not possible to return empty lists](https://stackoverflow.com/questions/33005866/observable-empty-causes-java-util-nosuchelementexception-sequence-contains-no/33006165#comment76120359_33006165), so all I can do is to return `Object()`, which basically makes me change the type of the observable to `Object`, losing type safety everywhere...?

Maybe I can use an "either" type or similar?

**Comment by ScottPierce** [comment]
@i-schuetz It's a crappy solution, but it works: https://github.com/memoizr/retro-optional

**Comment by ivnsch** [comment]
@ScottPierce thanks! I was able to solve it with funKTionale but there are some transitive dependency problems and I don't need all that just for the optionals...

I wonder, someone mentioned the use of rx's `Maybe` for this, though it's not quite the same thing. It would at least not involve adding another dependency... thoughts?

**Comment by ScottPierce** [comment]
As long as you are willing to change the way that you deal with streams, `Maybe` could work. I personally think that makes streams even more frustrating than `Optional`, but feel free to give it a shot.

If you are using Kotlin, we found that by adding some extension functions / properties, `Optional` is a lot easier to swallow. Namely:

```Kotlin
val <T> Optional<T>.value: T?
    get() = if (isPresent) get() else null
```

**Comment by ivnsch** [comment]
@ScottPierce yeah I tried `Maybe` but there were some awkward parts, like `getOrElse`, in particular `isDefined` ... (seems to need something like `blockingGet() != null`? Not sure...). All in all it has a different purpose in mind so I'm using retro's `Optional` now, all good! I also came to the idea of adding those extensions as they were present in funKTionale, also to convert normal/Kotlin "optionals" objects to optionals...

Thanks!

**Comment by artem-zinnatullin** [comment]
You can try Koptional, it's small, made with usability in mind and tries to fit Kotlin's design, also has extensions for RxJava: `filterSome()` and `filterNone()`

https://github.com/gojuno/koptional

**Comment by ubaierbhat** [comment]
Why not add an implementation of `Optional<T>` in RxJava2 (or RxAndroid)  since `null` is illegal now.

**Comment by JakeWharton** [comment]
Use java.util.Option

**Comment by ZakTaccardi** [comment]
@JakeWharton but it's not an option on Android - `java.util.Optional` is Java 8

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by akarnokd** [comment]
Exactly. Targeting Java 6, there is no standard `Optional` and we didn't want to introduce yet another one.

**Comment by JakeWharton** [comment]
Use Guava's Optional.

**Comment by yuriykulikov** [comment]
You can use Guava Optional or Vavr option. Both work well with Immutables.io. If you are not using them and application size is an issue, you can throw in a simple optional implementation. It will be like 100 lines.

**Comment by justjanne** [comment]
So, @JakeWharton , the official solution is to *double* every short-lived event object, and the resulting GC load? That’s not even close to a usable option, this is never going to handle thousands of messages per second on a mobile phone when every single one has to be wrapped twice, unwrapped twice, and the GC has to collect all those objects again.

Are there any other solutions being worked on?

**Comment by JakeWharton** [comment]
Send batches.

**Comment by justjanne** [comment]
@JakeWharton Not an option. So the answer is "never use RxJava2" then?

**Comment by JakeWharton** [comment]
Use null object pattern.

**Comment by halfhp** [comment]
> Use java.util.Option

How is this different than using null as a sentinel (aside from being less efficient), which was a big reason for [not supporting null](https://github.com/reactive-streams/reactive-streams-jvm/issues/204#issuecomment-70711355) in the first place?

**Comment by JakeWharton** [comment]
Because it's explicitly not null allowing the library to use null
internally as its own sentinel in queues.

**Comment by halfhp** [comment]
Hmmm, as far as I can follow in the thread re the change, I didnt notice anyone mention that as a goal.  Also seems a little odd for them to poop on using null as a sentinel, so they could turn around and use null as a sentinel :p

**Comment by JakeWharton** [comment]
Heh, yep!

Another advantage I perceive although I'm not sure it was a goal is that
you never have to worry about null checking values in almost all callbacks
from the library. Since there's no real way to propagate the fact that a
value might be null down the stream this eliminated a good chunk of
needless defensive coding in common code for me.

**Comment by akarnokd** [comment]
Disallowing null was the decision the Reactive Streams project made. Compliance requires that we honor this as well. Knowing that flow items coming through onNext can never be null allowed us to utilize null as a sentinel in internal queues for example. So we didn't disallow null values so that we can optimize internal logic and afaik the decision wasn't about such possibility either. As Jake mentioned, it turned out non-null has other benefits.

**Comment by romanpa** [comment]
Hi

While we were using rx1 we had a lot of Single.just(null) , `Single<Void>` and things like this that in rx2 we are actually had been forced to represent as Completable.  But it's impossible to chain completables in lazy way like .map(), .flatMap() and etc.  in other types. Compeltable.andThen expects 'eager' completable. 
We are missing here a lazy 'andThen()' implementation, something like this:

```
public abstract class Completable implements CompletableSource {
    public final <T extends CompletableSource> Completable andThen(Supplier<T> defer) {
        return concatWith(Completable.defer(defer::get));
    }
}

```
This function would greatly simplify a people's life (refactoring of rx1 to rx2).  And will eliminate the need of messing around with 'Optional' and generally will 'clean' a code.

**Comment by akarnokd** [comment]
@romanpa The answer is: use `Completable.defer` if you need to defer the creation of the `Completable` that is to follow and use `andThen` as usual. You can even implement it as a `CompletableTransformer` and use static imports to avoid spelling out factory classes.

**Comment by romanpa** [comment]
I need a lazy way to chain completables.
This is my actual request.
Completable as it's now, introduce inconsistent behavior in rx
You can write `Single.just(1).flatMap(o -> Single.just(o*2))` when ` Single.just(o*2)`  will be lazily created.
And you cannot write` Completable.complete().andThen(() -> lazyCompletable)`

Of course that I can put every where Completable.defer , but it blows up the code , make it ugly and hard to read + if you have a huge amount of code like we do, it's a lot of work .

What is cleaner Completable.complete().andThen(() -> lazyCompletable) or Completable.complete().andThen(Completable.defer(() -> lazyCompletable))

**Comment by romanpa** [comment]
We could live with this limitation in rx1, but with restrictions of rx2 it's become a problem

**Comment by akarnokd** [comment]
Use static imports to remove some boilerplate, use Kotlin or keep using `Single` with an arbitrary non `Void` type and value.

```java
import static io.reactivex.Completable.defer;

Completable.complete().andThen(defer(() -> lazyCompletable))
```

**Comment by romanpa** [comment]
All things that you are proposing are actually some sort of hacks. Kotlin is out of scope and over-complicated solution to this problem. Kind of swatting flies with a sledgehammer.
Single.just(true) and things like this are also pretty ugly hack. When there is no meaning in returned value one should use Completable , shouldn't he?
static defer - it's also hack that adds unnecessary boilerplate code.

When you use a library you expect it to be consistent with itself.

The need to use a hack in itself demonstrates that there is a problem. I am not talking here about some theoretical things. We are very heavy users of RX with tons of code. The move from rx1 to rx2 it's a very resource demanding for us. And if we are already doing it, we would like to do it in a right way.

**Comment by justjanne** [comment]
And wrapping Objects in Optional more than doubled my GC load, and the alternative was replacing null checks everywhere with ugly comparisons for equality (which is also slower, because Java special-cases null-comparisons for better performance, but can't do the same with `== SomeInterface.NULL`). Disallowing nulls may make sense in languages with value objects, in Java it's more than suboptimal.

**Comment by akarnokd** [comment]
There is a limit how much convenience operators is accepted with RxJava given that there are too many operators already which by itself is frequently complained about. You can create a transformer that hides most of the boilerplate:

```java
public static CompletableTransformer x(Callable<Completable> next) {
   return c -> c.andThen(Completable.defer(next));
}

Completable.complete().compose(x(() -> Completable.complete()));
```

Also you can name it as short as you wish.

> The need to use a hack in itself demonstrates that there is a problem.

There is a fundamental limit on the expressiveness of Java itself and how expressive a library on top of it can be. Java language support for avoiding boilerplate comes few and far between, that's why many use Kotlin with RxJava.

The non-null requirement comes from the Reactive Streams specification and in fact allows less overhead for RxJava 2 because unlike 1.x, we don't have to do the `null` -> null-indicator wrapping/conversion/equivalence tests for every item, even if the entire flow doesn't use `null`s at all.

You are/were likely using the wrong abstraction and/or you have to put in more effort and come up with tools to factor out the repeating boilerplate you are experiencing.

**Comment by httpdispatch** [comment]
Possible solution is to use `Maybe.switchIfEmpty`

Example:

   ```
 public static <T> Maybe<T> maybeOfNullable(T value) {
        return value == null ? Maybe.empty() : Maybe.just(value);
    }
    
    maybeOfNullable(user)
            .map(user -> user.getName())
            .map(name -> convertNameToId(name))
            .flatMap(id -> getStream(id))
            .map(cacheItem -> getUserInfoFromCacheItem(cacheItem))
            // perform another action in case there are no any non null item emitted
            .switchIfEmpty(Maybe.fromAction(() -> showPrompt()))
            .subscribe(userInfo -> showUserInfo());
```

**Comment by justjanne** [comment]
@akarnokd 

> that's why many use Kotlin with RxJava.

And that’s exactly the issue. Kotlin has nice syntax for nullable values, but nothing for optional, nothing for custom NULL objects.

I need to have an observable for the status that a user has set an account name (which can be empty), or not (and this can change at any time). So possible values are no value or any possible string (including empty string).

So now I have to wrap it in Optional, which on Android isn’t even available, so I have to build my own Optional class or import Guava, then I need to wrap every single account value in it.

If you say I’m using the wrong abstraction, please suggest a better solution that has zero allocations more than the String/null case.

**Comment by akarnokd** [comment]
@justjanne You have limit on the account name, right? Have a global static `String` that is longer than the maximum allowed and use it as a null indicator. Later, instead of `if (name == null)` use `if (name == THAT_LONG_STRING_INDICATING_NULL)`.

**Comment by justjanne** [comment]
@akarnokd The string is from a third party system, I have no hard limit on it, nor can I set one.

Currently the only hard limit I set is 65MiB for the string.

And I definitely don't want to carry around a 65MiB value just for verifying this.

**Comment by justjanne** [comment]
And it's not "if (name == null)", it's that all of Kotlin's safety is thrown away.

I can't do name?.doX()?.let {} with your solution.

The compiler can't at compile time verify that I handle the long_string case (but it can for null, as in kotlin, nullable types are completely separate from nonnull types, in this case, String? vs. String)

**Comment by justjanne** [comment]
Basically I might as well cast every piece of data I throw into RxJava into Object (or void* or Any?, you get the idea), because then I'd get just as much compile time safety as I get with RxJava today. Except, well, even for casting types Kotlin has more compile time safety than for your solution.

**Comment by akarnokd** [comment]
@justjanne This is a Java library and as such, it is limited by the properties of the Java language, its type system and the platform. When we wanted to avoid allocation and use the same propagation medium for values, error and completion, we defined the [`NotificationLite`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/util/NotificationLite.java#L26) as the means to retain some type safety.

**Comment by justjanne** [comment]
@akarnokd And yet, RxJava1 handled this much safer than RxJava2 does. With RxJava2 I have to wrap every single call I make to RxJava to get some resemblance of null safety. So the question remains, without wrapping every object I put in RxJava in a wrapper object, how do I retain usability of Kotlin’s null safety operators?

**Comment by JakeWharton** [comment]
We've already sufficiently covered this in this thread and numerous options have been given. You were even involved in those conversations. Why are we need to rehashing this?

 * Wrapper
 * Null object pattern
 * NotificationLite trick

**Comment by justjanne** [comment]
@JakeWharton: And you've proven again that you haven't even read the complaint.

The requirement is still the same: a zero-allocation solution that allows me to use Kotlin's compile time null safety features.

Wrapper and NotificationLite aren't zero allocation, and the Null object pattern does not provide compile time safety (and has already lead to bugs in my code) 

You're insisting on keeping an API that was designed for languages with value types, that only correctly works for languages with value types, even if this breaks the consumers of your API. That's not wise, that's just stubborn.

**Comment by JakeWharton** [comment]
You can't. Move on.

**Comment by justjanne** [comment]
So am I supposed to read this as RxJava2 only being usable for toy projects? Because that’s what this reads like.

**Comment by JakeWharton** [comment]
If you ignore the thousands of production services and apps who use it without this issue rendering the library completely useless, then yes.

**Comment by vanniktech** [comment]
Can we put an end to this discussion and lock this issue?

**Comment by JakeWharton** [comment]
Please noooo I'm so bored working on slides.

Also `NotificationLite` is zero allocation.

**Comment by justjanne** [comment]
> Also NotificationLite is zero allocation.

Interesting, is there public documentation on how to swap it in? I can’t seem to find much about that. In fact, the entire Google search results are going to a few RxJava2 classes (with no documentation either), or to issues of people mentioning it (with no documentation either), or to random websites (also not containing any docs). In fact, Google has exactly 43 search results, and none of them documenting it: https://i.imgur.com/NnGBzDa.png

**Comment by justjanne** [comment]
Also,

> If you ignore the thousands of production services and apps who use it without this issue rendering the library completely useless, then yes.

Most of these are either running on beefy servers, not $60 2010 Android phones, or they’re not handling nearly as much and as reactive data. WhatsApp, Allo, Telegram, etc restrict group sizes to a few hundred people. Yet users on IRC can end up in channels with 8000 (e.g. #ubuntu or #debian on freenode) to 18000 (the osu! bridge) to even larger (Twitch IRC) channels, with many users joining and leaving at the same time, with each user having many reactive properties on them. And a poweruser on WhatsApp may end up in a few dozen channels, a poweruser on IRC will be on in hundreds of them. Personally I’m in 398 channels with combined over 43'000 users with hundreds of them connecting/disconnecting or changing properties at the same time. And if I switch channels on a Moto G 2013, I expect the userlist to have all 8000 users, with all their properties, correctly updated, within of 33ms or less. And I expect every property of every user, of which there are about two dozen, to correctly update in the list. And I expect this to work with less than 20MiB RAM available for the app, on a 600MHz processor, and be fast.

So, no, there’s not that many apps or services in a similar situation. If there are, please link me, I’d like to see how they’ve solved it.

**Comment by JakeWharton** [comment]
`NotificationLite` is just a type safe helper around the null object pattern. Non-null values are kept as-is and null values are replaced with a singleton instance.

It must be fascinating to work on the only non-toy app in existence!

**Comment by justjanne** [comment]
> It must be fascinating to work on the only non-toy app in existence!

Please make constructive comments – as mentioned above, if you know of apps on similarly slow phones processing similarly large sets of data, I’d love to see a link to them, and how they handled the issues with RxJava.

> > NotificationLite is just a type safe helper around the null object pattern. Non-null values are kept as-is and null values are replaced with a singleton instance.

I also don’t see how I get from NotificationLite to an Observable<String?>. As mentioned above as well, I’d love to see any documentation on how to create a clean API with these types, while maintaining the mentioned performance limits.

**Comment by akarnokd** [comment]
It is straightforward to use:

```java
Object o = NotificationLite.next("");
Object o2 = NotificationLite.next("non empty");
Object o3 = NotificationLite.complete();

String s = NotificationLite.isComplete(o) ? null : NotificationLite.getValue(o);
String s2 = NotificationLite.isComplete(o2) ? null : NotificationLite.getValue(o2);
boolean isNull = NotificationLite.isComplete(o3);
```

No allocations, only `instanceof` checks.

You can build your own variant based on it: 
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/util/NotificationLite.java

**Comment by justjanne** [comment]
Sure, but then I'd end up with Observable<Object> right? I'd have to ensure type safety either not at all, or through a compile time annotation processor to verify them.

It seems like the safest and most performant solution is to just go back to what I did before, and write my own half-finished ReactiveX implementation.

It'd be amazing if there would be an implementation of Observable, though, that internally used NotificationLite. Which is what this entire issue seems to have been about.

On 5 April 2018 20:08:49 CEST, David Karnok <notifications@github.com> wrote:
>It is straightforward to use:
>
>```java
>Object o = NotificationLite.next("");
>Object o2 = NotificationLite.next("non empty");
>Object o3 = NotificationLite.complete();
>
>String s = NotificationLite.isComplete(o) ? null :
>NotificationLite.getValue(o);
>String s2 = NotificationLite.isComplete(o2) ? null :
>NotificationLite.getValue(o2);
>boolean isNull = NotificationLite.isComplete(o3);
>```
>
>No allocations, only `instanceof` checks.
>
>You can build your own variant based on it: 
>https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/util/NotificationLite.java
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ReactiveX/RxJava/issues/4644#issuecomment-379026521

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by halfhp** [comment]
> It seems like the safest and most performant solution is to just go back to what I did before, and write my own half-finished ReactiveX implementation.

In that case what would stop you from going back to rx1 instead?

**Comment by justjanne** [comment]
Library support, a lot of libraries that integrated with RxJava now only offer RxJava2 integration, and definitely won't offer integration for my own solution.

An example would be Android's Room.

**Comment by halfhp** [comment]
I dont think your homespun version is going to have better library support than rx1.  There's also an [interop](https://github.com/akarnokd/RxJava2Interop) you can use to bridge the gap and use rx2 libs with your rx1 code.

**Comment by justjanne** [comment]
My homespun solution would be simply reusing the rxjava packe name again, and therefore it'd be possible to get the support that I need.

That's why that's not a great idea — I basically need a zero-allocation solution in the rxjava2 namespace, for which it'd obviously be easiest if rxjava2 would use some other value as sentinel instead of null, e.g. what NotificationLite seems to be designed for (I don't quite see why it's not used internally, though).

**Comment by artem-zinnatullin** [comment]
>I don't quite see why it's not used internally, though

Because no null policy is part of Reactive Streams Specification that RxJava 2 follows. Rule 2.13 https://github.com/reactive-streams/reactive-streams-jvm#2.13

Yes, it's unfortunate

**Comment by justjanne** [comment]
Then make that optional, and allow people to break those rules.

From what I understand these rules never were designed for mobile devices, or other edge cases. They make a lot more sense on the CLR, where value types are available, or on the Hotspot JVM, where parallel generational GCs are available, than on the DalvikVM or ART, where the GC is generally subpar, CPU and memory performance are very limited, and due to network limits, processing data locally is desired.

On 5 April 2018 20:30:58 CEST, "Artem Zinnatullin :slowpoke:" <notifications@github.com> wrote:
>>I don't quite see why it's not used internally, though
>
>Because no null policy is part of Reactive Streams Specification that
>RxJava 2 follows. Rule 2.13
>https://github.com/reactive-streams/reactive-streams-jvm#2.13
>
>Yes, it's unfortunate
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ReactiveX/RxJava/issues/4644#issuecomment-379033540

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by artem-zinnatullin** [comment]
Can you post reproducible benchmarks & profiling results to prove that wrapping significantly slows down your case?

You can compare it with 0-allocation `NotificationLite` pattern to get a baseline.

I also doubt your system has high throughput in all places, most likely it's a few streams that you can migrate to `NotificationLite` and keep others as is.

**Comment by justjanne** [comment]
I’ll try to record within of this week a full trace on the 2011 €60 Huawei Ideos X3 device, with a ROM to bring it to Android 4.0.4. This is a typical device in terms of OS (using a custom cyanogen/lineage build), performance (600MHz single-core ARMv5 CPU), 256MB overall RAM, no JIT, and only a primitive GC.

**Comment by artem-zinnatullin** [comment]
Btw, you might be aware since you're keen on microoptimizations, 
but just in case — Kotlin compiler by default adds null checks on non-null types.

So Kotlin code like this:

```kotlin
fun f(s: String): Int {
    return s.length
}
```

Is equivalent to following Java code:

```java
public final int f(@NotNull String s) {
  Intrinsics.checkParameterIsNotNull(s, "s");
  return s.length();
}

class Intrinsics {
    public static void checkParameterIsNotNull(Object value, String paramName) {
        if (value == null) {
            throwParameterIsNullException(paramName);
        }
    }

    private static void throwParameterIsNullException(String paramName) {
        StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
        StackTraceElement caller = stackTraceElements[3];
        String className = caller.getClassName();
        String methodName = caller.getMethodName();
        IllegalArgumentException exception = new IllegalArgumentException("Parameter specified as non-null is null: method " + className + "." + methodName + ", parameter " + paramName);
        throw (IllegalArgumentException)sanitizeStackTrace(exception);
    }
}
```

So you might want to compile release version of your app with following flags:

```
-Xno-param-assertions
-Xno-call-assertions
```
References: 

- https://discuss.kotlinlang.org/t/run-time-null-checks-and-performance/2086/19
- https://github.com/JetBrains/kotlin/blob/v1.2.40-eap-16/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2JVMCompilerArguments.kt

That can help get part of lost performance due to object wrapping back if you're ***really*** into that.

But I'd strongly recommend to do benchmarking, then profiling, then repeat that couple times and only then make any conclusions.

**Comment by justjanne** [comment]
Thanks, @artem-zinnatullin, but I’ve already done these, as they intrinsic not null checks ended up eating around 5% of performance in a critical callchain, more than any other single component.

Object wrapping, and below that, RxJava2’s internals, now seem to be the next bottleneck

**Comment by artem-zinnatullin** [comment]
Nice, let's get measurements then and discuss that rather fighting with each other's personalities :)

**Comment by mlorenz2** [comment]
Hi,
since we're dealing with nullable's in our Kotlin project as well, we do have also written such an optional wrapper:
```
class OptionalWrapper<out T>(val value: T?)

fun <T> T?.wrapOptional() = OptionalWrapper(this)
```

After reading the whole discussion, I've learned that RxJava2 is just following the reactive streams spec. Well, our iOS team is using RxSwift in their project as well and they can use optionals in streams without problems:
`func getAnyObject() -> Single<AnyObject?>`

Does this mean, that RxSwift does not align on this reactive streams spec and is going to be changed in the near future to fit the spec? If not, why is RxJava2 following the spec then and RxSwift not at all? 

Sorry I know this thread isn't related to RxSwift, but since it is all about nullable's and there's no similar thread in the RxSwift repo I thought it might be ok and I'm just curious to know that..

**Comment by JakeWharton** [comment]
The spec is for the JVM

**Comment by akarnokd** [comment]
RxSwift doesn't follow the Reactive Streams specification and I don't think there exists a port of it yet. In fact none of the other Rx native language derivatives have upgraded to anything RS-like yet.

I've tried to port it and other v2 stuff, but it was extremely tedious. Swift doesn't have the atomics primitives like Java does, I was unable to express certain generics patterns an trying to code without a physical Mac was frustrating to say the least.

**Comment by ilyannn** [comment]
> RxSwift doesn't follow the Reactive Streams specification

Can you provide more info on this topic please?

> Well, our iOS team is using RxSwift in their project as well and they can use optionals in streams without problems

In Swift, `T?` is a syntactic sugar for `Optional<T>`. You can therefore post `nil` as an element to `Single<AnyObject?>`, but not to `Single<AnyObject>`. I believe RxSwift and RxJava work the same as long as you use `Optional`.

**Comment by akarnokd** [comment]
[This](https://github.com/reactive-streams/reactive-streams-swift) is supposed to be the standard for Swift, but its empty. [This is what I cobbled together](https://github.com/akarnokd/akarnokd-misc-swift/blob/master/SwiftExperiments/ReactiveStreams.swift) as a spec. [Here](https://github.com/nebhale/reactive-streams-swift) is another one. [This](https://github.com/reactive-streams/reactive-streams-jvm/issues/391) was a short discussion about it again.

However, the RxSwift developers are [not interested in backpressure](https://github.com/ReactiveX/RxSwift/issues/1376) so that's also a hindrance for adapting RS. Plus, it requires a significant architecture change and rewriting most of the internals.

**Comment by blainepwnz** [comment]
I am using this extension function to solve this problem, works fine for my case(map entities from database and ignore all null users)
If there is a need - some code can be executed with observable.empty to do some business logic on null item.
```
fun <U, D> Observable<U>.notNullMap(mapFunc: (U) -> D?): Observable<D> = flatMap {
    mapFunc(it)?.let { Observable.just(it) } ?: Observable.empty()
}
```
