### ISSUE TITLE
2.x Proposal: Valueless Flowables

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4652]
@akarnokd we talked about this in the comments of your blog once some time back after `Completable` was released, and wanted to revisit this. Feel free to close if you think it's not worth discussing.

**Context:** Often times in development, I've wanted effectively an `Action0`-esque API, where notifications are sent to trigger something but no values are actually sent since they don't matter. A good example of this in Android development is listening for clicks. Currently, the only way to implement this is to basically make a Flowable of type `Void`, which still required sending `null` (in `Observables`) or some object (required now for 2.x) through to trigger it. @JakeWharton's RxBinding is a good example of this in action, as it uses this pattern a [fair bit](https://github.com/JakeWharton/RxBinding/search?utf8=%E2%9C%93&q=Observable.OnSubscribe%3CVoid%3E&type=Code) (tried to filter the search, best effort since github ignores brackets).

It would be great if something like this could fit in RxJava 2.x, and figured I'd bring it up again since seeing another new type (`Maybe`) added since we talked. I understand if not though, especially considering it does add a nontrivial amount of API surface area.

**Comment by akarnokd** [comment]
This was brought up many times now. You should just send an ignorable value type through the `Flowable` as `Void` requires `null` which is now forbidden. There is an example on the [wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls) about this. When designing, you may go for `Flowable<Object>`.

**Comment by ZacSweers** [comment]
Ah cool, that wiki is good to see. In that case I'll go ahead and close this!

**Comment by abersnaze** [comment]
Another example of this is the timer source Observable. It could have been a valueless Observable but we opted to return a counter in case someone wanted to map to something.

**Comment by ZacSweers** [comment]
To revisit this one last time: What would you think about adding that `Irrelevant` enum example to RxJava 2 itself? Considering I imagine this will be used a lot, it would be nice to have a standard usage for this that libraries and projects in general can share. Otherwise I could see fragmentation around this between different libraries. Would also allow for shared use of the same data type without having to transform to something else used in your project.

**Comment by akarnokd** [comment]
Still no. But since this affects Android developers the most, why not add it to RxAndroid 2? Or better yet, roll your own library?

**Comment by ZacSweers** [comment]
@JakeWharton thoughts?

**Comment by JakeWharton** [comment]
I'm not eager about a type in either RxJava or RxAndroid's public API for this.

**Comment by dlew** [comment]
Some musing:

I don't know about the fragmentation argument. If we add `Irrelevant` there is no reason that libraries have to use it. They could just keep using `Observable<Object>`, thus introducing fragmentation.

Plus, if you wrote a mapping function that takes in an irrelevant type and outputs a String, would it make more sense for it to be `Irrelevant -> String` or `Object -> String`? The latter would be more generally usable, since it just indicates it doesn't care about the input (not that it cares that the input itself is irrelevant). As such library probably wouldn't use `Irrelevant -> T` anywhere.

On the other hand, it is nice to be able to signal to consumers that the type being sent has no meaning.

**Comment by ZacSweers** [comment]
I don't think mapping things to String helps here, the whole point is that you have something in the type system to indicate its irrelevancy while limiting the instance you can pass (so people don't send, say, `new Object()` or optimize around sharing some singleton). 

In our project alone, we're looking now at:
- RxBinding APIs presumably sending its own `Irrelevant`
- Our own `Irrelevant` for internal things
- A couple other libraries we use that presumably will start this as well.

So this already has us facing potentially 4 different types of `Irrelevant`. Before it wasn't an issue since `Void` could be passed, but with RxJava 2 not accepting nulls we're back to `Object` or some `Irrelevant` pattern as discussed here.  

I think this is a good chance to standardize a convention around it. Sure, libraries don't have to use it, but it would certainly help. I don't think value-less notification usages are as rare as some might think, and could actually be useful for some of RxJava's internals as well (such as `repeatWhen()` or `retryWhen()`, which I think kind of exemplify my point about consistency since they have different implementations of their `notificationHandler` that take the forms mentioned above).

**Comment by JakeWharton** [comment]
I think you missed the point of Dan's example. It was that these irrelevant types are just that: irrelevant. So it actually doesn't matter if you use an `Irrelevant` or Kotlin's `Unit` or `Object`.

**Comment by dlew** [comment]
Yes, that was exactly my point. Using `Irrelevant` does not actually provide actionable information for anything downstream, since anyone consuming an irrelevant type means the type itself is irrelevant.

The only advantage I see to having an `Irrelevant` type is having a way to indicate (to developers) that the actual instance being passed means nothing. Thinking on it further, I think that is probably achieved well enough with `Observable<Object>`, since an `Object` doesn't really have a purpose either.

**Comment by ZacSweers** [comment]
I understood that. My point is that it's still leaving a fragmented system of different "Irrelevant" conventions, or lack thereof.

``` java
Observable.just(IrrelevantEnum.INSTANCE)

Observable.just(new Object())

Observable.just(SOME_OBJECT_SINGLETON)

Observable.just(new Irrelevant())

// and so on
```

I guess just going with `Object` is fine, but kind of a step back from the explicitness that `Void` sort of offered.
