### ISSUE TITLE
Primitive Specilisation of API

### ISSUE THREAD

**Issue by sirinath** [ReactiveX/RxJava#4850]
For latency, GC and memory efficiency is it possible to add primitive specialised equivalents?

**Comment by akarnokd** [comment]
It's too much work for too little benefit; most users don't send millions of integers through a sequence plus we'd multiply the library size by 2x-4x. Bottom line, it is possible but we won't do it.

**Comment by sp-1234** [comment]
Why not do it in a separate optional add-on library? Then those who don't need it won't have any additional problems at all.
Also not all types are needed, I think (int, long, float, double) are enough for all practical cases. Then there are 4*4 = 16 permutations for primitive->primitive mapping functions, that's not too bad.

> most users don't send millions of integers through a sequence

Well, they don't do this because currently it's impossible to do efficiently.

Also how hard do you think it is? Maybe I'll even take the challenge.

**Comment by sp-1234** [comment]
Also how hard do you think it is? Maybe I'll even take the challenge.

**Comment by akarnokd** [comment]
Don't forget the Object->Primitive and Primitive->Object conversions, like `map((int i) -> Integer.toString(i))`.

Nobody is working on this and this won't be part of RxJava for the forseeable future. Also it depends on how Project Panama gets into the JDK eventually.

> Also how hard do you think it is? 

You lose `null` as a not-available indicator inside operators. This has cascading concurrency effects such as the need for a new Queue API, solving the problem of atomically changing a primitive + an empty indicator token, etc. At the end, you'll likely end up wrapping the primitives anyway and you gained almost nothing.

**Comment by sp-1234** [comment]
> Don't forget the Object->Primitive and Primitive->Object conversions, like map((int i) -> Integer.toString(i)).

There are little permutations (4), because all reference types are the same in this regard, that's nothing compared to 4*4 primitive permutations

>Also it depends on how Project Panama gets into the JDK eventually.

Yeah that's true, but it won't make its way into existing Android versions (if at all).

> You lose null as a not-available indicator inside operators.

This is a painful one, but maybe API could be extended for primitive versions so that user will explicitly choose an "impossible" value which is treated like null, when defining source of the data.
Lots of cases which work with only non-negative values or use ints for booleans/bytes are easy then. Also floating point types have NaN. Etc.

> solving the problem of atomically changing a primitive

AFAIK it's possible to do with sun.misc.Unsafe, which is exactly the backend behind AtomicLong class.

> At the end, you'll likely end up wrapping the primitives anyway and you gained almost nothing.

Given the above points, maybe it's not so likely?

**Comment by akarnokd** [comment]
If you are so convinced then go ahead and try it in your own repo.
