### ISSUE TITLE
OperatorObserveOn use  Queue-drain is Unnecessary?

### ISSUE THREAD

**Issue by chuyun923** [ReactiveX/RxJava#4886]
OperatorObserveOn is used to change thread for Subscriber to execute `onNext()` `onCompleted()` `onError()` ,In order to emits values  in a sequential way,OperatorObserveOn use Queue-drain in`ObserveOnSubscriber.schedule()` 

       protected void schedule() {
            if (counter.getAndIncrement() == 0) {   //restrict only one thread access
                recursiveScheduler.schedule(action);
            }
        }

**BUT recursiveScheduler is a Worker**,from Worker's DOC:

> Sequential Scheduler for executing actions on a single thread or event loop.

So,In OperatorObserveOn,without consider backpressure,we can just schedule action by `Worker ` directly,just like:

        @Override
        public void onNext(final T t) {
	      recursiveScheduler.schedule(new Action0() {

            @Override
            public void call() {
                child.onNext(t);
            }

        });
       }

Is there any problem？

**Comment by akarnokd** [comment]
The queue-drain gives much better performance because scheduling individual elements costs 1 allocation and a somewhat costly scheduling of the task itself. By queue drain, there is only an atomic increment followed by a scheduling of a `this` occasionally and the two sides of the queue communicate very efficiently if the supply of items is fast enough.

**Comment by chuyun923** [comment]
Thank you.
