### ISSUE TITLE
EventLoopsScheduler creates 4 event loops on 8-core machines

### ISSUE THREAD

**Issue by nmarasoiu** [ReactiveX/RxJava#4958]
Currently, the number of event loops RxJava 1.x (both 1.1.2 and 1.x current branch) starts by default on 8-core machines is 4 event loops: in RxJava/src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, Runtime.getRuntime().availableProcessors() is used if no system property is given, but this is half the cores for many machines. It would be better to have twice that even if on some machines it would be 2 threads interleaved than the current underutilization. I can create a pull request to multiply Runtime.getRuntime().availableProcessors()*2

**Comment by akarnokd** [comment]
Don't. `availableProcessors()` determines the number of threads in the `computation()` scheduler, which is supposed to return the number of CPU threads in your system. I have an i7 4790 which has 4 cores, 8 hyperthreads and `availableProcessors()` returns 8 on Windows 7 as expected. What is your environment? CPU, OS, Java version.

**Comment by akarnokd** [comment]
In addition, [this code](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/schedulers/EventLoopsScheduler.java#L38) limits the number of workers to the available CPU count: if your system reports 4 cores and you set `rx.scheduler.max-computation-threads=8` you'll still get 4 workers.

You may mistake it with a helper pool for delayed execution of `Schedulers.from` tasks [which does limit its pool size to 4](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/schedulers/GenericScheduledExecutorService.java#L58) but this is not usually a performance penalty since these pools only wait for the delay and don't execute any user task directly; they delegate back to the original Scheduler.

**Comment by nmarasoiu** [comment]
indeed
