### ISSUE TITLE
Question about reactive streams contract fulfillment of 2.x

### ISSUE THREAD

**Issue by rrevol** [ReactiveX/RxJava#4959]
I was reading the code of the FlowableZip when I saw something that seams to be in contradiction with the rule 3 of Subscriber (see [specs](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.0/README.md#specification) ) :

- the ZipSubscriber may call the drain() method of the ZipCoordinator when its onError or onComplete methods are called.
- when in the drain, it looks like the cancellAll() method will be called because of the onError/onComplete status of the inner subscriber.
- thus onError and onComplete may lead to a call to cancel() on the subscription, breaking the rule 3

Am I missing something here ? If not, is it on purpose that some rules of reactive streams are broken and is there a list of them with the reason why ?

**Comment by akarnokd** [comment]
Rule §2.4 says the `Subscription` should be considered cancelled and §3.6 + §3.7 a cancelled `Subscription` should ignore `request` and `cancel`.

Rule §2.3 is probably unnecessary due to the above. Plus if followed to the letter, it would be impossible for example, to retry a `Publisher` because an `Publisher.subscribe()` call from an `onError` would be disallowed.

Before this, there were [2 rules ignored](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#reactive-streams-compliance) from the specification.

Note that the RS spec was developed before any **native** library was developed with it and it still contains such problematic rules due to lack of experience at the time (I'd say some rules exist because how Typesafe/Lightbend implemented their wrapper for Akka-Stream the time.)

Why do you worry about this?

**Comment by rrevol** [comment]
Thanks for your answer.

It's true that the set of rules may not be canonical yet. I should have taken a closer look at them.

> Why do you worry about this?

I was working on a custom operator performing  a merge join between its sources and inspired from the FlowableZip. I was trying to solve a bug where a source was not unsubscribed on the termination of the other source, which should be done for inner joins. My problem has actually been solved by this [commit](https://github.com/ReactiveX/RxJava/pull/4761/commits/af12018df772249355ae53431bdfa46432af2cb8#diff-1d9d35ef81bdb97ab17427e67066bbac). Anyway, it happened to me that calling cancelAll would re-cancel one of the subscriptions, and I took a look at the spec to see whether it would be a problem.

**Comment by akarnokd** [comment]
2.0.5 will have a new operator `Flowable.strict()` that follows the RS spec to the letter no matter the performance cost.
