### ISSUE TITLE
2.x: Should schedulers have RxThreadFactory constructor parameters?

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveX/RxJava#4993]
RxJava 1 allowed for specifying a custom thread factory, but it looks like this feature did not make it to RxJava 2. Was this intentional or something that a PR would be welcome for?

**Comment by akarnokd** [comment]
Which scheduler? Computation? It was intentional. You can now configure the priority of each scheduler so there was little benefit from a customizing the factory. Use the [ParallelScheduler](https://github.com/akarnokd/RxJava2Extensions#parallelscheduler) from extensions which allows more [customization](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/schedulers/ParallelScheduler.java#L87).

**Comment by ZacSweers** [comment]
We used it for the IO scheduler as well. It was useful for tracking our own thread naming and setting their priority to android-specific priorities. We'd like to use it for that and SingleScheduler. Can ParallelScheduler be used as a substitute for non-computation schedulers too?

**Comment by akarnokd** [comment]
Since scheduler implementations are internal, it is not recommended anyway to use them directly.

ParallelScheduler is an individual scheduler with a specified number of threads that doesn't change over time. So unlike io(), ParallelScheduler won't stop its threads when they become idle for too long.

**Comment by ZacSweers** [comment]
> Since scheduler implementations are internal, it is not recommended anyway to use them directly.

I'm not sure I follow. As in we shouldn't create a new IoScheduler instance?

**Comment by ZacSweers** [comment]
Prior discussions/work for reference - #3724 #3879

**Comment by akarnokd** [comment]
Anything in the `io.reactivex.internal.*` is considered private and not part of any binary or API compatibility contracts.

**Comment by akarnokd** [comment]
So either use `Schedulers.from(Executor)` with your own pool or copy the internal code and change it locally.

**Comment by ZacSweers** [comment]
I missed that they were internal now. That's disappointing to see, and seems like a bit of a step backward compared to RxJava 1. We'll just copy then :|

**Comment by JakeWharton** [comment]
They're internal in 1.x too. The only remnants are public for binary
compatibility that no one should be using anyway. Are you referring to the
factory methods? Those could easily be replicated on 2.x.

**Comment by ZacSweers** [comment]
Yeah I was referring to the factory methods. Basically wanted to do the same thing you added in the linked PR above

**Comment by ZacSweers** [comment]
> Those could easily be replicated on 2.x.

@akarnokd any thoughts on this? This is what I was thinking of in opening this issue, in case I wasn't clear before

**Comment by akarnokd** [comment]
They will be still internal classes. However, we could expose them, for example, `Schedulers.newComputation()`, `Schedulers.newIO()` etc where extra parameters can be passed in, similar to how Project Reactor's schedulers were exposed.

**Comment by ZacSweers** [comment]
That sounds reasonable to me.[ The APIs they expose cover pretty much everything we'd want](https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/scheduler/Schedulers.java), would be happy to make a PR matching those if you're up for it.

**Comment by akarnokd** [comment]
Sure.
