### ISSUE TITLE
rxjava2-extras review request

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#4997]
Many operators have been migrated from [*rxjava-extras*](https://github.com/davidmoten/rxjava-extras) to [*rxjava2-extras*](https://github.com/davidmoten/rxjava2-extras) to use RxJava 2. 

I'd appreciate a review of the `master` branch from anyone interested to look at it.

A major enhancement is a rewrite of [`onBackpressureBufferToFile`](https://github.com/davidmoten/rxjava2-extras/blob/master/README.md#onbackpressurebuffertofile) which now uses fixed-size memory-mapped files and uses concurrency tricks from [Aeron](https://github.com/real-logic/Aeron).

Operators are documented (with marble diagrams) [here](https://github.com/davidmoten/rxjava2-extras/blob/master/README.md).

Many thanks.
Dave

**Comment by akarnokd** [comment]
Generally, some parameter validation is missing. I saw some internal implementations doing it in the constructor but not others.

### [reverse()](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableReverse.java)

  - You can use `flatMapIterable`.

### [mapLast()](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableMapLast.java)

  - The purpose of this operator is unclear to me. 
  - `onError` doesn't map the last value unlike `onComplete` which may or may not be intended.

### [match()](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableMapLast.java)

  - If you don't need the input flowables, there is no need to store them in the coordinator but hand them to the [subscribe()](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableMatch.java#L108) method. 
  - Also the same method doesn't use the `child` parameter.
  - `public final class FlowableMatch`
  - emitted should be `long` @ [L145](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableMatch.java#L145)
  - it is recommended one clears the queue to avoid GC nepotism @ [L148](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableMatch.java#L148)
  - unnecessary as the while loop will quit anyway @ [L190](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableMatch.java#L190)

### [repeat](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableRepeat.java)

  - See [FlowableRepeatScalar](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/operators/FlowableRepeatScalar.java) for the unlimited case.

### [StringSplitSimple](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableStringSplitSimple.java)

  - `unbounded` should be set before requesting @ [L76](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableStringSplitSimple.java#L76)
  - There is no need to queue notifications, they can go into simple fields and checked before polling for items @ [L93](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableStringSplitSimple.java#L93)
  - clear the queue @ [L112](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableStringSplitSimple.java#L112)

### [split()](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/TransformerStringSplit.java)

  - See [FlowableSplit](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/string/FlowableSplit.java).

### [BackpressureToFile](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/buffertofile/FlowableOnBackpressureBufferToFile.java)

  - Must check `isDone` before `error != null` because if isDone == true, error definitely does or doesn't contain an error @ [L256](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/buffertofile/FlowableOnBackpressureBufferToFile.java#L256). Otherwise if isDone is false and error is about to get assigned, you may see a half constructed error.
  - You may want to scope the exception handler to cover the absolute necessary and doesn't capture other failures from onNext, etc. @ [L278](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/buffertofile/FlowableOnBackpressureBufferToFile.java#L278)

**Comment by davidmoten** [comment]
You are a legend @akarnokd. Thanks very much!

**Comment by akarnokd** [comment]
You are welcome.
