### ISSUE TITLE
tryOnNext design

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#5038]
I have written an operator in *rxjava2-extras* called [`collectWhile`](https://github.com/davidmoten/rxjava2-extras#collectwhile). I'd appreciate a review for any glaring problems especially as this is my first foray into supporting an aspect of operator fusion, namely *request-one* micro-fusion. Source for the operator is [here](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableCollectWhile.java).

By the way I'm happy with how the RxJava 2 api hangs together for writing operators. Super job.

I'm a bit curious about `tryOnNext`. When something happens for that method to call `onError` and terminate it's unclear what I should return. I assume it's actually more performant to encourage another loop of a `while (e!=r)` loop upstream by returning false from `tryOnNext` so that we encounter the `cancelled` check straight away instead of possibly (if `e==r`) hitting the atomics `requested` and `this` outside the inner loop and then doing the `cancelled` check.

Perhaps the `tryOnNext` method could return an enum with values like `EMITTED`,`NOT_EMITTED`,`CANCELLED` and the `onNext` method would look like 

```java
if (tryOnNext(t) == NOT_EMITTED) {
    parent.request(1);
}
```

The upstream drain loop might avoid a `cancelled` check by doing:

```java
Result result = child.tryOnNext(t);
if (result == Result.EMITTED) {
    e++;
} else if (result == Result.CANCELLED) {
  return;
}
```
I'm not wedded to those names of course, they are just so you get the idea.

Do you see any advantages to changes like these?

**Comment by akarnokd** [comment]
> When something happens for that method to call onError and terminate it's unclear what I should return. I assume it's actually more performant to encourage another loop of a while (e!=r) loop upstream by returning false from tryOnNext so that we encounter the cancelled check straight away instead of possibly (if e==r) hitting the atomics requested and this outside the inner loop and then doing the cancelled check.

Doesn't matter, both works because request amount updates are done after the e == r checks anyway and besides, there is only some chance you hit a request boundary while doing this.

> Perhaps the tryOnNext method could return an enum with values 

Fusion was designed to have a low impact as possible, one boolean branch prediction is better than two.

> I'd appreciate a review for any glaring problems

[L162](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableCollectWhile.java#L162): you conditionally offer to the queue **after** indicating you are done. This may lose the very last collection because a typical drain will find `done && queue.isEmpty()`. You should set done just before `drain`.

[L188](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableCollectWhile.java#L188): checking `done` after a `poll()` may leave unconsumed collections if they appear between the two,  always read `done` first into a local variable, check ˙poll`/`isEmpty`.

[L195](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableCollectWhile.java#L195): Not a problem but you can have one `return` after the `if` since both paths quit.

[L209](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableCollectWhile.java#L209): the case for `if (e == r)` is missing here; it covers the case when the upstream ends on a request boundary and can emit an `onComplete()` without the need to request more.

[L224](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableCollectWhile.java#L224): I don't think you need queue-drain here at all. You can have it flat and whenever you don't emit a collection in `tryOnNext`, just return false indicating the upstream should produce another value. See [FlowableBufferPredicate](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/operators/FlowableBufferPredicate.java#L134).

**Comment by davidmoten** [comment]
>L162: you conditionally offer to the queue after indicating you are done. This may lose the very last collection because a typical drain will find done && queue.isEmpty(). You should set done just before drain.

Thanks, yep

>L188: checking done after a poll() may leave unconsumed collections if they appear between the two, always read done first into a local variable, check ˙poll/isEmpty`.

Ta

>L209: the case for if (e == r) is missing here; it covers the case when the upstream ends on a request boundary and can emit an onComplete() without the need to request more.

Yep, that would be nice to have, I was lazy.

>L224: I don't think you need queue-drain here at all. You can have it flat and whenever you don't emit a collection in tryOnNext, just return false indicating the upstream should produce another value. See FlowableBufferPredicate.

Yep I thought the queue drain was overkill, just being lazy.

Thanks for the review (I need to be a bit more careful! I'll check other operators for similar probs).

**Comment by davidmoten** [comment]
Other operators were fine, these were lessons learnt previously. I was just hasty. Thanks again, closing.
