### ISSUE TITLE
Is it necessary to dispose DisposableSingleObserver explicitly ?

### ISSUE THREAD

**Issue by zahid-mt** [ReactiveX/RxJava#5040]
Is it necessary to dispose DisposableSingleObserver explicitly ?

```
final DisposableSingleObserver<? super SoapObject> myDisposableSingleObserver
            = new DisposableSingleObserver<SoapObject>(){
        @Override
        public void onSuccess (SoapObject response){
            //My logic here
        }

        @Override
        public void onError (Throwable error){
            Log.e(TAG, "Error:" + error.getMessage());
        }
    };
```
For Example If I exit from Android activity; Will RxJava dispose myDisposableSingleObserver implicitly or I have to call
```
if (myDisposableSingleObserver.isDisposed()) {
     myDisposableSingleObserver.dispose();
}
```

I am using v2.0.5

**Comment by akarnokd** [comment]
If the execution gets to `onSuccess` or `onError`, the upstream is to be considered disposed and all resources freed (before or just after your code returns from the onXXX method). 

There is no need to call `dispose` on `DisposableSingleObserver` and has likely no effect because some operators disconnect the internal link of `Disposable`s thus a `dispose` may never reach a `doOnDispose()` operator.

To make sure your resource is released no matter what, use `using` and/or `doFinally`.
