### ISSUE TITLE
Unittest with Mockito

### ISSUE THREAD

**Issue by jedsada-gh** [ReactiveX/RxJava#5096]
Hi, i cannot run unittest because error (subscribeOn(Schedulers.io() is null on logcat) why?

compile "io.reactivex.rxjava2:rxandroid:$rxAndroidVersion"
compile "io.reactivex.rxjava2:rxjava:$rxVersion" 

rxVersion = "2.0.5"
rxAndroidVersion = "2.0.1"

**Comment by artem-zinnatullin** [comment]
Most likely because you're using schedulers from RxAndroid which require
Android Framework implementation at runtime while you're running unit tests
with stubbed (by Android Gradle Plugin) Android Framework classes.

One way to solve this is to replace RxAndroid schedulers with regular ones
during the tests, another is to use Robolectric and another is to run tests
on actual Android OS.

**Comment by jedsada-gh** [comment]
Thank.

**Comment by jedsada-gh** [comment]
https://gist.github.com/T-Jedsada/236cbe632c3629f314a5a71fe4051b60

result i used Robolectric your can help me?

**Comment by artem-zinnatullin** [comment]
I haven't use Robolectric for awhile so I'm not very helpful with setting
it up.

It looks like you will need to replace io scheduler with trampoline() or
immediate() anyway, so I would recommend to change schedulers for tests and
you won't need Robolectric. There are tons of articles about testing RxJava
code that you may find helpful, I'm writing from phone, so I'd leave
googling for you :)

**Comment by jedsada-gh** [comment]
Yeah! Thank brother

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
