### ISSUE TITLE
2.x: BehaviorSubject lastElement/lastOrError don't invoke onSuccess/onComplete/onError

### ISSUE THREAD

**Issue by Maragues** [ReactiveX/RxJava#5131]
RxJava version: 2.0.6

Using BehaviorSubject

- [lastElement](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#lastElement()) returns Maybe but doesn't invoke onSuccess or onComplete
- [lastOrError](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#lastOrError()) returns Single but doesn't throw NoSuchElementException when empty or invoke onSuccess when it has content

All tests fail on the last line

```
@Test
public void lastOrError() {
  Observable.empty().lastOrError().test().assertFailure(NoSuchElementException.class);
  BehaviorSubject.create().lastOrError().test().assertFailure(NoSuchElementException.class);
}
//java.lang.AssertionError: No errors (latch = 1, values = 0, errors = 0, completions = 0)

@Test
public void lastElement() {
  Observable.empty().lastElement().test().assertComplete();
  BehaviorSubject.create().lastElement().test().assertComplete(); 
}
//java.lang.AssertionError: Not completed (latch = 1, values = 0, errors = 0, completions = 0)

@Test
public void lastOrError_withContent() {
  Observable.just(1).lastOrError().test().assertValue(1);
  BehaviorSubject.createDefault(1).test().assertValue(1);
  BehaviorSubject.createDefault(1).lastOrError().test().assertValue(1);
}
//java.lang.AssertionError: Expected: 1 (class: Integer), Actual: [] (latch = 1, values = 0, errors = 0, completions = 0)

@Test
public void lastElement_withContent() {
  Observable.just(1).lastElement().test().assertValue(1).assertComplete();
  BehaviorSubject.createDefault(1).test().assertValue(1);
  BehaviorSubject.createDefault(1).lastElement().test().assertValue(1).assertComplete();
}
//java.lang.AssertionError: Expected: 1 (class: Integer), Actual: [] (latch = 1, values = 0, errors = 0, completions = 0)
```

System

OS: macOS 10.12.3
IDE: Android Studio 2.3 Beta 4
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by akarnokd** [comment]
You need the source to complete to get the last of the sequence - otherwise how would you identifiy the last element? It is the element just before the call to `onComplete()`.

You may confuse `lastX` with a some kind of latest operator which peeks into a hot source and gets you a single value out of it. For this purpose, `BehaviorSubject` offers the [`getValue()`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/BehaviorSubject.html#getValue()) method you can use imperatively to get to the latest element. Turning it into a dynamic `Maybe` or `Single` is just a matter of composition:

```java
BehaviorSubject<Integer> bs = ...

Maybe<Integer> latestMaybe = Maybe.fromCallable(() -> bs.getValue());

Single<Integer> lastestSingle = Single.fromCallable(() -> bs.getValue());
```

whenever you subscribe to these latter and the `BehaviorSubject` changes, you get the latest value out.

**Comment by Maragues** [comment]
I see, thanks.

Would it make sense to add that to *BehaviorSubject* documentation? Since it inherits from *Observable*, reading the docs makes you feel like you can use the latter methods and the output won't change. In my case, I was returning an Observable through *distinctUntilChanged* and none of *lastElement* or *lastOrError* work because it's an *ObservableDistinctUntilChanged*, but again I felt as it should be working.

If I had the knowledge I wouldn't mind working on the documentation PR myself, but I'm far from feeling confident enough to write them.

Thanks for your time!

**Comment by akarnokd** [comment]
I'd consider this as a material for a blog post rather than a documentation change. In this case, you may be in a better position of explaining the path to getting to the bottom of your original issue.

Generally, the topic of how operators interact with each other can become quite long and most of those interactions can be inferred from first principles like the Observable contract. 

There were cases, such as `zip`, where a particular interaction is so commonly misunderstood or mis-expected that we [extended](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Flowable.java#L4144) the docs. I don't feel such problem in this case though.
