### ISSUE TITLE
UndeliverableException wraps retrofit2.adapter.rxjava2.HttpException

### ISSUE THREAD

**Issue by francorolando** [ReactiveX/RxJava#5227]
at work we upgraded to RXJava 2.0.6, we are confused why a retrofit2.adapter.rxjava2.HttpException gets wrapped into an UndeliverableException, does anybody see the same issue or can anybody shed a light on why that is happening? Thanks.

**Comment by ScottPierce** [comment]
I work with @francorolando . Let me elaborate a little bit. Our app is unexpectedly crashing when we don't set an `RxJavaPlugins` error handler. An `UndeliverableException` ends up crashing the app. If we set an error handler, then the app doesn't crash, and the exception is able to be delivered to the subscriber just fine.

Is this expected behavior?

**Comment by akarnokd** [comment]
Yes, since 2.0.6, many undeliverable exceptions get wrapped into `UdeliverableException`. The [release log](https://github.com/ReactiveX/RxJava/releases/tag/v2.0.6) explains it and there is a recent update to [the wiki](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) as well.

**Comment by francorolando** [comment]
thanks.
