### ISSUE TITLE
2.x Single unsubscribeOn missing

### ISSUE THREAD

**Issue by I60R** [ReactiveX/RxJava#5300]
Also, in order to match 2.x naming convertions that operator should be named `disposeOn`

**Comment by akarnokd** [comment]
Indeed that operator is missing from `Single` and available on the other types. Would you like to convert closest `MaybeUnsubscribeOn` over to it in a PR?

It is called `unsubscribeOn` for historical reasons and 
- to pair up with `subscribeOn`
- to have the same name across the types instead of `disposeOn` and `cancelOn`.

`unsubscribeOn` is the name of (concept of) the operation whereas `doOnCancel` and `doOnDispose` represent the signal types and appropriate method names within the API and as such were adjusted.

**Comment by I60R** [comment]
Thanks for fast feedback and explanation.

About PR: yes, I can do it.
However, I'm not too experienced programmer and can't promise anything about code quality and time

**Comment by akarnokd** [comment]
Oh, I understand. A certain code quality is expected here, plus RxJava 2.0.9 is scheduled to be released tomorrow. I'll do the PR then in a few hours.

**Comment by I60R** [comment]
Looks not too complicated. Can you give me 2-3 hours?

**Comment by akarnokd** [comment]
I've done it. For exercise, see if you can do it yourself and compare it against #5302 to verify your approach.

**Comment by I60R** [comment]
Done it same way, but without testing (oh, it's hardest thing to prove that my code works as expected)
