### ISSUE TITLE
2.x Schedulers.io() reuses blocked threads

### ISSUE THREAD

**Issue by irgendeinich** [ReactiveX/RxJava#5346]
RxJava 2.1.0

I think this bug has resurfaced https://github.com/ReactiveX/RxJava/issues/4230.

I wrote a small code sample that illustrates the issue.
```
var running = true
for (i in 1..10) {
    val subscription = Completable.fromAction {
        println("Running")
        while (running) {
            //This Completable just does its thing, ignoring any interrupts.
        }
        println("Finished running")
    }.subscribeOn(Schedulers.io()).subscribe()
    // Wait so the Completable actually starts running.
    Thread.sleep(1)
    // Dispose so the scheduler thinks the thread is available again.
    // If we don't dispose the scheduler will correctly create new threads.
    subscription.dispose()
}

// This Completable waits on the other task instead of getting a new thread.
Completable.fromAction {
    println("Did my thing")
}.subscribeOn(Schedulers.io()).subscribe()
Thread.sleep(10000)
// As soon as the already disposed jobs finish, the waiting task executes.
running = false
Thread.sleep(100)
```

**Comment by akarnokd** [comment]
This has been due to the changes in [this](https://github.com/ReactiveX/RxJava/commit/7d09e458bec4e343a3d73bd665d484eadb36b987) commit.

There is a tradeoff between not getting blocked and not leaking threads with IO scheduler. I think there was an issue at the time about getting leaks because of blocked IO workers. The suggestion is to use `newThread` for this type of sources while using `io` for the well behaving ones.

**Comment by irgendeinich** [comment]
OK, that sounds reasonable.
Thanks for the very quick answer. 👍
