### ISSUE TITLE
2.x toList should accept 0 as the capacityHint

### ISSUE THREAD

**Issue by ansman** [ReactiveX/RxJava#5361]
In my opinion this should be allowed:
```java
someObservable
  .toList(0);
```

The code that produced the error initially looked like this:
```java
someObservable.flatMapSingleElement(items -> Observable.fromIterable(items)
  .filter(SomeItem::somePredicate)
  .toList(items.size()));
```

**Comment by akarnokd** [comment]
No. Any decent Java version will not preallocate the internal array of `ArrayList` until it actually receives an item, thus having a minimum of 1 causes no allocation. Plus, since you want to size the result list based on the original list `items` already available inside a `flatMap`, you are free to branch on `items.size()` in the lambda and return a `Single` prepared with an empty array list of the capacity of your chosing.

**Comment by ansman** [comment]
The reason why I'm suggesting this is not due to performance issues but rather ease of writing. I feel like with the current javadoc it should be fine to say that you're expecting 0 items. But perhaps the javadoc should be updated then?

**Comment by ansman** [comment]
Out of curiousity, why shouldn't 0 be allowed as the default capacity?

**Comment by ansman** [comment]
Oh, and Android's `ArrayList` does allocate eagerly.

**Comment by akarnokd** [comment]
You can post a PR that adds the `, positive` to all the operators' parameter javadoc: `toList`, `toSortedList` and `sorted` in both `Observable` and `Flowable`.

> Out of curiousity, why shouldn't 0 be allowed as the default capacity?

Because expecting zero elements is an indication the flow needs redesign.

**Comment by ansman** [comment]
Sure, it would be more efficient to use `Observable.just(new List<SomeItem>())` but it would make the code more verbose.

**Comment by akarnokd** [comment]
I assume your target platform is Android thus you can now use Kotlin with its extension methods to define a custom operator for yourself.
