### ISSUE TITLE
RxJava 2.1.0 SerialDisposable#isDisposed() return false for Disposables#disposed() initial value

### ISSUE THREAD

**Issue by bejibx** [ReactiveX/RxJava#5392]
Consider following code:
```java
SerialDisposable disposable = new SerialDisposable(Disposables.disposed());
if (disposable.isDisposed()) {
   // do somesing
}
```
I wanted to set my initial value to be disposed and thought ```isDispossed()``` will return ```true``` for ```Disposable``` returned from ```Disposables.disposed()```, but it actually returns ```false```. Find out thats because ```SerialDisposable#isDisposed()``` just check if current ```Disposable``` equals to ```DisposableHelper#DISPOSED```, which is weird. So to fix this I have to go with this:
```java
SerialDisposable disposable = new SerialDisposable(DisposableHelper.DISPOSED);
if (disposable.isDisposed()) {
   // do somesing
}
```
Is this intended behavior? If so, can you please explicitly indicate this in the documentation?

**Comment by akarnokd** [comment]
> Is this intended behavior?

Yes. The containers don't care of the actual state of what they contain and if they did, that would disrupt the state of the system. For example, if a Disposable in the CompositeDisposable container is disposed, should the the CompositeDisposable report itself as disposed despite all other content not being disposed? Also containers act as a deferred cancellation mechanism so having a disposes content doesn't mean the end of life since that disposed item can be replaced by a non-disposed item any time and continue.

> If so, can you please explicitly indicate this in the documentation?

Trying to prevent all those possible misunderstandings or mis-assumptions via documentation is infeasible, especially in a free and open-source project where you can find out and experiment with the code on your own to clear up your understanding. I firmly think this question and the original assumptions behind it are not suitable for explicit mention in the documentation.

**Comment by bejibx** [comment]
It seems I just misunderstood ```SerialDisposable``` concept. Sorry about that.

> Trying to prevent all those possible misunderstandings or mis-assumptions via documentation is infeasible, especially in a free and open-source project where you can find out and experiment with the code on your own to clear up your understanding.

Not quite agree with that. Having this little clarification in documentation would have saved me about 2 hours trying to understand why my app behave so strange. There could be another developers who may at first misunderstood how ```SerialDisposable``` behaves.

Anyway, closing this issue. Again, sorry for bother you.
