### ISSUE TITLE
Feature request: put back Subscriptions

### ISSUE THREAD

**Issue by wz2b** [ReactiveX/RxJava#5393]
This comment is related to reactive 2.0.7 and the description in https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0 

> To avoid the name clash, the 1.x rx.Subscription has been renamed into io.reactivex.Disposable (somewhat resembling .NET's own IDisposable).
> 'rx.Subscriber and can be cancelled/disposed externally via dispose()

If you look a piece of code and you see this:

`sub.unsubscribe()`

it's immediately pretty clear what it does.  On the other hand, if you see this:

`sub.dispose()`

you really have no idea.  'dispose' invokves thoughts of garbage collection, memory deallocation, freeing native resources, etc.  Anything beyond that is a side effect.  In terms of achieving some degree of parity with C# doing this has made it far less clear to the casual reader.

I'd really like to see the name collision solved in another way.  Maybe the thing to do is to put back Subscription but make its use optional (Subscription extends Dispose).  Perhaps that's not a good solution - I don't fully understand the problem.  I just want to request something be done to make it more clear what it's doing, because "you unsubscribe by calling dispose()" seems like a step in the wrong direction.

**Comment by akarnokd** [comment]
No.

> it's immediately pretty clear what it does

I give you a counterexample. 1.x' `Scheduler` methods returned `rx.Subscription` as well but in terminology, tasks are **cancelled**, not unsubscribed thus calling `unsubscribe()` there could be considered as misnaming.

In this respect, `Disposable` and `dispose` is a more generic concept that can stop tasks, clean up resources and unsubscribe reactive flows without deriving its name from any of those activities. This is especially true if a single call to `dispose` actually does all these three things at once (stops a task, releases resources and unsubscribes from an `Observable` connection.)

> I just want to request something be done

Use Kotlin and add an extension method to `Disposable` named as you see fit. Also since RxJava is stable since last October, such disruptive change would break our established aim to stay binary compatible and stay consistent with the API provided.
