### ISSUE TITLE
assertSubscribed() always passes no matter how many times a Flowable is subscribed to.

### ISSUE THREAD

**Issue by RichardWarburton** [ReactiveX/RxJava#5474]
Hi,

Perhaps I've misunderstood the purpose of this API method, but the javadoc for `assertSubscribed()` that it should only pass if the Flowable has been subscribed to. However it seems to pass for me even if I don't subscribe, eg the following passes:

```
Flowable.fromArray(1, 2).test().assertSubscribed();
```

It also suggests that it will pass if you only subscribe once, so the following test case should also fail, but seems to pass:

```
final Flowable<Integer> flowable = Flowable.fromArray(1, 2);
        flowable.subscribe();
        flowable.subscribe();
        flowable.test().assertSubscribed();
```

I've tested this in both rxjava 2.1.1 and 2.0.1.

**Comment by JakeWharton** [comment]
Calling test() calls subscribe automatically and returns the
TestSubscriber. This would only then return false in this case of a broken
Flowable that never called the onSubscribe method of the Subscriber.

**Comment by RichardWarburton** [comment]
Oh I see. If that's the intended behaviour then I would suggest that the Javadoc is clarified.

**Comment by JakeWharton** [comment]
I don't think it's inaccurate. Creating your own TestSubscriber instance
will have that method return false until you subscribe it to something.

**Comment by akarnokd** [comment]
Indeed, the javadoc says "Assert that the onSubscribe method was called exactly once." but the method doesn't actually check if there were multiple subscriptions with the same `TestSubscriber`. If `onSubscribe` was called multiple times, there is an `IllegalStateException` added to the errors of the `TestSubscriber` and `assertNoErrors()` would report on that. A small adjustment to "Assert that the onSubscribe method was called." would correct this potential discrepancy in a light way.

However, judging from the unit tests provided, the main assumption about RxJava flows seems to be wrong. The [Javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#test()) of `test()` states:

> Creates a TestSubscriber that requests Long.MAX_VALUE and **subscribes** it to this Flowable.

i.e., calling `test()` will trigger subscription and the chain will call `onSubscribe` thus `assertSubscribed` is passing.

Calling `subscribe()` creates an individual channel to the source thus calling it 3 times will establish 3 channels, each with its own consumer when calling `subscribe()` and `test()`, thus there is no single consumer to assert the number of `onSubscribe` calls and expect it to be 3. Cold sources, like `fromArray` don't count the number of subscribers they have interacted with during their lifetime because there is no use for that information in general (plus requires mutable state and atomics inside flows).

ReactiveX sources are sometimes considered a deferred, lazy and template of flows where calling `subscribe()` will realize the flow. In contrast, Java `Stream` is just lazy: streaming twice requires rebuilding the entire flow manually. Being deferred has a huge advantage in flows when time and/or failure is a considerable part of the setup: if a stage fails or times out, this nature allows resubscribing to the upstream from that stage automatically and without the need to rebuild that part of the flow manually. This has also the added benefit that the downstream may not even know there was a failure and retry and eventually and possibly receiving the data it wants to process.

**Comment by RichardWarburton** [comment]
Hi gents,

Thanks for your replies. I was aware of the big picture stuff here but I hadn't put the implications together in my own mind. Thanks for clarifying the situation. I think the javadoc change you suggested would help confusion around the "subscribe once" aspect as well. I'll close this issue.

regards,

  Richard
