### ISSUE TITLE
Merge works not as expected

### ISSUE THREAD

**Issue by gengjiawen** [ReactiveX/RxJava#5496]
The operator merge not work as expected.
Version: 2.1.0
```java
    public static void main(String[] args){

        Observable<Integer> i = Observable.create((ObservableEmitter<Integer> e) -> {
            throw new RuntimeException("h1");
        }).subscribeOn(Schedulers.io());

        Observable<Integer> i2 = Observable.create((ObservableEmitter<Integer> e) -> {
            throw new RuntimeException("h2");
        }).subscribeOn(Schedulers.io());

        Observable.merge(i, i2)
                .subscribeOn(Schedulers.io())
                .subscribe(
                        integer -> {
                            System.out.println("integer = " + integer);
                        },
                        throwable -> {
                            System.out.println("throwable = " + throwable);
                        });

        try {
            Thread.sleep(20 * 1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

If I remove `i`, `i2` subscribeOn operator. It works fine.

**Comment by akarnokd** [comment]
I don't see how you have any expectation about this setup or how you'd define "doesn't work" in this context.

**Comment by gengjiawen** [comment]
It crash.I expect it will deal with the first stream error occured, kill other stream.

**Comment by akarnokd** [comment]
This setup behaves correctly because you race the emission of two errors due to `subscribeOn` on two independent threads. There are a couple of outcomes possible and legal:

- h1 wins and cancels i2, no h2 emission
- h2 wins and cancels i, no h1 emission
- h1 wins but h2 reaches the merge and a composite exception is formed
- h2 wins but h1 reaches the merge and a composite exception is formed
- h1 wins but h2 reaches the merge and gets routed to the global error handler
- h2 wins but h1 reaches the merge and gets routed to the global error handler
- h1 wins and i2 is cancelled just before trying to signal h2, which then gets routed to the global error handler
- h2 wins and i is cancelled just before trying to signal h1, which then gets routed to the global error handler

**Comment by gengjiawen** [comment]
thanks, it's very clear.
