### ISSUE TITLE
Single shared operator

### ISSUE THREAD

**Issue by jaumard** [ReactiveX/RxJava#5498]
With rx2.x and Single, I'm search for the equivalent of the shared operator from Observable.
 
From what I understand this operator doesn't exist for Single, is there a reason for that ? 

My need is to shared a Single that execute network call, I don't want to do x time that network call, just want to share the response when the network call is done. `cache` operator is not what I need as it will never do the network call again. If there multiple subscribe during a call just share the response of the first one, if not just execute the network call normally

**Comment by akarnokd** [comment]
The semantics for `ConnectableSingle` has not been defined and the alternatives, such as converting to `Observable` and back for the missing operations or using `cache`, were enough as the workaround. In addition, since the `Single` succeeds or fails, the `refCount` would be a gamble because if you don't subscribe fast enough in a batch, one of the subscribers would restart the upstream unexpectedly. Therefore, there are currently no plans to have such extensions for the "shorter" reactive base types.
