### ISSUE TITLE
2.x: Single#error won't invoke RxJavaPlugins#onError even if observer is disposed.

### ISSUE THREAD

**Issue by xkikeg** [ReactiveX/RxJava#5514]
When I wrote the simple code like that
```java
ArrayList<Throwable> exceptions;
RxJavaPlugins.setOnError(exceptions::add);
Single.error(new RuntimeException("error!!!")).test(true).dispose();
assertThat(exceptions.size(), isEqualTo(1));
```
The test will fail as `exceptions.size()` is actually zero. Seeing `SingleError`, it seems invoking `Observer#onError` even if it's disposed. Is it intended behavior? For `SingleCreate`,
```java
Single.create(
        (emitter) -> {
          throw new RunTimeException("error!!!");
        })
    .test(true)
    .dispose();
assertThat(exceptions.size(), isEqualTo(1));
````
It correctly invokes `RxJavaPlugins#onError`.

(btw https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/plugins/RxJavaPlugins.java#L365 calls `#uncaught(e)` twice, it's not interesting behavior as well...)

**Comment by akarnokd** [comment]
All `error()` operators ignore cancellation by design, as do the `empty()` operators. These behaviors are allowed by the Reactive-Streams specification and also come in quite handy when testing other operators.

In RxJavaPlugins, there is one invocation of uncaught with the exception of the handler if the handler failed and the default call with the original error.

**Comment by xkikeg** [comment]
Thanks for prompt reply.
I've not understood the design yet (what's the benefit if ignoring cancellation in `error()`), but I got it.

Also thanks for `uncaught` explanation. Now I fully got the point.
