### ISSUE TITLE
Task order for Observable.combineLatest and Schedulers.computation()

### ISSUE THREAD

**Issue by dya-victor** [ReactiveX/RxJava#5561]
Version: 1.3.0

Hello!

I have observed strange behavior while I was using combineLatest with Schedulers.computation(). Please take a look at example:
```java
   private static void runSubscription(String prefix, boolean shouldWait, ConcurrentMap<String, Integer> stat) {
        Observable<Long> interval = Observable.interval(1000, TimeUnit.MILLISECONDS);
        Observable.combineLatest(Observable.just(prefix), interval, (s1, s2) -> s1)
            .subscribeOn(Schedulers.computation())
            .observeOn(Schedulers.computation())
            .onBackpressureLatest()
            .subscribe(s -> {
                try {
                    if (shouldWait) {
                        Thread.sleep(4000);
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                stat.merge(s, 1, (v1, v2) -> v1 + v2);
            });
    }

    public static void main(String[] args) throws Exception {
        ConcurrentMap<String, Integer> stat = new ConcurrentHashMap<>();

        stat.put("1", 0);
        runSubscription("1", true, stat);
        for (int i = 1; i < Runtime.getRuntime().availableProcessors(); i++) {
            String key = String.valueOf(i + 1);
            stat.put(key, 0);
            runSubscription(key, false, stat);
        }

        while (!Thread.currentThread().isInterrupted()) {
            // Print invocation statistics
            System.out.println(stat);
            Thread.sleep(4000);
        }
    }
```
The output shows how many times particular subscriber was invoked. First column - subscriber number, second - invocation count. For version above output is:
```
{1=0, 2=0, 3=0, 4=0}
{1=0, 2=1, 3=1, 4=3}
{1=1, 2=1, 3=1, 4=7}
{1=2, 2=1, 3=1, 4=11}
{1=3, 2=1, 3=1, 4=15}
{1=4, 2=1, 3=1, 4=19}
{1=5, 2=1, 3=1, 4=23}
{1=6, 2=1, 3=1, 4=27}
{1=7, 2=1, 3=1, 4=31}
...
```
The output is not stable, but every time some of threads invoked less times. 
But when I changed both `Schedulers.computation()` to `Schedulers.io()`, output changed to expected:
```
{1=0, 2=0, 3=0, 4=0}
{1=0, 2=3, 3=3, 4=3}
{1=1, 2=7, 3=7, 4=7}
{1=2, 2=11, 3=11, 4=11}
{1=3, 2=15, 3=15, 4=15}
{1=4, 2=19, 3=19, 4=19}
```
Is it incorrect usage of scheduler, or it is a bug?

**Comment by akarnokd** [comment]
The `computation` scheduler has a number of worker threads that is, by default, is equal to the number of available processors and hands out worker threads in a round robin fashion. Since there is a limited number of them and you block one of them in your first run, the subsequent runs will likely get that scheduler and block tasks behind it.

You are practically wasting schedulers as `subscribeOn` in this case has no effect, `interval` already runs on the computation scheduler and `observeOn` moves the events from one computation worker to another without much benefit.

**Comment by dya-victor** [comment]
Thank you for quick answer! But I still have a doubts. I tried to changed `Schedulers.computation` to `Schedulers.from(Executors.newFixedThreadPool(3))`, nine subscriptions, and it did work as expected:
```
{1=0, 2=0, 3=0, 4=0, 5=0, 6=0, 7=0, 8=0, 9=0}
{1=0, 2=3, 3=3, 4=3, 5=3, 6=3, 7=3, 8=3, 9=3}
{1=1, 2=7, 3=7, 4=7, 5=7, 6=7, 7=7, 8=7, 9=7}
{1=2, 2=11, 3=11, 4=11, 5=11, 6=11, 7=11, 8=11, 9=11}
```
In the same time, even with removing `observeOn` and `subscribeOn` number of invocations are not even. 

<details>
<summary>Modified code, Executor used</Summary>

```java
public class Main {
    private static final Executor executor = Executors.newFixedThreadPool(3);

    private static void runSubscription(String prefix, boolean shouldWait, ConcurrentMap<String, Integer> stat) {
        Observable<Long> interval = Observable.interval(1000, TimeUnit.MILLISECONDS);
        Observable.combineLatest(Observable.just(prefix), interval, (s1, s2) -> s1)
                .onBackpressureLatest()
                .observeOn(Schedulers.from(executor))
                .subscribeOn(Schedulers.from(executor))
                //.observeOn(Schedulers.computation())
                .subscribe(s -> {
                    try {
                        if (shouldWait) {
                            Thread.sleep(4000);
                        }
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    stat.merge(s, 1, (v1, v2) -> v1 + v2);
                });
    }

    public static void main(String[] args) throws Exception {
        ConcurrentMap<String, Integer> stat = new ConcurrentHashMap<>();

        stat.put("1", 0);
        runSubscription("1", true, stat);
        for (int i = 1; i < Runtime.getRuntime().availableProcessors() + 5; i++) {
            String key = String.valueOf(i + 1);
            stat.put(key, 0);
            runSubscription(key, false, stat);
        }

        while (!Thread.currentThread().isInterrupted()) {
            // Print invocation statistics
            System.out.println(stat);
            Thread.sleep(4000);
        }
    }
}
```
</details>

**Comment by akarnokd** [comment]
`Executors.newFixedThreadPool(3)` works differently than our schedulers. We have N x `Executors.newSingleThreadedScheduledExecutor()`, each of them handed out to operators on demand. If one gets stuck, everybody who gets that executor is blocked. 

In contrast, `newFixedThreadPool(3)` has 3 workers which pick the next task from a shared queue. If one is blocked, the other 2 will be still able to pick tasks from the queue.

**Comment by dya-victor** [comment]
Thank you!

**Comment by timofeevda** [comment]
> Executors.newSingleThreadedScheduledExecutor(), each of them handed out to operators on demand. If one gets stuck, everybody who gets that executor is blocked.

That's a strange design decision. If we replace Thread.sleep() with tough computational work (e.g. several nested loops with large amount of iterations) one of "observeOn" operators will be starving because the other one keeps getting tasks from "observeOn" queue effectively blocking other operator who got that executor.

In case of bad timings, backpressure and conditional logic within "CPU bound" work (leading to arbitrary execution time spent in observer) usage of Scheduler.computation() will lead to completely unpredictable results.

Looks like round-robin policy of handing out pooled worker is very sensitive to the rate of events and time computational work takes. Shared queue doesn't have this issue but may be slightly less efficient.

In any case behavior described above seems conterintuitive. I would except scheduler to try to invoke tasks regardless of "slow" tasks performed in one of the workers.

**Comment by akarnokd** [comment]
> That's a strange design decision.

It is designed as such by default to avoid thread hopping that hurts performance in the long run. Plus, if you actually don't block but compute something, you are making progress.

> I would except scheduler to try to invoke tasks regardless of "slow" tasks performed in one of the workers.

The default doesn't do that because most operators expect a FIFO execution and reliable delayed scheduling which can be achieved by a single threaded scheduled executor. 

For all other cases, there is the option of `Schedulers.from` which adds the penalty for forcing a FIFO execution internally in case the underlying executor is multi-threaded and has to use helper schedulers to ensure timing stays ordered.

**Comment by timofeevda** [comment]
OK, thanks for explanation.
