### ISSUE TITLE
2.x: flowable blockingSubscribe bug

### ISSUE THREAD

**Issue by mvoda** [ReactiveX/RxJava#5605]
Ran into the following unexpected behavior (bug?) when experimenting with Flowables:
RxJava v2.1.3

```java
Flowable.just(1, 2).mergeWith(Flowable.error(new Exception("whoops")))
   .blockingSubscribe(v -> LOGGER.info("received: " + v), LOGGER::error, () -> LOGGER.info("completed"));
```

I expected to get the following output: 
```
received: 1
received: 2
java.lang.Exception: whoops
```
but the code only logs the exception, without any values. 

Changing blockingSubscribe to subscribe produces the expected output. 
Also, using Observable instead of Flowable produces the expected output with both subscribe and blockingSubscribe, which makes me think this might be a bug.

**Comment by akarnokd** [comment]
This is a valid outcome. `mergeWith` allows errors to cut ahead. In this case, since `blockingSubscribe` requests later than a regular `subscribe`, the underlying `merge` operator won't relay the 1, 2 when they are emitted due to lack of requests but the `Exception` can and will be emitted without downstream requests.

Try `concatWith` instead.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
