### ISSUE TITLE
Use take() concat() skip() together would cause item lost.

### ISSUE THREAD

**Issue by jie-meng** [ReactiveX/RxJava#5666]
Version: 2.1.5

```java
public static void main(String[] args) {
        Observable<Integer> src = Observable.just(1, 2, 3, 4, 5);
        src.publish(new Function<Observable<Integer>, ObservableSource<Integer>>() {
            @Override
            public ObservableSource<Integer> apply(@NonNull Observable<Integer> integerObservable) throws Exception {
                return integerObservable.take(2).concatWith(integerObservable.skip(2));
            }
        }).subscribe(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) throws Exception {
                System.out.println(integer);
            }
        });
    }

```

expected result: 1 2 3 4 5
actual result: 1 2 5

3 and 4 are lost. We suppose it was a bug.

**Comment by akarnokd** [comment]
That is the expected behavior. This is what happens:

1. the range 1..5 is shared through a function
2. the `integerObservable` you get will emit 1, 2
3. the `take` unsubscribes after this two items
4. `concatWith` switches to its second `ObservableSource` and subscribes to it
5. the `skip` subscribes to the shared `integerObservable`
6. the `integerObservable` resumes with 3, 4, 5
7. `skip` ignores 3, 4; relays 5
8. the sequence completes.

So due to `concatWith`, the second parameter sequence doesn't get to interact with the shared sequence until the first half completed.

**Comment by jie-meng** [comment]
Got it, Thanks!

publish() makes src Observable to hot.

Change code to

```
public static void main(String[] args) {
        Observable<Integer> src = Observable.just(1, 2, 3, 4, 5);
        src.take(2).concatWith(src.skip(2))
.subscribe(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) throws Exception {
                System.out.println(integer);
            }
        });
    }
```
It works as expected.
