### ISSUE TITLE
Single.subscribeWith is not disposed

### ISSUE THREAD

**Issue by vovkab** [ReactiveX/RxJava#5697]
Rxjava version:

```
compile "io.reactivex.rxjava2:rxjava:2.1.6"
```

Example:

```java
Disposable disposable = Single.just("123")
        .subscribeWith(new DisposableSingleObserver() {
            @Override
            public void onSuccess(Object o) {}

            @Override
            public void onError(Throwable e) {}
        });

System.out.println("Disposed: "  + disposable.isDisposed());
```

Output:
```
Disposed: false
```

Expected result:
Disposable should be disposed.

Related issues:
 * #5160 : 2.x: Disposable returned from Single.subscribe() is not disposed after terminal event
 * #5276 : Single's Disposable is not disposing

**Comment by akarnokd** [comment]
Since `DisposableSingleObserver` implements the `SingleObserver` interface as abstract methods, it can't call `dispose()` for you and you have to call that from within `onSuccess` or `onComplete`. Therefore, you can either call the lambda `subscribe()` overload and get the `isDisposed` consistent with the state or define your abstract wrapper over `DisposableSingleObserver`.

In concept, once `onSuccess` or `onError` are called, the upstream is to be considered disposed thus there should be no reason to call `dispose` at that point. People often need side-effects when a source terminates or gets disposed, thus they use `doOnDisposed` and call `dispose` from `onSuccess` to trigger that cleanup. However, there is a more appropriate operator called `doFinally` that executes after terminal events or dispose calls, thus you don't have to call `dispose` to cleanup a flow.

[ResourceSingleObserver](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observers/ResourceSingleObserver.html)'s JavaDoc explains it a bit better though.

**Comment by vovkab** [comment]
@akarnokd thank you for such a quick answer!

From documentation I see:
> A Single will call only one of these methods, and will only call it once. Upon calling either method, the Single terminates and the subscription to it ends.

So it should be terminating subscription, or this is a client responsibility now?

Do you know how can I achieve the same result like we did in rxjava1 with subscription, where we don't have to worry about manually unsubscribing from source if it finished, i.e. `onError` or `onComplete` is being called?

I'm just trying to keep a reference to a "subscription" and to be able to say if we still subscribed or not.

**Comment by akarnokd** [comment]
Disposing resources is the producer's responsibility (aka, the upstream) so you don't have to call `dispose` on a terminal event. However, using `isDisposed` to determine a source has terminated is discouraged; you should be reacting to the terminal signal in `onSuccess` or `onError` if you want to perform some operation. Otherwise `DisposableSingleObserver.isDisposed()` only returns true if you called `dispose()`:

```java
Disposable disposable = Single.just("123")
        .subscribeWith(new DisposableSingleObserver() {
            @Override
            public void onSuccess(Object o) {
                dispose();
            }

            @Override
            public void onError(Throwable e) {
                dispose();
            }
        });

System.out.println("Disposed: "  + disposable.isDisposed());
```

**Comment by vovkab** [comment]
> Disposing resources is the producer's responsibility (aka, the upstream)

Does it mean that `Single.just("123")` should have called `.dispose`?

> Otherwise DisposableSingleObserver.isDisposed() only returns true if you called dispose()

Feels a bit clunky that client have to manually unsubscribe even though in case of the Single, we know that it will be an error to call `onSuccess` or `onError` again, so there is no point for subscription to exists after thous methods have been called. Maybe, of course, I'm missing some important use cases.

**Comment by akarnokd** [comment]
Upstream's don't care if your `SingleObserver` implements `Disposable` because unlike 1.x, `dispose()` travels upstream and never downstream. If a chain has resources, a terminal event will free those resources so you don't have to call `dispose`. `just` has no resources associated.

The convenience observer classes, such as `DisposableSingleObserver` are provided so one can call `dispose` on it from any thread without the need to dig into the concurrency implications of such call. 

`isDisposed` makes only sense on container types and inside operators that check if they should continue producing data or not.

Checking if a flow has terminated via `isDisposed` has two discouraged uses: trying to sleep-loop or busy-loop on it or having a completely synchronous flows that terminates once the execution returns from `subscribe()`. You have the latter case.

The `DisposableSingleObserver` [keeps](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observers/DisposableSingleObserver.java#L56) two abstract methods, `onSuccess` and `onError` from [SingleObserver](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/SingleObserver.java#L54). You implement those methods and `Single` talks to the `SingleObserver` interface. There is nothing in between that would react to the method calls and make `isDisposed` return true - we don't use aspect oriented programming in RxJava after all.

So either don't rely on `isDisposed` or write another wrapper that implements `onSuccess` and `onError`, delegates some alternative abstract methods and then calls `dispose()` for you to get `isDisposed` return true:

```java
public abstract class AbstractMySingleObserver<T> extends DisposableSingleObserver<T> {

    @Override
    public final void onSuccess(T item) {
        try {
            success(item);
        } finally {
            dispose();
        }
    }

    @Override
    public final void onError(Throwable ex) {
        try {
            error(ex);
        } finally {
            dispose();
        }
    }

    protected abstract void success(T item);

    protected abstract void error(Throwable ex);

}
```

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
