### ISSUE TITLE
2.x: SingleFromCallable doesn't check isDisposed before calling onError or onSuccess.

### ISSUE THREAD

**Issue by runningcode** [ReactiveX/RxJava#5742]
I was investigating a bug and I noticed that `SingleFromCallable` doesn't check `isDisposed()` before calling `onError` or `onSuccess` when comparing it to `ObservableFromCallable`.

Should it be checking `isDisposed()`? If not, why not? Or is this a bug?

My code example where I'm getting this error is Android based:
I have a HomePresenter with this code:
```
void setActivity(Activity activity) {
	Timber.d(“HomePresenter attachActivity”);
	this.activity = activity;
}
```

```
void onStart() {
	Timber.d(“HomePresenter onStart”);
	disposables.add(api.getEmail()
		.subscribeOn(Schedulers.io())
		.observeOn(AndroidSchedulers.mainThread())
		.subscribe(email -> {
			Timber.d(“email was %s”, email);
			activity.setEmail(email);
		})
	);
```
```
void onStop() {
	Timber.d(“HomePresenter onStop”);
	disposables.clear();
	activity = null;
}
```

in the logs I see:
```
Lifecycle onStart HomeActivity
HomePresenter attachActivity
HomePresenter onStart
Lifecycle onStop HomeActivity
HomePresenter onStop
email was foo@bar.com
NullPointerException: attempt to invoke virtual method Activity.setEmail(String) on null object reference
```

It seems the subscription to the observable was cleared before the `onSuccess` method was called.

Or maybe I'm missing something else completely, anyways, thanks for the help :)

**Comment by akarnokd** [comment]
Indeed it is inconsistent with the other operators. Would you like to submit a PR? The [`MaybeFromCallable`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/maybe/MaybeFromCallable.java) should give a hint about the proper implementation.

Otherwise, the NPE is due to the line `activity.setEmail(email);` where `activity` is null. Even if `isDisposed` would have been considered, there is a race between completion of the source and stopping the activity, thus you may end up with null `activity` anyway.
