### ISSUE TITLE
Handling termination of merged streams

### ISSUE THREAD

**Issue by RobLewis** [ReactiveX/RxJava#5751]
I can't find a description of what happens when streams combined with `.merge()` terminate. The logical behavior would be for the merged stream to terminate only when all the source streams have finished, but I don't see this explicitly stated anywhere. Also I suppose there could be cases where you would want the merged stream to finish when the _first_ source does. 

What about other operators that combine streams?

**Comment by akarnokd** [comment]
When all sources to `merge()` complete, the operator completes. This is implied by the [marble diagram](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#merge-io.reactivex.ObservableSource-).

> Also I suppose there could be cases where you would want the merged stream to finish when the first source does.

In my experience, such flow pattern didn't come up so far regarding `merge()`. There could be similar effects with `amb` or `withLatestFrom`.

> What about other operators that combine streams?

You could look at the marbles for that.

**Comment by RobLewis** [comment]
Thanks, but that marble diagram doesn't actually address my question. And if you look at [this 1.x marble diagram](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/merge.png), it (and the accompanying text) address handling of errors, but not completions.

**Comment by akarnokd** [comment]
That's why I linked `merge(Observable<Observable<T>>)` which is the same in [1.x](http://reactivex.io/RxJava/1.x/javadoc/rx/Observable.html#merge-rx.Observable-).

Merge completes if all sources complete normally, otherwise it would lead to non-deterministic data loss. If the `delayError` option is set, all sources must complete normally or with error and then the final event is either a completion or a composite of any errors received.

I suggest you read the book [**Programming with RxJava**](http://shop.oreilly.com/product/0636920042228.do) to get the general feel of what to expect from RxJava operators.

**Comment by RobLewis** [comment]
I submit that your answer above, "Merge completes if all sources complete normally", would improve the quality of the documentation if added in the appropriate places. A bonus would be to illustrate this (for the case of simple Observables, not Observables that emit Observables) with a marble diagram.

**Comment by akarnokd** [comment]
If you want, you can submit a PR that improves the wording and diagrams of 20+ methods across several base classes.
