### ISSUE TITLE
TestObserver reporting onComplete event when there are none

### ISSUE THREAD

**Issue by nschwermann** [ReactiveX/RxJava#5774]
Hello using version 2.1.4 and this simple test reproduces the issue

        Maybe.just("test")
                .test()
                .assertValue("test")
                .assertNoErrors()
                .assertNotComplete()

We get back the value test but the TestObserver reports back on onComplete as well and test test fails. 

However, subscribing with subscribe(Consumer<? super T> onSuccess, Consumer<? super Throwable> onError, Action onComplete)  does not trigger the Action onComplete as I expect it shouldn't.

**Comment by akarnokd** [comment]
`TestObserver` serves for `Observable`, `Maybe`, `Single` and `Completable` but for to do so, it does protocol conversion and otherwise it is unaware what type it tests. Therefore, it will report `onComplete` for [success](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observers/TestObserver.java#L346)es in `Maybe` and `Single`.

**Comment by nschwermann** [comment]
Thanks for pointing that out @akarnokd. You say the implementation is unaware if it is Observable, Maybe, etc. However you are overriding onSuccess here which would indicate it is either Maybe or Single, correct? So in this case onComplete shouldn't be called or otherwise counter for it should not be incremented. Is there some other way I'm not aware of that onSuccess could be called here? (I wouldn't be at all surprised)

**Comment by akarnokd** [comment]
`TestObserver` [implements](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observers/TestObserver.java#L36) the consumer types of the listed base types where `MaybeObserver` and `SingleObserver` happen to define `void onSuccess(T item)`, hence the `@Override` annotation as per Java language convention.

The protocol conversion helps with the following assertions:

```java
Maybe.just(1)
.test()
.assertResult(1);

Maybe.error(new RuntimeException())
.test()
.assertFailure(RuntimeException.class);

Maybe.empty()
.test()
.assertResult();
```

`assertResult` and `assertFailure` are the primary means to verify basic outcomes on all reactive types. Because of the protocol conversion and due to quite a few operators present on all types, this helps a lot in reducing testing boilerplate across the base reactive types.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
