### ISSUE TITLE
2.x Flowable test with null values are ignored

### ISSUE THREAD

**Issue by fooock** [ReactiveX/RxJava#5800]
I'm using the version **2.1.8** from the master branch of this repo

I forked the project and executed the tests. When finished, I see that multiple test are ignored like the `mergeWithNullValues()` from the `FlowableMergeTest` class. This test contains:

```java
TestSubscriber<String> ts = new TestSubscriber<String>();
Flowable.merge(Flowable.just(null, "one"), Flowable.just("two", null)).subscribe(ts);
ts.assertTerminated();
ts.assertNoErrors();
ts.assertValues(null, "one", "two", null);
```
Obviously this test shouldn't never be pass, but, why is ignored? If we expect for this test a `NullPointerException`, why not make the test to expect this result? Like:

```java
@Test(expected = NullPointerException.class)
public void mergeWithNullValues() {
    TestSubscriber<String> ts = new TestSubscriber<String>();
    Flowable.merge(Flowable.just(null, "one"), Flowable.just("two", null)).subscribe(ts);
    ts.assertTerminated();
    ts.assertNoErrors();
    ts.assertValues(null, "one", "two", null);
}
```
Multiple tests with similar behavior exists.

Thanks

**Comment by akarnokd** [comment]
These are remnant from the v1 tests and during the migration, I used custom tools to see which test methods have to be ported. Some of them are now invalid but serve a new purpose. They make sure the Travis CI output is changing every couple of seconds due to reporting ignored tests which prevents the CI from cancelling the build when it doesn't detect output from it for 10 minutes (the tests run over 11 minutes on CI). 

The `null` checks themselves are verified elsewhere and don't really need the whole old test as it will throw as soon as `Flowable.just(null, "one")` executes.
