### ISSUE TITLE
Interval operator leaks

### ISSUE THREAD

**Issue by gabrielhuff** [ReactiveX/RxJava#5803]
I was wondering if it is safe to subscribe to `interval` streams without worrying about disposing if the observable itself is only referenced within the subscription scope.

Since I couldn't find the answer on the docs, I tried to run a practical example. Consider the following class (running with RxJava 2.1.8, written in Kotlin for simplicity):

```kotlin
class Counter(tics: Observable<Unit>) {

    var value = 0

    init { tics.subscribe { value++ } }
}
```

After running some tests, I noticed the following:

```kotlin
// Counter instances WON'T leak here
(0..100_000_000).forEach { Counter(BehaviorSubject.create()) }

// Counter instances WILL leak here
(0..100_000_000).forEach { Counter(Observable.interval(1, TimeUnit.SECONDS).map { Unit }) }
```

So, it appears that I must always unsubscribe when it comes to `interval` observables, even if their scope is limited to its observers, otherwise they will leak. My guess would be that this happens because there's no weak referencing between the `interval` observables and whatever is triggering its emissions.

Note that ihis is not true for all observables (the `Subject` example does not result on a leak).

Is there a way to fix this behaviour? If not, would it be possible to update the `interval` operator documentation?

**Comment by akarnokd** [comment]
When you no longer need an active source, you should `dispose`/`cancel` it, otherwise resources may leak. 

In case of `interval`, there is a background thread that holds strong a reference to the `Observer` so it can emit the next value once the defined time elapses (over and over). It can't know that you no longer care about receiving events unless you explicitly tell it to stop via `dispose()`. In accordance, ignoring the `Disposable` of `subscribe(Consumer)` is the telltale sign of potential reference leaks, especially on Android.

> Is there a way to fix this behaviour?

Yes, dispose the subscription to `interval` explicitly.

> If not, would it be possible to update the interval operator documentation?

The behavior is governed by the [Reactive Streams specification Rule 2.6](https://github.com/reactive-streams/reactive-streams-jvm#2.6) from which the [`Observable` is derived](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html):


6 | A Subscriber MUST call Subscription.cancel() if the Subscription is no longer needed.
-- | --
:bulb:  | The intent of this rule is to establish that Subscribers cannot just throw Subscriptions away when they are no longer needed, they have to call cancel so that resources held by that Subscription can be safely, and timely, reclaimed. An example of this would be a Subscriber which is only interested in a specific element, which would then cancel its Subscription to signal its completion to the Publisher.

[Observable.java#L52](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L52)

> The design of this class was derived from the Reactive-Streams design and specification by removing any backpressure-related infrastructure and implementation detail, replacing the org.reactivestreams.Subscription with `Disposable` as the primary means to cancel a flow.

**Comment by gabrielhuff** [comment]
I see. Thanks for the references.

So I guess that, on the example I provided, the `Counter` class would have to explicitly expose a clean-up method (maybe implement `Closeable`), otherwise it would be fundamentally leakable.

Still, I can see that, from an implementation perspective, this is currently not true for the `Subject` implementations (e.g. `PublishSubject`, `BehaviorSubject`), right? Do you think it's safe to assume they will be collected or should we always dispose its subscriptions?

**Comment by akarnokd** [comment]
I don't recommend speculating about the reference graphs in RxJava components and you should always `dispose`/`cancel` when events are no longer needed.

**Comment by gabrielhuff** [comment]
Alright, thank you very much
