### ISSUE TITLE
2.x A question about the efficiency of processor sub classes implementation

### ISSUE THREAD

**Issue by fanzhengchen** [ReactiveX/RxJava#5825]
I think the implementation of processor such as PublishProcessor could be improved.
For example of [PublishProcessor](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/processors/PublishProcessor.java)
  2.x
```java
boolean add(PublishSubscription<T> ps) {
        for (;;) {
            PublishSubscription<T>[] a = subscribers.get();
            if (a == TERMINATED) {
                return false;
            }

            int n = a.length;
            @SuppressWarnings("unchecked")
            PublishSubscription<T>[] b = new PublishSubscription[n + 1];
            System.arraycopy(a, 0, b, 0, n);
            b[n] = ps;

            if (subscribers.compareAndSet(a, b)) {
                return true;
            }
        }
    }
```
we apply for a new array and copy, it may fail when it runs with multiple threads, it would be a waste of computational resource when operate the array. I think **persistent data structure** would work better, especially for this assigning variable with multiple threads, what do you think?

**Comment by akarnokd** [comment]
With subjects, the dominant operation is almost always the dispatching of items for which the current linear array of subscribers is the fastest. The current copy-on-write approach is close to optimal when the total number of subscribers are less than 16 (one cache line). It is very rare there are more than this number of subscribers and even if, they tend not to fluctuate much after an initial subscription storm.

>I think persistent data structure would work better

[Doesn't work](https://en.wikipedia.org/wiki/Persistent_data_structure):

*" In computing, a persistent data structure is a data structure that **always preserves the previous version** of itself when it is modified. Such data structures are effectively immutable, as their operations do not (visibly) update the structure in-place, but instead always yield a new updated structure."*

That means you'll have a memory leak with the `Processor`.

Also I couldn't find any  "concurrent persistent data structure" and otherwise [they aren't as good as they seem](http://concurrencyfreaks.blogspot.hu/2013/10/immutable-data-structures-are-not-as.html).
