### ISSUE TITLE
replay(1) retains second-to-last emitted item

### ISSUE THREAD

**Issue by BenTilbrook** [ReactiveX/RxJava#5827]
Version:  `2.x`: `2.1.9`

When using `Observable.replay(1)`, the second-to-last object emitted by the upstream observable is retained by the internal buffer. I would expect only the last object to be retained, and this is especially problematic if the objects are large, such as an Android `Bitmap` or `Activity`.

Sample code:

```kotlin
val subject = BehaviorSubject.create<Int>()
subject.onNext(1)
subject.onNext(2)
subject.onNext(3)
val replay = subject.replay(1)
replay.connect()
Assert.assertEquals(listOf(3), replay.test().values())
subject.onNext(4)
Assert.assertEquals(listOf(4), replay.test().values())
subject.onNext(5)
// replay.current.value.buffer.value.value contains 4
Assert.assertEquals(listOf(5), replay.test().values())
```

**Comment by akarnokd** [comment]
That's an unfortunate effect of the linked structure in `replay` and the facts that 1) discontinuity is not allowed and 2) observers subscribing concurrently should start somewhere.

That's why the `head` references a `Node` instance where the actual value is behind the `next` link. This way, observers can pick the head `Node` and when the time is right for them, start walking the links. Thus, a `replay(1)` will have two nodes with a previous node and one with the cached value. Nulling out the previous node doesn't work as `replay` can't know there isn't a late consumer still walking the links from a much earlier node.

If there wasn't any initial empty `Node`, observers would have to keep check somehow when the first item's `Node` gets created. Unfortunately, this potentially concurrent activity may lead to lost initial items for some observers.

The third option would be reference counting Nodes, which is very expensive and complicated.

If you need to cache the very latest, simply keep using the `BehaviorSubject`.

**Comment by BenTilbrook** [comment]
Thanks for the explanation. I suspected along those lines.

If a fix isn't viable, I think this is worth documenting, as it's counter-intuitive.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by akarnokd** [comment]
There could be a less expensive approach by creating a fresh head node with link to the next cached item. This should allow late observers to capture the head node and follow the next links and the head would no longer reference the previous item:

```java
        void trim() {
            if (size > maxSize) {
                size--;
                Node<Object> h = head.get();
                Node<Object> n = new Node<Object>(null);
                n.lazySet(h.get());
                head = n;
            }
        }
```

The drawback is that there is now two nodes allocated per upstream item.

Note that there are 2 base type replays, 1 subject, 1 processor and 2 bounded replay modes, a total of 8 algorithms to adjust or document.

**Comment by akarnokd** [comment]
Closing via #5828.
