### ISSUE TITLE
RxJava 1.x end-of-life

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5854]
The end-of-life for the RxJava 1.x version is nearing, **March 31, 2018**. However, there are still a bunch of components marked as `@Beta` or `@Experimental`. Most of these have been made standard in 2.x from the beginning and users are encouraged to upgrade for some time now anyway.

There could be a final **1.4** release where these components are promoted to standard, however, the remaining 1-1.5 months aren't really that much time for support if some very latecommers start using them and find bugs.

Alternatively, the RxJava 1.x era could simply end with a 1.3.x patch version and without any promotion.

**Comment by davidmoten** [comment]
I agree that promoting `@Beta` or `@Experimental` features to standard doesn't mean much if the support life is so short. I'm not fussed about staying as is.

**Comment by artem-zinnatullin** [comment]
I'd keep `@Beta` and `@Experimental` annotations as is, end-of-life is end-of-life. Less changes we do - less we need to worry about.

**Comment by JakeWharton** [comment]
Since the annotations are indication of API stability, I see no reason to retain them for the final release as everything will become effectively stable. In fact, I'd argue that removing the annotations more clearly conveys the intention of the end-of-life release as a freezing of both API and implementation.

And since there is no risk in removing them I don't see a reason why they should be retained.

**Comment by davidmoten** [comment]
I prefer to keep them in the case of a fork that continues to release (I might do that to support my prod apps if required).

**Comment by akarnokd** [comment]
Closing via [1.3.8](https://github.com/ReactiveX/RxJava/releases/tag/v1.3.8). No changes to the tags.
