### ISSUE TITLE
No successful subscription when running `using` and `retry` together

### ISSUE THREAD

**Issue by dmitart** [ReactiveX/RxJava#5869]
Version: 'io.reactivex.rxjava2:rxjava:2.1.10'

No successful subscription when running `using` and `retry` together, without `retry` or with other `Single` everything is fine.

```        
Single.just("input").flatMap(val ->
                Single.using(
                        () -> {
                            System.out.println("create");
                            return "";
                            },
                        call -> singleSubscriber -> {
                            System.out.println("sub");
                            singleSubscriber.onSuccess(val);
                            System.out.println("sub done");
                            },
                        call -> {
                            System.out.println("close");
                        }
                        )
                .retry((count, error) -> {
                    System.out.println("retry");
                    return true;
                })
        )
                .subscribe(val -> System.out.println("output " + val));
```
Output:
```
create
sub
close
sub done
```

Expected:
```
create
sub
close
output input
sub done
```

**Comment by akarnokd** [comment]
You should not create a `SingleSource` via lambda as people often forget to follow the protocol: `onSubscribe (onSuccess | onError)?`. Use `Single.create()` instead:

```java
Single.create(singleSubscriber -> {
    System.out.println("sub");
    singleSubscriber.onSuccess(val);
    System.out.println("sub done");
})
```

with which now prints:

```
create
sub
close
output input
sub done
```

What happens is that `retry` converts to `Flowable` internally to reuse that operator, which requires downstream requests. However, since `onSubscribe` was never called, the request channel is never established below that operator and the single element is hold up indefinitely.

**Comment by dmitart** [comment]
This solves my issue, thank you. I was not using `using` a lot before and didn't knew about this convention.
