### ISSUE TITLE
2.x Implementing partitioning with parallel and group by does not spread items evenly across threads

### ISSUE THREAD

**Issue by lennehendrickx** [ReactiveX/RxJava#5908]
Library version: 2.1.10

I am implementing a partitioning strategy using RxJava 2.
My first implementation was using the recently added parallel operator in combination with the groupBy operator.
But when running a test I see that items in a group are not always handled by the same thread.
And that threads are not handling an equal amount of items.
Is there something I am missing?

```
/**
 * Test fails.
 * Expected behavior: processing is evenly distributed accross 4 threads.
 * Example distribution for one test run: [801, 73, 71, 55]
 */
@Test
public void groupByWithParallel() {

    ConcurrentHashMap<String, Integer> threadProcessingCount = new ConcurrentHashMap<>();

    // GIVEN
    Flowable<Integer> flowableWithGroupByAndParallel = Flowable.just(1, 2, 3, 4)
            .repeat(250)
            .groupBy(number -> number % MAX_NUMBER_OF_THREADS)
            .parallel()
            .runOn(Schedulers.io())
            .flatMap(group -> group.doOnNext(number -> {
                printThreadAnNumber(number);
                increaseThreadProcessingCount(threadProcessingCount);
            }))
            .sequential();

    // WHEN
    flowableWithGroupByAndParallel
            .test()
            .awaitTerminalEvent();

    // THEN
    assertThat(threadProcessingCount.values()).containsExactly(250, 250, 250, 250);

}

private static void printThreadAnNumber(Integer number) {
    System.out.println(Thread.currentThread().getName() + " " + number);
}

private static void increaseThreadProcessingCount(ConcurrentHashMap<String, Integer> threadCallCount) {
        threadCallCount
                .compute(currentThread().getName(),
                        (thread, count) -> ofNullable(count).map(previousCount -> ++previousCount).orElse(1));
}
```

A have made a second attempt with flatMap and subscribeOn, but this also did not result in the expected bahavior.

```
/**
 * Test fails.
 * Expected behavior: processing is evenly distributed accross 4 threads.
 * Example distribution for one test run: [801, 73, 71, 55]
 */
@Test
public void flatMapWithSubscribeOn() {

    ConcurrentHashMap<String, Integer> threadCallCount = new ConcurrentHashMap<>();

    // GIVEN
    Flowable<Integer> flowableWithFlapMapAndObserveOn = Flowable.just(1, 2, 3, 4)
            .repeat(250)
            .groupBy(number -> number % MAX_NUMBER_OF_THREADS)
            .flatMap(group -> group.subscribeOn(Schedulers.io()).doOnNext(number -> {
                printThreadAnNumber(number);
                increaseThreadProcessingCount(threadCallCount);
            }));

    // WHEN
    flowableWithFlapMapAndObserveOn
            .test()
            .awaitTerminalEvent();

    // THEN
    assertThat(threadCallCount.values()).containsExactly(250, 250, 250, 250);

}

private static void printThreadAnNumber(Integer number) {
    System.out.println(Thread.currentThread().getName() + " " + number);
}

private static void increaseThreadProcessingCount(ConcurrentHashMap<String, Integer> threadCallCount) {
        threadCallCount
                .compute(currentThread().getName(),
                        (thread, count) -> ofNullable(count).map(previousCount -> ++previousCount).orElse(1));
}
```

However when I use flatMap with observeOn the partitioning seems to work fine.

```
/**
 * Test succeeds.
 */
@Test
public void flatMapWithObserveOn() {

    ConcurrentHashMap<String, Integer> threadCallCount = new ConcurrentHashMap<>();

    // GIVEN
    Flowable<Integer> flowableWithFlapMapAndObserveOn = Flowable.just(1, 2, 3, 4)
            .repeat(250)
            .groupBy(number -> number % MAX_NUMBER_OF_THREADS)
            .flatMap(group -> group.observeOn(Schedulers.io()).doOnNext(number -> {
                printThreadAnNumber(number);
                increaseThreadProcessingCount(threadCallCount);
            }));

    // WHEN
    flowableWithFlapMapAndObserveOn
            .test()
            .awaitTerminalEvent();

    // THEN
    assertThat(threadCallCount.values()).containsExactly(250, 250, 250, 250);

}

private static void printThreadAnNumber(Integer number) {
    System.out.println(Thread.currentThread().getName() + " " + number);
}

private static void increaseThreadProcessingCount(ConcurrentHashMap<String, Integer> threadCallCount) {
        threadCallCount
                .compute(currentThread().getName(),
                        (thread, count) -> ofNullable(count).map(previousCount -> ++previousCount).orElse(1));
}
```

I have setup a repository with the test setup [here](https://github.com/lennehendrickx/rxpartitioning/blob/master/src/test/java/rx/test/RxPartitioningTest.java)

**Comment by akarnokd** [comment]
The `parallel` operator uses a round-robin dispatching strategy which distributes work based on demand on each rail. This can lead to uneven processing per rail as the speed at each rail processes items will affect how often they get more items. You can somewhat affect this by reducing the prefetch used by the `runOn` operator.

In this particular case, you are talking to groups fed by, likely main thread so that `doOnNext` invocation doesn't come from the rail `runOn` executes the `flatMap`. If you'd printed the map, you'd see what threads are involved. Note also that by default, certain operations running on some thread may drag the production of items to their thread unless the source is pinned by `subscribeOn` which reroutes the backpressure requests to the dedicated Scheduler. That's why you see multiple thread counts instead of just the main thread for example.

Using `subscribeOn` on a `GroupedFlowable` has no practical effect because it is backed by a hot `UnicastProcessor`; items are emitted from the sender thread. As you correctly discovered, the right operator is `observeOn`.

The `groupBy.flatMap` is balanced based on the numbers each group will receive due to that modulo keying. However, unlike `parallel`, this may lead to uneven time consumption and CPU utilization.

**Comment by lennehendrickx** [comment]
Thank you for the fast and detailed response. 
This solution may indeed lead to uneven time consumption and CPU utilization. For our use case this is the expected behaviour because we need items with the same partition key to be treated sequentially (on the same thread).
