### ISSUE TITLE
Question about availability of SerializedSubject class

### ISSUE THREAD

**Issue by pwittchen** [ReactiveX/RxJava#5909]
Hi,

In the wiki here: https://github.com/ReactiveX/RxJava/wiki/Subject#serializing we can read about `SerializedSubject`. Nevertheless, in the latest version of [SerializedSubject.java](https://github.com/ReactiveX/RxJava/blob/51dd03b470d52509eb1835a55801c34e6efbb1d7/src/main/java/io/reactivex/subjects/SerializedSubject.java) file, I've noticed that this class is package private, so I cannot use it outside the RxJava library. Is it done on purpose? Is there any reason because of which this class cannot be used by projects depending on RxJava?

Regards,
Piotr

**Comment by akarnokd** [comment]
Most of the wiki is outdated and references 1.x components. It will be updated after 1.x EOL.

`SerializedSubject` was made private because there was no real reason to expose it as a class. You can get it to wrap a `Subject` implementation by simply calling [`toSerialized`](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/subjects/Subject.java#L71). Also there is no reason not to extend `Subject` provided by RxJava when implementing a custom one.

**Comment by pwittchen** [comment]
Ok, thanks. Now, it's clear. :-)
