### ISSUE TITLE
2.x: Concat operator, Maybes, and threading

### ISSUE THREAD

**Issue by schmist** [ReactiveX/RxJava#6093]
Following code sample (Kotlin 1.2.51, RxJava 2.1.16):
```kotlin
val m1 = Maybe.just(1).subscribeOn(Schedulers.io())
val m2 = Maybe.just(1).subscribeOn(Schedulers.io())

val m3 = m1
    .concatWith(m2)
    .firstElement()
    .map { Thread.currentThread().name }

var counter = 0
var counterMain = 0

(0 until 10000)
    .forEach { if (m3.blockingGet() == "main") counterMain++ else counter++ }

println("Result: main $counterMain, other $counter, sum ${counterMain + counter}")
````
leads to the following in-deterministic (main number is different for each run) result:
```Result: main 13, other 9987, sum 10000```

It seems that the result of the `concat` operator sometimes runs on the calling thread, even if the participating Maybes use specific schedulers. I could not reproduce this behavior for Observables or Singles. Is this intended behavior and the resulting thread cannot be guaranteed or could it be a bug?

**Comment by akarnokd** [comment]
This is a peculiarity of the backpressure inside the `concatArray` operator `concatWith` builds upon. If the first source is fast, the drain loop running on the main thread may get the success value and push it to downstream still on the main thread. You have to use `observeOn` before `map` to make sure the right thread is used or apply `subscribeOn` just after `concatWith` so that the drain loop is no longer invoked on the main thread if the above race condition happens.

**Comment by schmist** [comment]
Thanks for the quick answer!

Since I cannot reproduce it for `Single` and `Observable`, and there are different `concatArray` implementations for `Flowable` and `Completable`, is the assumption correct that this peculiar behavior only exists for `Maybe` sources?
Is this due to the nature of `Maybe` and cannot be changed or could it be fixed somehow so that all observable sources act the same?

**Comment by akarnokd** [comment]
This is a `Maybe` specific property as it has a dedicated implementation. `Single` is converted to `Flowable` and `Flowable.concat` is used where the code path is longer for the emission. Try with `Schedulers.single()` for those other implementations so that the scheduling window is minimal.

**Comment by akarnokd** [comment]
To be clear, concatenating `Observable`s doesn't have this effect because there is no backpressure to coordinate the emissions with. Each source emits from its thread which passes through the `concat` operator. With `Flowable`, emissions may be held off or simply cached until the value can be retrieved, but this can happen on any participating threads. That's why to ensure proper reception of items, one should use `observeOn` before such `map`s to make sure no matter where the value originated, it continues on the desired thread (until the next async boundary).

**Comment by schmist** [comment]
Ok, many thanks for your answers!
