### ISSUE TITLE
Gradle build error just as the error info from the part of README

### ISSUE THREAD

**Issue by MarcSteven** [ReactiveX/RxJava#6108]
Pls change the read me about the setup library into the project
The reason as below:
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018，pls see http://d.android.com/r/tools/update-dependency-configurations.html,
So pls use implementation instead of compile in the correct position...

**Comment by akarnokd** [comment]
I don't understand what you are talking about. We have `api` and `implementation` for some time now: https://github.com/ReactiveX/RxJava/blob/2.x/build.gradle#L67

**Comment by MarcSteven** [comment]
@akarnokd  I mean you should update the readme -about the set up library ,you write like that  compile :"",you should change it to - implement "",it works well

**Comment by akarnokd** [comment]
PR welcome.

**Comment by sircelsius** [comment]
I believe that @MarcSteven is referring to changing the project's README's ["Setting up the dependency"](https://github.com/ReactiveX/RxJava/blob/2.x/README.md#setting-up-the-dependency) section to use `api` or `implementation` instead of `compile`.

I'll open a PR, but I'm not super familiar with the differences between `api` and `implementation`.
