### ISSUE TITLE
rxjava2[2.1.8] delay Operation invalid when Turn off the screen  for a while

### ISSUE THREAD

**Issue by lckj686** [ReactiveX/RxJava#6115]
I used rxjava2[2.1.8] delay Operation in my  Foreground Service 。Normal use ok， but when Turn off the screen  for a while ，delay Operation cannot work，but the takeUntil Operation can use to cancel the invalid delay。my code：

      Observable.just(1).delay(downtime, TimeUnit.SECONDS)
                .doOnDispose({
                    //valid all the time
 
                })
                .takeUntil(observable)
                .subscribe({
                    request()
                })

**Comment by TarasMazepa** [comment]
RxJava doesn't have any Android specific integration. If your code is not working in some tricky Android OS situations it usually means that you are doing something wrong with Android Sdk integration. In your case it could be one of the following:
1. Your service is not ready for sporadic restarts from OS
2. Your service doesn't aquire wake lock
3. Consider using JobDcheduler to schedule some work instead of doing it with RxJava. JobScheduler will execute work even if your service/app is killed

**Comment by iNoles** [comment]
RxAndroid

**Comment by TarasMazepa** [comment]
RxAndroid provides Android specific schedulers but have no effect on operators

**Comment by akarnokd** [comment]
Please ask such platform specific questions on StackOverflow.

**Comment by lckj686** [comment]
thanks @TarasMazepa    ，I'll refer to your ideas
