### ISSUE TITLE
[RxJava2.x] Why is Observable  Reactive class

### ISSUE THREAD

**Issue by CoXier** [ReactiveX/RxJava#6126]
As you say:

> RxJava is a Java VM implementation of Reactive Extensions.

And from RS [README](https://github.com/reactive-streams/reactive-streams-jvm#3-subscription-code), I know there is a class Subscription in `RS`. However in `RxJava2.x` the class `Disposable` between Observable/Observer seems not follow `RS` specification.

In addition, can you explain : "The specification itself has evolved out of RxJava 1.x and provides a common baseline for reactive systems and libraries."

**Comment by CoXier** [comment]
Same question for Single, Maybe andCompletable.

**Comment by CoXier** [comment]
I think it should be discussed on StackOverflow. So I will close this issue.

**Comment by akarnokd** [comment]
Java does not have extension methods and using static methods to transform within and between reactive base types is very cumbersome. 

For example, imagine you'd have to write like this everywhere:

```java
Observable<Integer> o1 = Observable.range(1, 10);
Observable<Integer> o2 = Observable.map(o1, a -> a + 1)
Observable<Integer> o3 = Observable.filter(o2, a -> a % 2 == 0)
Observable.subscribe(o3, v -> System.out::println, e -> e.printStackTrace());
```

The next closest thing to establishing a fluent API is to have the base types be implemented in classes and have the operators as instance methods.

```java
Observable.range(1, 10)
    .map(o1, a -> a + 1)
    .filter(o2, a -> a % 2 == 0)
    .subscribe(v -> System.out::println, e -> e.printStackTrace());
```

The middle ground is the `compose()` operator that allows applying static operators but still in a fluent manner:

```java
Observable.range(1, 10)
   .compose(o -> SomeExtension.mapFilter(o, v -> v % 2 == 0, v -> v + 1))
    .subscribe(v -> System.out::println, e -> e.printStackTrace());
```

> And from RS README, I know there is a class `Subscription` in RS. 

[`Subscription`](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/api/src/main/java/org/reactivestreams/Subscription.java#L22) in the Reactive Streams specification **is an interface**, check again.

> However in RxJava2.x the class `Disposable` between `Observable`/`Observer` seems not follow RS specification.

How can you tell that by the way? `Disposable` was derived from `Subscription` by removing the `request` method, and thus all the rules governing backpressure because its use is in non-backpressured reactive types.

> The specification itself has evolved out of RxJava 1.x and provides a common baseline for reactive systems and libraries.

What explanation do you expect?

**Comment by CoXier** [comment]
> Subscription in the Reactive Streams specification is an interface, check again.

Sorry I made a mistake. Now I know `Disposable` was derived from `Subscription`, thanks a lot.

> What explanation do you expect?

I want to know why `The specification itself has evolved out of RxJava 1.x.`, can you hold some example ?

Another thing is that have you ever thought split RxJava into several parts such as `Flowable`, `Observable` and so on to reduce method count.

**Comment by akarnokd** [comment]
> can you hold some example ?

Why do you want to know? RxJava has introduced the `Observer` with its `onNext`, `onError` and `onCompleted` methods. The spec took it and expanded it with `onSubscribe` . Also RxJava introduced the `Producer` interface along with `Subscription`, which was then combined by the spec into `Subscription`.

> Another thing is that have you ever thought split RxJava into several parts such as Flowable, Observable

Yes. It was a maintenance nightmare and the cross combinations required for different types working together exploded. 

> reduce method count

RxJava 2 ProGuards pretty well so no real need to split the library for Android use. Other platforms typically don't care about method counts.

Besides, there are typically two complaints about RxJava: why there are so many methods and why isn't there an operator that solves my problem directly.

**Comment by CoXier** [comment]
> Why do you want to know? 

I love RxJava very very much. I want to know it , not only just use it.

> Besides, there are typically two complaints about RxJava: why there are so many methods and why isn't there an operator that solves my problem directly.

Actually it does magic work in my development. But there is a problem that many people do not know how to use RxJava to solve problems. LOL.  Maybe many people only see RxJava can help us to do async work.
