### ISSUE TITLE
onErrorComplete operator for Observable

### ISSUE THREAD

**Issue by bio007** [ReactiveX/RxJava#6186]
I would like to open a discussion (hear the opinions) on the reason why there is no onErrorComplete for Observable. There is such a operator on Maybe and I think it can be sometimes useful on Observable as well. It's no big deal to use Observable to Maybe workaround or `Observable.onErrorResumeNext(Observable.empty())`.

Still it would be more straightforward with designated operator.

**Comment by akarnokd** [comment]
There is no particular reason. `Maybe` and `Completable` have got their methods defined way after `Observable`. At the time, it looked a reasonable addition for such 0..1 element sources. Note that they have `Predicate`d overloads so that suppression of an error can be at least conditional.

Pros:
- convenience

Cons:
- relatively short workaround exists
- would make suppressing exceptions too easy
- uncertain about the value added vs. maintenance cost

Recommended:
- use the workaround (perhaps turned into a transformer).

**Comment by bio007** [comment]
Ok thanks for the input. I agree there is a short workaround even though I think not so obvious for someone not experienced with rx. Just wanted to hear someone's else opinion, thanks 👍
