### ISSUE TITLE
RxJava 2.2.1 and 2.2.2 have problem with proguard

### ISSUE THREAD

**Issue by giang29** [ReactiveX/RxJava#6212]
Today I updated RxJava version to 2.2.2, and then I couldn't build my app because proguard gives me some warning:
```
Warning: library class io.reactivex.internal.operators.completable.CompletableDisposeOn$CompletableObserverImplementation extends or implements program class io.reactivex.CompletableObserver
Warning: library class io.reactivex.internal.operators.completable.CompletableDisposeOn$CompletableObserverImplementation extends or implements program class io.reactivex.disposables.Disposable
Warning: library class io.reactivex.internal.operators.completable.CompletableResumeNext$ResumeNext extends or implements program class io.reactivex.CompletableObserver
Warning: library class io.reactivex.internal.operators.completable.CompletableResumeNext$ResumeNext$OnErrorObserver extends or implements program class io.reactivex.CompletableObserver
Warning: library class io.reactivex.internal.operators.observable.ObservableWithLatestFrom$WithLastFrom extends or implements program class io.reactivex.Observer
Warning: library class io.reactivex.internal.operators.single.SingleContains$Single extends or implements program class io.reactivex.SingleObserver
```
AFAIK, RxJava 2 doesn't require any proguard configuration, so how can I resolve this?
P/s: I also tried to use v2.2.1, but it didn't work either. Only rolling it back to 2.2.0 helped

**Comment by akarnokd** [comment]
I have no idea. There were internal changes which should not affect any usage or compilation. Maybe you have to clear some ProGuard or build caches.

**Comment by JakeWharton** [comment]
This is not a problem with RxJava but of your build configuration. See https://issuetracker.google.com/issues/73122476. Basically you have two versions of RxJava in your classpaths. One transitively as an implementation detail and the other directly which are not the same version. The fix is to either use a Gradle resolutionStrategy to force the same version everywhere or you just update your transitive dependencies. You can also update to AGP 3.3 alpha 10 which fixes this automatically by reconciling the version different on both classpaths automatically.

No action for RxJava to take.

**Comment by giang29** [comment]
Thanks @JakeWharton 
I 'll give it a try 😄

**Comment by giang29** [comment]
Fixed by resolutionStrategy
