### ISSUE TITLE
TestObserver.assertEmpty asserts that the stream has not completed.

### ISSUE THREAD

**Issue by amadeu01** [ReactiveX/RxJava#6247]
- Version: 2.2.2

 ```java
    @Test
    public void testEmpty() {
        TestObserver testObserver = new TestObserver();
        Maybe.empty()
                .subscribe(testObserver);

        testObserver.awaitTerminalEvent();

        testObserver.assertEmpty();
    }
```

As in the [documentation](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#empty()) we can find that :
> `empty()`
> Returns an Observable that emits no items to the Observer and immediately invokes its onComplete method.

However the `assertEmpty()`

```java
     public final U assertEmpty() {
        return assertSubscribed()
                .assertNoValues()
                .assertNoErrors()
                .assertNotComplete();
    }
```

Asserts that the stream has not completed, but on the documentation says that the empty() method will invokes `onComplete`. So, is that right to assert that the observer has not completed?

**Comment by akarnokd** [comment]
`assertEmpty` is there to check for no items or terminal signals whatsoever, so that the test consumer is empty of signals. It is the source of some confusion and we may change the name in 3.x to better reflect the intention. Use `assertResult` for checking for no-items completion and `assertEmpty` for no signals:

```java
Maybe.empty()
.test()
.assertResult();

Maybe.never()
.test()
.assertEmpty();
```
