### ISSUE TITLE
Maybe support for nulls

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#6271]
I would like to propose APIs for `Maybe` that relax the rules around the handling of nulls.  Similar to `java.util.Optional.ofNullable`. For example but limited to:

* `Maybe.justNullable` If the item passed in is null return empty.
* `Maybe.mapNullable` allow the mapper to return null and have it map to empty without having to use flatMap.
* `Maybe.zipArrayNullable` allow the array passed to the zipper to contain null values if the Maybes zipped are empty rather than eagerly zipping to empty.

**Comment by akarnokd** [comment]
> `Maybe.justNullable`

A static method can live anywhere and since this would take a constant reference known upfront, there is not much benefit over `value != null ? just(value) : empty()`.

> `Maybe.mapNullable`

The problem with null returns is that you may accidentally return null due to bad API usage, then spend the next hour hunting down empty sources. I suggest implementing a `MaybeTransformer` for yourself if you want to save on the cost of `flatMap`.

> `Maybe.zipArrayNullable`

Again, static methods can live anywhere and the usage case sounds very peculiar. We don't balance out the Observable/Flowable zips either.

**Comment by abersnaze** [comment]
> constant reference known upfront

not necessarily. I'm getting a return value from a function that I have to store in a variable and messes with the chaining of operators.

> due to bad API usage

hence the different API rather than changing the existing just/map/zip APIs.

> usage case sounds very peculiar

I'm finding it hard to come up with use case for how it is currently implemented. I've found that zip is only really useful when you can guaranty the number of items in each.

**Comment by akarnokd** [comment]
> Maybe.justNullable

I meant constant reference known upfront before RxJava gets involved:

```java
final T value = someApi()
return value != null ? Maybe.just(value) : Maybe.empty();
```

So in other terms, it is not the responsibility of the operator itself to come up with `value`. All in all, this is something you can have it yourself outside RxJava:

```java
public final class MaybeEx {
    public static <T> Maybe<T> ofNullable(T value) {
        return value != null ? Maybe.just(value) : Maybe.empty();
    }
}
```

> Maybe.mapNullable

I'd say it is a corner case of a map+filter operator. I definitely don't want to add standard operators that require the user to provide null to indicate emptiness as it makes the RxJava inconsistent. If you need such operator for yourself, I suggest having a transformer. Otherwise, I suggest an emitter-like callback instead:

```java
public <T, R> Maybe<R> mapFilter(BiConsumer<? super MaybeSimpleEmitter<R>, T> handler);

interface MaybeSimpleEmitter<T> {
   void onSuccess(T item);
   void onError(Throwable ex);
   void onComplete();
}
```
This can be implemented relatively thinly.

> Maybe.zipArrayNullable

Apart from a very few places, we don't want to give out nulls to user code. This you can implement outside RxJava due to it being a static method. 

There could be workarounds with existing operators such as having `Notification` wrapping:

```java
Maybe<Notification<T>> one = source
    .map(Notification::createOnNext)
    .defaultIfEmpty(Notification::createOnComplete);
...

Maybe.zip(one, two, three, (a, b, c) -> {
    T aValue = null;
    if (a.isOnNext()) aValue = a.getValue();
    ...
})
```

Note that unlike the multi-valued sources, `Maybe`s and `Single`s are already relatively high cost operators to use repeatedly and an extra allocation doesn't add that much of an overhead.

I'm willing to have `Maybe.materialize` (& dematerialize) for this purpose.

The other approach would be a zip variant with an API to query which source is empty:

```java
static <T, R> Maybe<R> zipArrayNotification(
    BiConsumer<MaybeSourceNotifications<T>, MaybeSimpleEmitter<R>> handler, 
    Maybe<T>... sources
);

interface MaybeSourceNotifications<T> {
   int size();
   boolean isComplete(int index);
   boolean isError(int index);
   boolean isSuccess(int index);
   T getValue(int index);
   Throwable getThrowable(int index);
}
```

**Comment by abersnaze** [comment]
It’s clear that `java.util.Optional` thought it important enough to support. 

Anyway I’ve since copied and modified the 7 classes necessary to implement the static zipNullable into my own project.

Should anyone else need these they can reopen.
