### ISSUE TITLE
Wiki improve: Observable.fromArray()

### ISSUE THREAD

**Issue by worstkiller** [ReactiveX/RxJava#6435]
Hey guys just  a little suggestion over the use of
 `Observable.fromArray()` 
in wiki pages,
 seems to have used the
 `Observable.fromIterable(list);` instead of `Observable.fromArray(array);`
Here is link to page 
https://github.com/ReactiveX/RxJava/wiki/Creating-Observables#fromarray
Please change if applicable thanks.

**Comment by akarnokd** [comment]
Hi, you can post a PR against https://github.com/ReactiveX/RxJava/blob/2.x/docs/Creating-Observables.md

**Comment by lorenzpahl** [comment]
I would like to add that there are more issues on that wiki page that could be resolved along with the mentioned problem:

- Missing parentheses in the second [`just`](https://github.com/ReactiveX/RxJava/blob/2.x/docs/Creating-Observables.md#just) example: `error.printStackTrace` instead of `error.printStackTrace()`.
- [`fromFuture`](https://github.com/ReactiveX/RxJava/blob/2.x/docs/Creating-Observables.md#fromfuture-example), [`create`](https://github.com/ReactiveX/RxJava/blob/2.x/docs/Creating-Observables.md#create-example): `Executors.newSingleThreadedScheduledExecutor()` instead of `Executors.newSingleThreadScheduledExecutor()`.
- [`range`](https://github.com/ReactiveX/RxJava/blob/2.x/docs/Creating-Observables.md#range-example): typo `erro`. `Char` should be `Character`.
- [`error`](https://github.com/ReactiveX/RxJava/blob/2.x/docs/Creating-Observables.md#error-example): variable `error` is defined twice.

**Comment by worstkiller** [comment]
hey @akarnokd  i just opened a PR with included suggestions from @lorenzpahl also.
https://github.com/ReactiveX/RxJava/pull/6436
Please merge them.
Thanks 😃
