### ISSUE TITLE
Add ability to pass a Context object as a replacement to ThreadLocal

### ISSUE THREAD

**Issue by graemerocher** [ReactiveX/RxJava#6484]
It is currently extremely complex to instrument RxJava 2 (see for reference Zipkin's instrumentation for RxJava 2 - https://github.com/apache/incubator-zipkin-brave/pull/665/files) if you wish to trace, or modify behaviour across a reactive flow.

Reactor solves this problem through a `Context` object https://projectreactor.io/docs/core/release/reference/#context

There is no similar construct that I am aware of for RxJava 2.

Third partly library authors could probably add instrumentation such that a `Context` could be simulated, but it feels like something that should be included within RxJava directly.

This issue asks that such a feature be considered for inclusion and opens the discussion about the possibility of the feature.

The context for this is that we use RxJava 2 in Micronaut and prefer to maintain it as the default Reactive library, but have requirements that more and more require the `Context` notion (security, tracing, transactions etc.) and would prefer to reduce the amount of instrumentation code we have to maintain. 

The code that we do have is based off of the Zipkin approach, but it has disadvantages in that it significantly increases stack trace sizes due to the inclusion of all of the instrumentation stack frames.

This may be going over ground already covered in #2885 but that issue was really closed without resolution.

**Comment by akarnokd** [comment]
We have no plans to introduce context ourselves; Reactor has gone into that direction. I haven't looked at their implementation, but I see issue reports implying logical problems with their approach, not to mention, the traveling-upstream nature of the solution.

**Comment by graemerocher** [comment]
Ok, do you have any suggestions for simplification regarding instrumentation? We can of course maintain our own instrumentation as an alternative. 

Since we only really publicly expose Reactive Streams another option is to switch to Reactor, but we are not hugely keen on that idea as we would like to continue to support Android and RxJava 2 in general.

**Comment by akarnokd** [comment]
I have no experience with instrumentation. There are the standard hooks or you do some extensive bytecode reengineering of some sorts.

**Comment by graemerocher** [comment]
Ok, thanks for your input.

**Comment by akarnokd** [comment]
Context support is out-of-scope for RxJava for the foreseeable future. If Reactor-Core is not workable in the given target environment, I suggest creating a small reactive library based on RxJava's base interfaces (i.e., `ContextFlowable`) that has DSL with the necessary operators adapted from RxJava proper.

**Comment by lukaseder** [comment]
I've found this issue here while researching a vaguely related topic: https://github.com/jOOQ/jOOQ/issues/13704 (how to shoehorn aspect oriented transaction context into third party libraries, such as jOOQ), and I've come to the conclusion that if a "context" should be made available throughout reactive streams, then it best be added to the `org.reactivestreams` SPI and covered by the TCK.

An implementation based solution like that by reactor might work for reactor-only environments, but that means that the SPI itself is insufficient as a "standard" for interoperability in such environments.

A third party library like jOOQ can't be based on specific implementations. The reactive streams SPI is the only reason why a third party like jOOQ even considered going reactive, and the integration has worked quite well so far. Supporting non-SPI provided contexts doesn't work for such third parties, so I hope folks who are interested in this will lobby with the SPI maintainers to add optional contexts to e.g. `org.reactivestreams.Subscriber`.

**Comment by akarnokd** [comment]
This can't be solved on our level. The best you could do currently is to bring along the context in a composite type, provided every step from source to consumer can deal with it and pass it along. I have my doubts the reactive spec would be extended into this direction in the foreseeable future.
