### ISSUE TITLE
Schedulers.io() reuses blocked threads in RxJava 2

### ISSUE THREAD

**Issue by DrMetallius** [ReactiveX/RxJava#6542]
This exact issue: #4230 happens to us in RxJava 2.2.5. `IoScheduler.EventLoopWorker` calls `tasks.dispose()` and then immediately releases the worker to the pool regardless of whether it has completed or not.

In our case we have a network socket operation, which obviously doesn't respond to interrupts. That results in other operations randomly getting stuck until the network operation either completes or times out. Needless to say, that's rather frustrating and wasn't easy to debug.

Please pull the fix into RxJava 2 as well.

**Comment by akarnokd** [comment]
The fix is to use `Schedulers.newThread` or a custom `Schedulers.from(ExecutorService)`-based pool that you are comfortable blocking uninterruptibly.

There were trouble with changing the behavior as it resulted in excess IO worker creation and eventually running out of memory.

**Comment by DrMetallius** [comment]
`Schedulers.newThread` is a non-ideal solution since threads are not reused with that implementation. `Schedulers.from(ExecutorService)` can't be used since it doesn't support cancellation which we are actively using. There is a new method, `Schedulers.from(ExecutorService, boolean)`, but it's experimental and we avoid using non-stable APIs in the project.

I realize that creating and disposing uninterruptible operations could lead to spawning an unlimited number of threads, but I/O scheduler is supposed to be unbounded, so it's the user's responsibility to not have too many requests in any case when using this scheduler. This is explicitly documented in Javadocs, as I've just checked.

The current behavior basically leads to randomly blocking one of the operations which happens to have gotten the worker which hasn't finished yet. This can happen regardless of how many operations are done in parallel, any disposed uninterruptible operation can trigger this. At the very least this should be documented, because this behavior is very surprising and it's difficult to understand what's happening and why tasks randomly stop to be processed.

If the goal is to have a scheduler which has limits on how many threads it spawns, there should just be a separate scheduler with a bounded number of threads and a queue. Maybe stabilize `Schedulers.from(ExecutorService, boolean)` and provide another scheduler through it with a preconfigured pool for I/O tasks.

The only viable solution I see for us right now is to put the uninterruptible parts of the operations onto a regular executor while using `Future.get()` to block the threads coming from Rx schedulers. That way we forego using RxJava for the uninterruptible parts. This is rather inconvenient, especially considering that we aren't doing anything out of the ordinary, this is just regular network access, which is inherently uninterruptible.

**Comment by akarnokd** [comment]
> Schedulers.from(ExecutorService) can't be used since it doesn't support cancellation

[Schedulers.from(Executor) docs says](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#from-java.util.concurrent.Executor-):

"cancelling tasks scheduled by this scheduler **can't be interrupted** when they are executing but only prevented from running prior to that"

If you don't mix interruptible and non-interruptible work, then it should work for you.

> At the very least this should be documented, because this behavior is very surprising and it's difficult to understand what's happening and why tasks randomly stop to be processed.

PR welcome.

> should just be a separate scheduler with a bounded number of threads and a queue. Maybe stabilize 

You can create custom schedulers, for example, taking the `Schedulers.from(ExecutorService, boolean)` implementation by source so in case of a very unlikely removal in 2.2.11, you don't lose code. Also this `from` method will be stabilized in the next major release, 3.x.

> network access, which is inherently uninterruptible

You could also look for alternative network access tools/libraries that can be interrupted. Otherwise, isolating such uninterruptible parts is a good idea.

**Comment by DrMetallius** [comment]
> cancelling tasks scheduled by this scheduler can't be interrupted when they are executing but only prevented from running prior to that

That's exactly what I meant, they can be canceled before they are started, but not after that. With network-related tasks, they can be (and often are) interrupted in-between the network requests, but not during them.

> You can create custom schedulers, for example, taking the Schedulers.from(ExecutorService, boolean) implementation by source

Maybe I misunderstood something, but the implementation simply does the following: `new ExecutorScheduler(executor, interruptibleWorker)`. `ExecutorScheduler` is a class in the internal package and it uses a lot of other internal stuff as well. Are you suggesting using internal classes directly? Or you are proposing dragging `ExecutorScheduler` and all of its internal dependencies into the project as well?

> You could also look for alternative network access tools/libraries that can be interrupted.

That's a huge undertaking for the project. If we are switching the libraries we use for networking, we might as well migrate away from RxJava instead.

**Comment by akarnokd** [comment]
> Or you are proposing dragging ExecutorScheduler and all of its internal dependencies into the project as well?

Yes. 

You don't have many options left. If we'd change stuff around to better suit your use case, we have to introduce those changes/components as experimental. You declared you won't use experimental API so that doesn't work. Somebody could create a custom scheduler for you in an external library, but then that would be mostly the extracted code anyway. Then you introduce another library and support wildcard into your project which is a risk again.

**Comment by DrMetallius** [comment]
We do have another option, there is a solution described in my second comment which involves moving network calls off Rx threads. That's inconvenient though, and I was hoping that this behavior of `Schedulers.io` would be fixed, but based on what I've heard so far, it isn't considered a bug despite that it is random, undocumented, and breaks quite common use cases. In that case, of course, we can only think of workarounds.

**Comment by filipwiech** [comment]
Maybe this is something that could be remedied in 3.x?

**Comment by akarnokd** [comment]
@MatushkaRossiya This is generally unsolvable with a standard scheduler like `io`: either you hang behind a blocking action or run out of memory because workers can't be released fast enough. So you have to write a custom scheduler or find a network library that responds to interruption. In fact, I can't imagine which network library would block uninterruptibly, some proprietary one?

**Comment by DrMetallius** [comment]
@akarnokd Why not make a queue and limit the number of workers servicing the queue? Until the queue is full, nothing gets blocked, and the memory doesn't get used up by all the workers. Unless there's something I don't know about this approach, this seems like an obvious solution to me. Generally unbounded number of workers is useful in cases where we'd rather run out of memory than block anything, but since the current approach can cause blocking even with one worker, that doesn't seem to be the goal here.

> In fact, I can't imagine which network library would block uninterruptibly, some proprietary one?

OkHttp calls are uninterruptible if you work with it synchronously. Basically anything that directly calls `Socket.connect` is uninterruptible because it evenutally makes native system calls, which can't respond to interruption and can only be canceled by closing the socket from some other thread.

I'm not sure why it is assumed that interruption is supported by default. It is a cooperative mechanism by design, as opposed to thread stopping in the first versions of Java. As a result interruption support has to be specifically implemented where required.

**Comment by akarnokd** [comment]
> Why not make a queue and limit the number of workers servicing the queue?

That's what `Schedulers.from(Executor)` does. Again, you can implement a custom Scheduler with the desired behavior or move the problematic calls outside RxJava.

> Unless there's something I don't know about this approach

Thread locality. Avoiding thread hops in subsequent items improves performance, reduces power consumption.

> which can't respond to interruption and can only be canceled by closing the socket from some other thread.

How do you bridge OkHttp and RxJava? Sounds like you have to fix the bridge to close the socket upon cancellation, which should unblock `connect` or post a bug report to whatever bridge library you are using.

> I'm not sure why it is assumed that interruption is supported by default.

Because it is available and usually works. For the rest, there should be a way to close/unblock something in case interruption doesn't work.

**Comment by DrMetallius** [comment]
> That's what Schedulers.from(Executor) does. Again, you can implement a custom Scheduler with the desired behavior or move the problematic calls outside RxJava.

Yes, we'll have to do the latter. I've already explained why `Schedulers.from` isn't suitable.

> Thread locality. Avoiding thread hops in subsequent items improves performance, reduces power consumption.

But the behavior shouldn't be any different than without the queue until the number of workers hits a certain limit.

> How do you bridge OkHttp and RxJava?

We don't. They don't directly interact, Rx is only used for UI and the logic directly beneath it, network operations are deep within the application core. So we'd have to implement interruption of ongoing calls solely to satisfy the (undocumented) requirements imposed on us by Rx, which isn't even a part of the core.

> Because it is available and usually works.

I've just explained why it's *not* available by default. Moreover, for example, Android calls sometimes swallow the interruption flag, so additional work has to be done to make sure this doesn't happen even if your code behaves correctly.

> For the rest, there should be a way to close/unblock something in case interruption doesn't work.

We don't need this mechanism on its own. It's not a problem for us if there are a couple of threads in the background blocked on a network call until they time out a bit later. It becomes a problem solely when Rx starts scheduling other work onto these threads which can't service other tasks immediately.

**Comment by akarnokd** [comment]
> Yes, we'll have to do the latter.

Great!

Please note that RxJava is an open source project maintained by volunteers and experts on their free time, who are involved in concurrency-related design and implementation considerations for years now. Since RxJava has to support a wide variety of use cases, we often have to make tradeoffs that may end up causing trouble to some. This is why there are extension points and customization options, such as `Scheduler` parameters so that corner cases can be worked around locally without the need to change or disrupt the entire library and project. 

You are, of course, welcome to post a PR detailing this particular corner case with the `io` scheduler in the documentation.

**Comment by DrMetallius** [comment]
> who are involved in concurrency-related design and implementation considerations for years now

That's an appeal to authority.

> we often have to make tradeoffs that may end up causing trouble to some

Except in this case there is a solution with a queue, which shouldn't disrupt anything as I explained in the previous comment.

> You are, of course, welcome to post a PR detailing this particular corner case with the io scheduler in the documentation.

When I have my free time, maybe I'll do that, but I'd rather fix the underlying issue than describe in the documentation that any task may be randomly blocked.

By the way, just in case someone stumbles upon this bug, here's the minimum example:

    Completable.fromCallable {
        Socket().connect(InetSocketAddress("10.255.255.1", 80), 10000)
    }
        .subscribeOn(Schedulers.io())
        .subscribe()
        .dispose()

    Completable.complete()
        .subscribeOn(Schedulers.io())
        .blockingAwait()

This code will block for 10 seconds. However, if the line with `dispose()` is removed, it won't block at all.
