### ISSUE TITLE
2.x: publish operator always calls error handler

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#6593]
```kotlin
    val source = PublishSubject.create<Int>()
    val observer = source.publish { source }.test()

    val exception = Exception()
    source.onError(exception)
    observer.assertError(exception)
```
The code above always calls the error handler and if the error handler isn't set, then it always calls the uncaught exception handler with an `UndeliverableException`. Is there a way to avoid this problem? I don't understand what's triggering the exception since I subscribe to the source only once.

**Comment by akarnokd** [comment]
You are subscribing twice. The `publish` operator subscribes to `source` because it is the upstream for it and `publish` also subscribes to `source` again because it is the result of the function invocation. Thus you have two consumers, both get `onError` called and then only one path (upstream or inner) is then delivered to the downstream. The other goes to the global error handler.

Why are you publishing a publish subject and then ignore the shared instance too?

**Comment by JakeWharton** [comment]
For the expected behavior you would want to use `it` inside the publish lambda.

**Comment by vRallev** [comment]
That was stupid mistake. The original code uses the shared observable similar to this:
```
obs.publish { shared ->
    shared
        .debounce(time, unit, scheduler)
        .map { Unit }
        .startWith(Unit)
        .switchMap {
          Observable.concat(shared.take(1), shared.sample(time, unit, scheduler))
        }
``` 
And now I'm realizing that is subscribes twice. I somehow missed the `startWith`. I assume similar to #5911 I need to use `concatDelayError()`.

**Comment by vRallev** [comment]
No, even then I can't avoid the exception with the code. But I guess that's an issue now how I combine the operators.

**Comment by vRallev** [comment]
`switchMapDelayError` did the trick. Sorry about noise!
