### ISSUE TITLE
Question: Why a running computation thread got interrupted while window is finished

### ISSUE THREAD

**Issue by zubchenok** [ReactiveX/RxJava#6672]
Why an active computation thread got interrupted while window is finished?
```
        Observable
            .intervalRange(0, 2, 0, 1, TimeUnit.SECONDS)
            .window(1, TimeUnit.SECONDS)
            .doOnNext(i -> {
                long start = System.currentTimeMillis();
                while (System.currentTimeMillis() < start+1500) {
                }
                if (Thread.interrupted()) {
                    System.out.println("WTF? Thread is interrupted!");
                }
            })
            .ignoreElements()
            .blockingAwait();
```
Is it a bug?

**Comment by akarnokd** [comment]
This is a shortcoming of the window operator that cancels the timer before terminating, which interrupts the long running code in `doOnNext`. 

A workaround would be to move the computation to yet another thread with `observeOn` so that the interrupt won't reach it.

I'll look into the termination and timer cancellation ordering to avoid such confusing interrupts.

**Comment by zubchenok** [comment]
Could you fix it for 2.x too?

**Comment by akarnokd** [comment]
If it can be fixed, both 2.x and 3.x will receive the fix.
