### ISSUE TITLE
2.x: Backport marble fixes to Single

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6679]
The main task is to locate the relevant methods and then copy-paste the `<img>` entry.

The diff in https://github.com/ReactiveX/RxJava/pull/6668/files should help.

In case of renamed operator(s), let me know and I'll post images for them.

**Comment by thiyagu-7** [comment]
I'll take this up :)

**Comment by thiyagu-7** [comment]
The two `using` methods taking a `Supplier` as resourceSupplier in 3.x are taking a `Callable` in 2.x. Can I use the same image for these methods?

I guess the only change from 2.x to 3.x is to use a Supplier rather than a Callable. So, I suppose the marble image need not have any change for 2.x

I'll send a PR once you confirm this

**Comment by akarnokd** [comment]
Use them for now, I'll create the appropriate images for them tomorrow.

**Comment by akarnokd** [comment]
Closing via #6681
