### ISSUE TITLE
3.x: NonNull type argument annotations

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6793]
Now that we can add annotations to type arguments and type use, the functional interfaces can be defaulted and overridden as necessary.

However, I'm not familiar how the tooling (IDEs and Kotlin) is able to handle the changes.

For example, given `public interface ObservableSource<@NonNull T> {}`.

- Should `class Observable<T> implements ObservableSource<T>` repeat `@NonNull`?
- Does the use of `T`, such as `subscribe(Observer<? super T> observer)` inherit `@NonNull`?
- Does the introduction of a new argument `R` get the nullness propagated: `<R> Observable<R> map(Function<? super T, ? extends R> mapper)` where `R` is implicitly `@NonNull`?

**Comment by akarnokd** [comment]
Asking around a bit, `public interface ObservableSource<@NonNull T> {}` should be enough to set the default on `T`.

**Comment by valeriyo** [comment]
@akarnokd If it's not too much effort, perhaps 3.x annotation improvements be backported to 2.x? For example, `public interface Consumer<T>` is missing `\@NonNull` in 2.x and Kotlin compiler issues unnecessary warnings. Not sure how much effort that would be, maybe it doesn't make sense in 2.x, that's why I'm asking. And thank you so much for your continued excellent work!!!

**Comment by akarnokd** [comment]
Can't do it properly in Java 6.
