### ISSUE TITLE
Preserve 'interrupted' state in blocking methods

### ISSUE THREAD

**Issue by CheatEx** [ReactiveX/RxJava#6904]
I've noted that [BlockingMultiObserver#blockingGet()](https://github.com/ReactiveX/RxJava/blob/b3ad0752de398f4536bb88a7b1c77b0b9fbecb87/src/main/java/io/reactivex/rxjava3/internal/observers/BlockingMultiObserver.java#L87) wraps and re-throws InterruptedException. This makes hard to recover interrupted state of a thread. The general convention is to either throw IE as is or restore the interrupted state so downstream code could handle it too.

RxJava seem to partially follow this convention, see https://github.com/ReactiveX/RxJava/pull/147 and https://github.com/ReactiveX/RxJava/blob/b3ad0752de398f4536bb88a7b1c77b0b9fbecb87/src/main/java/io/reactivex/rxjava3/internal/util/BlockingHelper.java#L45 But not in the most used public methods.

Did you consider restoring interrupted state in blocking operations designed for external use, specifically in `Completable`, `Single`, `Maybe`, `Observable` `blocking*` methods?

**Comment by akarnokd** [comment]
> Did you consider restoring interrupted state

Yes and decided not to in most cases. The trouble is, restoring the interrupted state may lead to further unintended interrupts.

**Comment by CheatEx** [comment]
> further unintended interrupts

Further interrupts are intended. I would even say desired. The point usually is to terminate a thread ASAP.

**Comment by akarnokd** [comment]
Do you have a specific problem or are you just reciting some external convention without contextual considerations of RxJava?

**Comment by CheatEx** [comment]
No, I'm only learning and evaluating RxJ.

So I would really appreciate if you share those contextual considerations. Or maybe point out a resource where I can learn more about RxJavas convention for cancelling and shutdown of blocked threads.

**Comment by akarnokd** [comment]
RxJava is about non-blocking operations and cancellation is just another signal that propagates non-blockingly. However, when dealing with external, blocking APIs, cancellation does trigger thread interruption for the purpose to unblock those specific 3rd party calls. This doesn't automatically imply the next 3rd party call should be interrupted immediately just because it happens to run on the same thread.

Here are some past issues regarding similar situations: https://github.com/ReactiveX/RxJava/issues?q=is%3Aissue+interrupt+is%3Aclosed
