### ISSUE TITLE
Subscribe to Flowable using Subscriber and return Completable that completes when subscription is done

### ISSUE THREAD

**Issue by gabrielhuff** [ReactiveX/RxJava#7036]
I'm trying to implement the following:

Given a `src` `Flowable` and a `dst` `Subscriber`, create a `write` method that forwards all the emissions from `src` to `dst` and returns a `Completable`. That is:

```java
Flowable<T> src = ...
Subscriber<T> dst = ...
Completable completable = write(src, dst); // How to implement this?
```

The returned `Completable` should behave as follows:

- Complete when `src` completes
- Fail when `src` fails
- Fail when `src` gets disposed
- When disposed, cause `dst` to fail (i.e. 'canceling' the write operation)

So pretty much like the standard `Publisher#subscribe(Subscriber)` method, but returning a hot `Completable` capable of tracking the subscription state.

**Is there a simple way to do this** (i.e. by using a couple of operators)?

**Comment by akarnokd** [comment]
No. Your requirements make the signal coordination complicated. You can try with subjects, `doOnX` and `merge` methods to wire up the signals and outcomes.

Such arrangement is quite uncommon and I wonder why don't you simply use `subscribe(Consumer, Consumer, Action)` so that you can cancel it and capture the terminal signals?

**Comment by gabrielhuff** [comment]
Fair enough. It is indeed a very specific use case. Thanks for the help nevertheless.
