### ISSUE TITLE
blockingForEach doesn't receive events from concatMapSingle

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#7061]
Hi @akarnokd, it's been a while!

Playing with 3.0.4 I found something that doesn't work as I expected. Don't see any issues posted recently about it, so wondering if it's a user error on my part, or if something is wrong with concatMapSingle. 

Here is code that demonstrates it. The first example sticks to Observables and concatMap, and correctly ticks 10 times, printing to the console. The second one just switches the code to using Single and concatMapSingle, and never prints anything, even though it ticks internally.

```java
import java.util.Random;
import java.util.concurrent.TimeUnit;

import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

public class TestForEach {

	private static final Random RAND = new Random();

	public static void main(String... args) {

		// concatMap with Observable
		var o = Observable.range(0, Integer.MAX_VALUE).concatMap(i -> {
			// random delay before "sending" the request to simulate variance
			int delay = Math.max(10, RAND.nextInt(300));
			return Observable.timer(delay, TimeUnit.MILLISECONDS).take(1).map(l -> "tick " + i);
		});

		o.take(10).blockingForEach(s -> {
			System.out.println("concatMap: " + s);
		});

		// concatMap with Observable
		// THIS DOES NOT WORK, BUT I EXPECT IT TO DO THE SAME AS ABOVE
		var o2 = Observable.range(0, Integer.MAX_VALUE).concatMapSingle(i -> {
			// random delay before "sending" the request to simulate variance
			int delay = Math.max(10, RAND.nextInt(300));
			return Single.timer(delay, TimeUnit.MILLISECONDS).map(l -> "tick " + i);
		});

		o2.take(10).blockingForEach(s -> {
			System.out.println("concaptMapSingle" + s);
		});
	}

}

```

**Comment by akarnokd** [comment]
Hi Ben.

Example 2 does print 10 lines eventually and at once for me and would be considered the expected behavior. What happens is the main thread starts spitting out numbers from `range` rapidly of which 10 will eventually signal enough values so that `take` will stop `range` asynchronously. This then passes the control to the drain of `blockingForEach` which then prints the 10 items queued up in its buffer until then.

Example 1 behaves differently because `range` and `concatMap` fuse together, thus `range` no longer spits out values rapidly like above. `concatMap` then subscribes to an inner source and backs out so that the main thread can go into `blockingForEach` to wait for a value. The inner source succeeds asynchronously that allows `blockingForEach` to move forward and start the next inner source. If you put `hide` between `range` and `concatMap`, you can make it behave like Example 1.

You can somewhat avoid this same-thread blocking by using `subscribeOn` in example 2 but beware that `Observable.range` will still spit out a lot of values very rapidly thus it will most likely bog down the system.

**Comment by benjchristensen** [comment]
Isn't 'Single' supposed to be semantically equivalent to 'Observable.take(1)'? Why wouldn't the fusing behavior occur the same with 'Single' vs 'Observable.take(1)'? For me, the difference in behavior breaks the point of having 'Single', as it's no longer able to be a semantic (and performant) replacement as it was intended to be. 

So is it just that 'concatMapSingle' has not had the work done to fuse, or is there some other reason?

**Comment by benjchristensen** [comment]
By the way, I can of course just use 'Flowable' and that solves the issue with 'concatMapSingle', as it adds the backpressure. And that's what I'm doing. I was just confused by why 'Single' vs 'Observable.take(1)' aren't semantically the same in the example I originally posted. I feel they should be, otherwise it's confusing as a user why 'concatMap' and 'concatMapSingle' don't behave exactly the same (when take(1) occurs on the Observable version).

**Comment by akarnokd** [comment]
The main issue is that `Observable.range()` occupies the main thread where you also want to block for consumption. Fusion just somewhat mitigates this property. Consequently, the following source would not give up the main thread regardless of `concatMap` or `concatMapSingle`:

```java
Observable.create(emitter -> {
    int i = 0;
    while (!emitter.isDisposed() && i < Integer.MAX_VALUE) {
       emitter.onNext(++i);
    }
    emitter.onComplete();
});
```

> So is it just that 'concatMapSingle' has not had the work done to fuse,

Fusion is not implemented there but could be.

**Comment by benjchristensen** [comment]
> Fusion is not implemented there but could be.

Ah, this answers the question then. Thank you.

That is what was surprising as a user, as from an API perspective it is expected that they behave the same. But because fusion is only implemented on one of them, the behavior is not the same. My perspective is that a user should not need to understand a very nuanced difference like this. (I'm treating v3 as a user only, and not digging into the code as I would have done years ago.)

I suggest keeping this on the list then as an improvement for the future, to have `concatMapSingle` implemented with fusion, so that `Observable` vs `Single` don't behave differently. 

And yes, I know there are multiple ways of working around this, like the one you gave, or just using `Flowable`. My suggestion is that working around it should not be necessary, and that 'concatMap' and 'concatMapSingle' behave the same. 

Thank you @akarnokd for the rapid responses on this. Have a good day!
