### ISSUE TITLE
Flowable.fromPublisher work called on wrong thread

### ISSUE THREAD

**Issue by personshelldon** [ReactiveX/RxJava#7242]
Hello! I need to implement some custom behavior in my code. I need to emit new data in my `Flowable` every time when some event occurred. To get this working I wrote the next logic:
```
val signalProcessor = BehaviorProcessor.createDefault(Unit)

fun getData(id: Int): Flowable<Int> {
      return Flowable.fromPuiblisher(signalProcessor).map { 
          Log.d(TAG, "$id Current work thread name: ${Thread.currentThread().name}")
          // Some logic with id parameter here
          id
      }.subscribeOn(Schedulers.io())
}

fun sendSignal() {
    signalProcessor.onNext(Unit)
}

fun testSubscibe() {
    getData(0).subscribe {
        // Some logic with result
        Log.d(TAG, "$it Result received")
    }
    getData(1).subscribe {
        // Some logic with result
        Log.d(TAG, "$it Result received")
    }
    val thread1 = Thread {
        Log.d(TAG, "Signal from Thread1")
        sendSignal()
    }.apply {
        name = "Thread1"
    }
    val thread2 = Thread {
        Log.d(TAG, "Signal from Thread2")
        sendSignal()
    }.apply {
        name = "Thread2"
    }

    Thread.sleep(100)
    thread1.start()
    Thread.sleep(100)
    thread2.start()
}
```

## Expected result:
```
0 Current work thread name: RxCachedThread-****
0 Result received
1 Current work thread name: RxCachedThread-****
1 Result received
Signal from Thread1
0 Current work thread name: RxCachedThread-****
0 Result received
1 Current work thread name: RxCachedThread-****
1 Result received
Signal from Thread2
0 Current work thread name: RxCachedThread-****
0 Result received
1 Current work thread name: RxCachedThread-****
1 Result received
```
## Real result:
```
0 Current work thread name: RxCachedThread-****
0 Result received
1 Current work thread name: RxCachedThread-****
1 Result received
Signal from Thread1
0 Current work thread name: Thread1
0 Result received
1 Current work thread name: Thread1
1 Result received
Signal from Thread2
0 Current work thread name: Thread2
0 Result received
1 Current work thread name: Thread2
1 Result received
```

When `subscribe` method called the worker thread started from `Schedulers.io()` as expected. But when `sendSignal` called all work in `map` always runs on a thread from which `sendSignal` was called and `subscribeOn` is ignored.

## Environment
**RxJava version**: 3.0.11

**Comment by akarnokd** [comment]
`subscribeOn` affects where the subscription side-effect happen and not generally where the emission happens, especially with subjects and processors. You have to use `observeOn`.

In your case, `subscribeOn`'s side-effect is to emit the initial value of the `BehaviorProcessor` on the IO thread. Since `subscribeOn` does not affect `onNext` calls and `BehaviorProcessor` emits on whatever thread calls `onNext`, you see the non-io threads in the log.

Two more notes:
- `BehaviorProcessor` is already a `Flowable` thus `Flowable.fromPublisher` has no effect.
- You should not call `onNext` from multiple threads without proper serialization; use `toSerialized()` on the processor ensure this.
