### ISSUE TITLE
[2.x] Observable.interval() backlogs elements when cpu resources are not available.

### ISSUE THREAD

**Issue by BigPig-LittleTail** [ReactiveX/RxJava#7358]
I use RxJava[2.x] in Android project. I try to do some things on the background. So I use Observable.interval(), like this

```class LoginActivity: AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)

        findViewById<Button>(R.id.button2).setOnClickListener {
            Observable.interval(0,1,TimeUnit.SECONDS).subscribe{
                Log.e("TAG", "onSuccess $it")
            }
        }

    }
}
```

1. I start the 'interval' in my application.
2. I switch the application to the background. 
3. In the Android system, when the application is switched to the background, CPU resources may not be available, especially in the Harmony OS(support by huawei). The element is suspended
4.  After a while, I switch the app to the foreground. The elements which should have emit over the past time, finally emit on the same time.
![image](https://user-images.githubusercontent.com/32700546/140926596-78c32ea2-e164-4001-88e7-0007fb8608e5.png)

I try to read the source code and find nothing help. What should i do to avoid this situation?
###

**Comment by akarnokd** [comment]
I have limited knowledge of the Android platform in this regard so I can only offer two workarounds:

- Dispose the subscription if your app goes into the background and resubscribe when it goes into the foreground. If you need a monotone counter, use some `field++` instead of `it`.
- Keep track of the current time when your code is invoked and do nothing if the time difference between the current and last is smaller than your intended period.

I also recommend asking this type of questions on StackOverflow instead.

**Comment by BigPig-LittleTail** [comment]
Thank you!
