### ISSUE TITLE
Split Observable & Flowable interfaces 

### ISSUE THREAD

**Issue by Desislav-Petrov** [ReactiveX/RxJava#7487]
Currently, the Observable & Flowable classes contain 15k+ lines of code each. This makes navigation difficult and even IntelliJ struggles handling the large file.

Would it make sense to split the classes into subclasses/subinterfaces where some logical grouping is followed?

**Comment by akarnokd** [comment]
No. This has been considered a long time ago and doesn't work. 

The main reason is that discoverability becomes even worse because now you have to remember the categories of operators; your logic for grouping can be different from other people's or even ours thus there is no one good way of doing it for all. Second, it adds a lot of pollution to the codebase and the typebase of the library.
