### ISSUE TITLE
How is the queue Null at ObserveOnObserver.drainNormal (ObservableObserveOn.java:172). It won't happen if I update to version 3.x. `3.x` `Question`

### ISSUE THREAD

**Issue by lazyduck037** [ReactiveX/RxJava#7532]
I'm using the lib version 2.2.9. I got an exception in my project like that:
```
Caused by java.lang.NullPointerException
Attempt to invoke interface method 'boolean mx.h.isEmpty()' on a null object reference
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal (ObservableObserveOn.java:172)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run (ObservableObserveOn.java:255)
io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:109)
android.os.Handler.handleCallback (Handler.java:899)
```
Will the bug not happen, If I update to version 3.x?

**Comment by akarnokd** [comment]
Hi. That exception should be impossible. Are you using custom built operators? Is it happening on a device or in your development environment? Does it happen if you fon't obfuscate?

2.x is no longer supported.

**Comment by lazyduck037** [comment]
Hi, I'm not using a custom build. It's happing on Oppo, Realme, Huawei devices and on production.
<img width="1143" alt="Screenshot 2023-03-03 at 14 03 30" src="https://user-images.githubusercontent.com/32600174/222653889-f86696dc-65b1-4507-bd37-bf578ca11a7e.png">
<img width="1131" alt="Screenshot 2023-03-03 at 14 03 40" src="https://user-images.githubusercontent.com/32600174/222653938-61450787-0983-4cc4-81b0-6fe1f9fc5184.png">

I'm building a custom lib from v3 to logging which class happening. I cannot reproduce it in development environment. I got it on production that was obfuscate.

**Comment by akarnokd** [comment]
Most likely cause of this exception is a missing `onSubscribe` call. This happens when people accidentally implement `ObservableSource` directly, instead of using `Observable.create`. Kotlin is really prone to this because people use `{ }` to create a SAM implementation of `ObservableSource` and then call `it.onComplete()`. Also it might also help that if you don't get this in the development environment, the problem code is on a conditional path that would not get called under "ideal" condition, such as fallback sequences or error handling sequences.
