### ISSUE TITLE
Possible unsynchronized access in ReplaySubject

### ISSUE THREAD

**Issue by arkivanov** [ReactiveX/RxJava#7543]
Version: `3.1.6`

Hello! While exploring `ReplaySubject` source code, I have noticed a possible unsynchronized access to `ReplayBuffer`. Please see the following [line](https://github.com/ReactiveX/RxJava/blob/329e8c91c2999826d7e689be754857cd6f9e1f14/src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java#L773).

On that line, `UnboundedReplayBuffer#replay` method reads the `buffer` without synchronization. If I understand it correctly, while `replay` is being called from `subscribeActual`, the buffer maybe modified by another thread in `ReplaySubject#onNext`. The documentation says that only `onNext`, `onComplete` and `onError` calls must be synchronized externally, so I assume that `subscribeActual` may be called concurrently with `onNext`.

**Comment by akarnokd** [comment]
No need to synchronize it because we never read beyond the `size` attribute, which is [volatile](https://github.com/ReactiveX/RxJava/blob/329e8c91c2999826d7e689be754857cd6f9e1f14/src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java#L657). 

Since an unbounded replay buffer is append-only, updating `size` will ensure all previous writes to the list cells become visible to anyone else, provided they read `size` first and don't read beyond it.

**Comment by arkivanov** [comment]
Thanks! This assumes that `ArrayList` replaces the reference to its underlying array with already copied data, when growing capacity. So the data is first copied to the new array, and then the reference is updated. I think this is undocumented and might not be always the case in some implementations.
