### ISSUE TITLE
Maybe.fromCallable type argument nullability [RxJava 3.1.3]

### ISSUE THREAD

**Issue by fgoncalves** [ReactiveX/RxJava#7577]
I wanted a clarification on the nullability of the type parameter of [Maybe.fromCallable](https://github.com/ReactiveX/RxJava/issues). I'm mostly interested in where it's heading.

The source clearly states that the type argument cannot be null - `Maybe<@NonNull T>`. However, the documentation does state the following:

> Note that the `null` handling of this operator differs from the similar source operators in the other
   io.reactivex.rxjava3.core base reactive classes. Those operators signal a `NullPointerException` if the value returned by their
   `Callable` `null` while this `fromCallable` considers it to indicate the returned `Maybe` is empty.

Running a couple of tests, returning null in `Maybe.fromCallable` still seems to work as the documentation explains.

This is actually handy. It avoids the recurring pattern "if something is null return Maybe.empty otherwise Maybe.just`.

However, when moving to the kotlin world the situation is a bit different. Kotlin pays much more attention to the annotations and in some versions refuses to compile. Code like `Maybe.fromCallable<String> { null }` will eventually not compile.

My question is then where are we heading? Should we be ignoring the doc and changing the calls to the `if/else` "formula" or is this simply an oversight in the use of the `@NonNull` annotation? Thanks!

**Comment by akarnokd** [comment]
The method is declared as requiring `Callable<? super @Nullable T>`, which should it allow to return null and typecheck correctly. Afaik, there are a couple of bugs in Kotlin currently that can't deal with for some reason.

The unambiguous workaround is to use `Maybe.create` and simply emit a non-null T value or complete if you have a `T?` type.

The underlying issue is that RxJava is a Java language code with liberal nullability interpretations whereas Kotlin is a separate language with ever so changing interpretations and interoperation features. 

We'll do our best to enable both languages but unfortunately, there is no good way to verify every signature for Kotlin.

**Comment by fgoncalves** [comment]
Thank you!
