### ISSUE TITLE
No Development on RxKotlin

### ISSUE THREAD

**Issue by derektom14** [ReactiveX/RxJava#7607]
[RxKotlin](https://github.com/ReactiveX/RxKotlin) hasn't had any updates since 2020, so it has fallen behind several Kotlin versions and is missing methods compatible with new Kotlin libraries like `Duration`. Why is it no longer under development? The README still suggests how to add new methods, and there are many pending PRs, but they aren't being reviewed.

**Comment by akarnokd** [comment]
Because pretty much no one left to maintain and manage it.

**Comment by derektom14** [comment]
Are you looking for volunteers to maintain it?

**Comment by akarnokd** [comment]
Usually the maintainers are chosen from the community based on track record. But since we don't have a community anymore, can't just hand out admin rights to arbitrary enthusiastic contributors. They tend to leave within months, don't have the necessary feel of responsibility or riddle the project with self serving changes "otherwise my colleagues won't use my methods".

Thus, your best bet is to implement whatever convenience you need locally (this is Kotlin after all), or fork / create a brand new project will all the reign you see fit.

**Comment by derektom14** [comment]
Ah, that's a shame. Should the README's "Contributing" section [here](https://github.com/ReactiveX/RxKotlin#contributing) at least be updated to reflect that it's no longer accepting contributions?

**Comment by akarnokd** [comment]
Updated the readme.
